### ISSUE TITLE
Factor legend not ordered

### ISSUE THREAD

**Issue by jrowen** [rstudio/leaflet#106]
It would be a great enhancement to order factor labels in the legend if an ordered factor is specified.  Currently, the order appears to match the output of `unique(v)`.

**Comment by yihui** [comment]
That makes sense. I'll do it tomorrow. Thanks!

**Comment by yihui** [comment]
Okay, the legend items are ordered by the factor levels now. Please let me know if the current development version works for you.

**Comment by jrowen** [comment]
Looks good. Thanks.
