### ISSUE TITLE
how to navigate from one page to another with the R language and framework Shiny

### ISSUE THREAD

**Issue by mariemhammami** [rstudio/leaflet#107]
Hello everyone

how to navigate from one page to another with the R language and framework Shiny
like this example
https://vnijs.shinyapps.io/quant/?SSUID=a24d58ee8dce7b8c544f01e19634e6a3

thank you

**Comment by yihui** [comment]
I don't know why this issue was filed to this leaflet repo. It looks like a general shiny question. Anyway, you probably want to read this article http://shiny.rstudio.com/articles/layout-guide.html
