### ISSUE TITLE
Map Layers and Plots Rendering in the Console but not in Shiny

### ISSUE THREAD

**Issue by CarlBoneri** [rstudio/leaflet#112]
I have been wrestling with this issue for hours; I can manipulate into working in a separate window (from 'in-app') by using renderPlot/plotOutput; but my tiles are not rendering when using renderLeaflet/leafletOutput etc. 
Removed all custom css thinking that might be it; but with no luck. Also reinstalled to make sure I had the dev version running.  dataLoc is a data.frame with colnames for Lat/Lon..everything works fine in the console. I'm not running as a single-file App;libraries and data-sets are loaded from the global.R file. I have no clue why it's not working in the app and have tried every combination I can think of. 
Any help is greatly appreciated..

server <- function(input, output, session){
output$myMap <- renderLeaflet({
  leaflet(data = dataLoc) %>%
      addProviderTiles("CartoDB.DarkMatter") %>%
      addCircles(lng = ~Lon, lat = ~Lat, weight = 1,
                 color = ~dataLoc$colors,fillOpacity=.4,radius = ~fb/10, popup = content_ScMapDiv) %>%
      setView(lng = dataLoc[dataLoc$sc==scIn,"Lon"],
              lat = dataLoc[dataLoc$sc==scIn,"Lat"], zoom=7)
})
}

ui <- fluidPage(
  leafletOutput("myMap")
)

![image](https://cloud.githubusercontent.com/assets/10135058/7929814/43b8814a-08d0-11e5-9183-e88b47f55c48.png)

**Comment by jcheng5** [comment]
Strange. Can you run in a web browser and check the JavaScript console for errors?

**Comment by CarlBoneri** [comment]
// Merge data options into defaults
      var options = $.extend({ zoomToLimits: "always" }, data.options);

TypeError: data is undefined


New one on me. Any ideas?

**Comment by CarlBoneri** [comment]
![image](https://cloud.githubusercontent.com/assets/10135058/7930012/963ea942-08d2-11e5-8c4e-18e82cb0ccce.png)


Standalone in the console I don't get the error though. Doubt this helps/

**Comment by CarlBoneri** [comment]
@jcheng5 ; i wound up going back through and updating almost every library just to be sure; i'm good now(other than a few new surprises from other libs). Thanks for the response and for the work you put out.

**Comment by jcheng5** [comment]
Oh OK, thanks.

**Comment by theRanalyst** [comment]
@CarlBoneri Can you tell me which libraries you updated please? I'm having the same issue, except my maps won't render in RStudio, but display properly in a web browser. Thanks in advance!

**Comment by CarlBoneri** [comment]
@theRanalyst 
have you run:  devtools::package_deps('leaflet') to see available updates?

package_deps('leaflet') %>% datatable
![image](https://cloud.githubusercontent.com/assets/10135058/10313871/d297e038-6c1f-11e5-9b5a-c18099e495c4.png)

I'm still running 3.1.2; and i'm assuming I updated devtools,leaflet;htmlwidgets,and shiny. I'm not sure what did the trick, but have you tried any other tiles? Give this a go and see if for some reason it's the default tile not being brought in; but I have zero expertise in this troubleshooting arena. 
doubt this is any help, but best of luck.
multiMap is a helper function I use; but the output df is simply:
![image](https://cloud.githubusercontent.com/assets/10135058/10313559/3e558ba6-6c1e-11e5-9d45-c1aa84890df6.png)

multiMap('New York; Atlanta Ga;Hong Kong') %>% mutate(lats = lat,lons = lng) %>% leaflet %>%
        addProviderTiles("CartoDB.DarkMatter") %>%
       addMarkers(lat = ~lats, lng = ~lons,popup = ~name)

![lflt](https://cloud.githubusercontent.com/assets/10135058/10313543/31c098cc-6c1e-11e5-9f84-b75f40eaa039.png)

**Comment by theRanalyst** [comment]
@CarlBoneri Doing as you suggested and looking at the package dependencies, I don't get the same output

```
> devtools::install_github("rstudio/leaflet")
> library(leaflet)
> devtools::package_deps("leaflet")
Not on CRAN ----------------------------
 package      installed  available
 leaflet      1.0.1.9000 1.0.0  
```

Running the map code you provided above (although tweaked since I don't have access to your `multiMap` function) did not help either. It returned the markers and the controls at the top right, but there is no base layer. Again, the map loads perfectly fine when loaded in a web browser. Here is the code I ran:
```
> map <- leaflet() %>% addProviderTiles("CartoDB.DarkMatter") %>% addMarkers(lng=c(-74.0059413, -84.3879824, 114.109497), lat=c(40.7127837, 33.7489954, 22.396428), popup=c("New York", "Atlanta", "Hong Kong"))
> map
```

**Comment by theRanalyst** [comment]
I decided to just load all of the libraries that you listed above and run `devtools::session_info()` to see where I stood. Everything is up-to-date as far as I can tell.

```
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2015-10-06                  

Packages ----------------------------------------------------------------------------------------------------------------------------------------
 package      * version    date       source                          
 colorspace   * 1.2-6      2015-03-11 CRAN (R 3.2.2)                  
 curl           0.9.3      2015-08-25 CRAN (R 3.2.2)                  
 devtools       1.9.1      2015-09-11 CRAN (R 3.2.2)                  
 dichromat    * 2.0-0      2013-01-24 CRAN (R 3.2.2)                  
 digest       * 0.6.8      2014-12-31 CRAN (R 3.2.2)                  
 htmltools    * 0.2.6      2014-09-08 CRAN (R 3.2.2)                  
 htmlwidgets  * 0.5        2015-06-21 CRAN (R 3.2.2)                  
 httr           1.0.0      2015-06-25 CRAN (R 3.2.2)                  
 jsonlite     * 0.9.17     2015-09-06 CRAN (R 3.2.2)                  
 labeling     * 0.3        2014-08-23 CRAN (R 3.2.2)                  
 lattice        0.20-33    2015-07-14 CRAN (R 3.2.2)                  
 leaflet      * 1.0.1.9000 2015-10-06 Github (rstudio/leaflet@3b4d8a3)
 magrittr       1.5        2014-11-22 CRAN (R 3.2.2)                  
 markdown     * 0.7.7      2015-04-22 CRAN (R 3.2.2)                  
 memoise        0.2.1      2014-04-22 CRAN (R 3.2.2)                  
 mime         * 0.4        2015-09-03 CRAN (R 3.2.2)                  
 munsell      * 0.4.2      2013-07-11 CRAN (R 3.2.2)                  
 plyr         * 1.8.3      2015-06-12 CRAN (R 3.2.2)                  
 png          * 0.1-7      2013-12-03 CRAN (R 3.2.2)                  
 R6             2.1.1      2015-08-19 CRAN (R 3.2.2)                  
 raster       * 2.4-20     2015-09-08 CRAN (R 3.2.2)                  
 RColorBrewer * 1.1-2      2014-12-07 CRAN (R 3.2.2)                  
 Rcpp         * 0.12.1     2015-09-10 CRAN (R 3.2.2)                  
 rstudioapi     0.3.1      2015-04-07 CRAN (R 3.2.2)                  
 scales       * 0.3.0      2015-08-25 CRAN (R 3.2.2)                  
 sp           * 1.2-0      2015-09-08 CRAN (R 3.2.2)                  
 stringi        0.5-5      2015-06-29 CRAN (R 3.2.2)                  
 stringr        1.0.0.9000 2015-10-05 Github (hadley/stringr@5f9319b) 
 yaml         * 2.1.13     2014-06-12 CRAN (R 3.2.2) 
```

**Comment by CarlBoneri** [comment]
@theRanalyst theRanalyst
hmm...well, if it's saving and rendering into a standalone doc...try this:

assuming you saved the 'map' to 'map_test.html' in your wd;

includeHTML('map_test.html') %>% html_print

are you having trouble with any other outputs into the Viewer Pane? 

If everything else is firing i'm afraid i'll be zero help from here on....but out of curiosity try running something else into the viewer? 
df<- data.frame(vals=sample(1:100,10),dates=seq(Sys.Date()-9,Sys.Date(),by='days') %>%as.character,stringsAsFactors=F)

rCharts::mPlot(vals~dates,data=df,type='Line')


hope you get it working.

**Comment by theRanalyst** [comment]
@CarlBoneri Thanks for the help, it's definitely appreciated. `shiny::includeHTML('map_text.html') %>% htmltools::html_print()` didn't help (I used an appropriate filename on my end, but kept it the same here for readability). It properly executed, but the map still did not display. However, the `rCharts` example did work. The chart is plotted and visible and the interactive elements are there. So this appears to be isolated to the `leaflet` package in my situation. You wouldn't happen to have any ideas, would you @jcheng5?

**Comment by CarlBoneri** [comment]
@theRanalyst did you get it figured out?

**Comment by theRanalyst** [comment]
@CarlBoneri Unfortunately, no. But I've decided to sidebar the issue since I'm able to properly produce the maps and save them as HTML. While viewing it in the Viewer would be ideal, I don't want to spend too much time on it, especially when other Viewer functions are working fine.

**Comment by jcheng5** [comment]
@theRanalyst Are you on a corporate network? Maybe with a proxy that all HTTP requests have to go through?

**Comment by theRanalyst** [comment]
@jcheng5 I am on a corporate network. I've tried to figure out how I'd get around the proxy, but I'm not sure what I'd do in addition to what I've done. If I use `Sys.getenv('http_proxy')` and `Sys.getenv('https_proxy')` it returns the appropriate information. Setting R to use Internet2 doesn't work either.

**Comment by jcheng5** [comment]
Assuming you're on Windows, RStudio should use this logic from Qt:

> This will respect the proxy settings set on the registry with the proxycfg.exe tool. If those settings are not found, this function will attempt to obtain Internet Explorer's settings and use them.

Can you check both of those places for the correct setting? Thanks...

Reference: http://doc.qt.io/qt-4.8/qnetworkproxyfactory.html#systemProxyForQuery

**Comment by theRanalyst** [comment]
@jcheng5 Not sure if I did this correctly, but here is what I got for my WinHTTP settings:

![capture](https://cloud.githubusercontent.com/assets/4400394/10436719/31839d3c-70f6-11e5-8884-257dd3ee446d.PNG)

And here is what it shows for my Internet Explorer proxy:

![capture](https://cloud.githubusercontent.com/assets/4400394/10436776/8510eb6c-70f6-11e5-9317-7110201fa6f3.PNG)

Could the issue be that there is a user name and password associated with the proxy that isn't being registered by the Qt logic?
