### ISSUE TITLE
How to add reactive function?

### ISSUE THREAD

**Issue by Make42** [rstudio/leaflet#114]
I want to use rstudio/leaflet together with shiny. I am using

       output$mapplot <- renderLeaflet({
           leaflet::leafletProxy(stations) %>%
              addTiles() %>%
              addCircles(popup = ~as.character(density), opacity = 1, color = ~pal(density))
       })

to draw render my plot. I want to change the color, that pal is using, by writing something like

      colorstyle <- reactive({
           as.character(input$colorstyle)
      })
      pal <- colorNumeric(
         palette = colorstyle,
         domain = stations_shown$density
      )

which however does not work. I got the impression that functions can not be changed reactively, but only values in shiny - is that correct? Is there are way to make, what I want, happen?

Btw: colorNumeric is returning a function.

**Comment by Make42** [comment]
I am getting closer to a solution: It works if I write instead:

      colorstyle <- reactive({
             as.character(input$colorstyle)
      })

      output$mapplot <- renderLeaflet({

            pal <- colorNumeric(
                 palette = colorstyle(),
                 domain = stations_shown$density
              )

             leaflet::leaflet(stations) %>%
                addTiles() %>%
                addCircles(popup = ~as.character(density), opacity = 1, color = ~pal(density))
      })

However I would also like to get pal outside renderLeaflet(), but when I write

      colorstyle <- reactive({
             as.character(input$colorstyle)
      })

       pal <- reactiive({
            return( colorNumeric(
                    palette = colorstyle(),
                    domain = stations_shown$density
            )
       })

      output$mapplot <- renderLeaflet({

             leaflet::leaflet(stations) %>%
                addTiles() %>%
                addCircles(popup = ~as.character(density), opacity = 1, color = ~pal(density))
      })

I get the error 

       Error in pal(density) : unused argument (density)

Why is that?

**Comment by jcheng5** [comment]
Answered at https://github.com/rstudio/shiny/issues/858
