### ISSUE TITLE
Error : 'leafletProxy' is not an exported object from 'namespace:leaflet'

### ISSUE THREAD

**Issue by Make42** [rstudio/leaflet#115]
My app worked. Now I replaced leaflet() with leafletProxy() as suggested in http://rstudio.github.io/leaflet/shiny.html and I no map is displayed anymore. Instead I get the error

       Error : 'leafletProxy' is not an exported object from 'namespace:leaflet'

Why is that?

**Comment by Make42** [comment]
I figured, maybe I did not have an up-to-date version, so I ran

      devtools::install_github('rstudio/leaflet')

but after that I got the error

      Error in derivePoints(data, lng, lat, missing(lng), missing(lat), "addCircles") : 
      Point data not found; please provide addCircles with data and/or lng/lat arguments

so I figured, maybe leafletProxy() does not have leaflet()'s guessing abilities and changed my command to

      leaflet::leafletProxy(stations_shown) %>%
            addTiles() %>%
            addCircles(popup = ~as.character(density),
                  opacity = 1, 
                 color = ~pal(density),
                 lat = ~latitude,
                 lng = ~longitude)
    
which gives me, while using it without shiny, the error 

      Error in sessionFlushQueue[[sess$token]] : 
      wrong argument to index an environment

and, while using it inside shiny, the error

      Error in UseMethod("doResolveFormula") : 
      not applicable method for 'doResolveFormula' applied to object of class "NULL"

One should keep in mind, that if I use leaflet() instead of leafletProxy() everything works fine without any error.

**Comment by jcheng5** [comment]
You need to give leafletProxy() an output id, I'd try that first.

**Comment by jcheng5** [comment]
BTW, `leafletProxy` does have the same guessing abilities, but when you called `leafletProxy(stations_shown)` you were actually not providing a data argument. Instead it needs to be `leafletProxy("mapid", data = stations_shown)`, then it will work as expected.

**Comment by Make42** [comment]
That did not work completely. My code:

      leaflet::leafletProxy("densitymap", data = stations_shown()) %>%
        addTiles() %>%
        addCircles(popup = ~as.character(density),
                   opacity = 1, 
                   color = ~pal()(density),
                   lat = ~latitude,
                   lng = ~longitude) %>%
        setView(8.822825, 48.845348, zoom = 5)
    
No error is thrown, but no map printed either. I just see a gray background and the plus and minus symbols for zooming.

**Comment by jcheng5** [comment]
That's strange. Can you give a complete reproducible example?

**Comment by Make42** [comment]
Yes, I can.  My server.R file is:

      library(leaflet)

        shinyServer(function(input, output){

                output$mapplot <- renderLeaflet({

                leaflet::leaflet() %>% addTiles()

          })
  
        })

or

      library(leaflet)

      shinyServer(function(input, output){

        output$mapplot <- renderLeaflet({
          leaflet::leafletProxy("id") %>% addTiles()

        })
  
      })

while my ui.R file is:

      shinyUI(fluidPage(
            leafletOutput("mapplot")
      ))

**Comment by jcheng5** [comment]
`leafletProxy()` doesn't go inside `renderLeaflet`, but `observe()`. Sorry, the examples in the docs are not good right now. But the basic idea is that you still use `renderLeaflet(leaflet() %>% ...)` to generate a map initially, and then make `leafletProxy()` calls inside of `observe()` (or `observeEvent()`) to modify that data.

Here's an example: https://github.com/rstudio/leaflet/blob/master/inst/examples/shiny.R

**Comment by Make42** [comment]
Ok, thanks. I'm still not able to get it to run, within my project:

In my ui.R I have:

      selectInput("analysistype",
                  label = "This or That:",
                  choices = list( "This" = "this",
                                  "That" = "that"),
                  selected = "this"),

while in my server.R I have:

    output$mapplot <- renderLeaflet({
    
      leaflet::leaflet(data = grid_shown()) %>%
        addTiles() %>%
        addCircles(popup = as.character(column()),
                   opacity = 1, 
                   color = pal()(column()),
                   layerId = as.character(1:nrow(grid_shown()))) %>%
        setView(8.822825, 48.845348, zoom = 5)
    
    })
    observeEvent(input$analysistype, {
      leafletProxy("mapplot") %>%
        addCircles(popup = as.character(column()),
                   opacity = 1, 
                   color = pal()(column()),
                   layerId = as.character(1:nrow(grid_shown())))
    })

and I get the error

       Warning:  Unhandled error in observer: not applicable method for 'doResolveFormula' applied on object of class  "NULL"
       observeEvent(input$analysistype)

Is this about the id of analysistype? If so, how do I set this correctly?

Btw: Maybe you can unclose the issue...?

**Comment by jcheng5** [comment]
Actually rather than unclose the issue, let's take this discussion off GitHub--we're just debugging your code at this point rather than investigating a potential Leaflet bug. I'll answer your last question but please email me at joe@rstudio.com or on [shiny-discuss](https://groups.google.com/d/forum/shiny-discuss) if you want to reply.

The problem is probably that in `leaflet::leaflet(data = grid_shown())`, `grid_shown()` is returning `NULL`, at least initially. You have a couple of options. One fix is to check for `NULL` everywhere you use `grid_shown()` and return early. The other fix is to use `shiny::validate` in the `grid_shown` reactive to abort any processing if there isn't enough data for `grid_shown` to properly return a non-`NULL` value--it's something you have to learn how to do but the result is more concise and robust. See [this article](http://shiny.rstudio.com/articles/validation.html) for details or email me your complete source code.

**Comment by Make42** [comment]
I got it to work! Puuuh. The solution is to

1) not add circles at leaflet::leaflet(), but only from leaflet::leafletProxy(),
2) not give leaflet::leaflet() any data,
3) use observe({}) around leaflet::leafletProxy() instead of observeEvent({}).

Regarding 3: My impression is that observeEvent is only needed if code should be run, after the change of an input object that is not directly mentioned in ui.R or if the object listened to is not used in the code. This is the case for clicking a map for example.

**Comment by jcheng5** [comment]
Yes, 1-3 is the pattern I've found useful as well. I'll be sure to update the docs next week to reflect that.

Regarding observe vs. observeEvent: observe works reactively, it automatically reexecutes whenever any of its dependencies change. This is normally what you want.

observeEvent should be reserved for cases where you do not want to automatically reexecute whenever your dependencies change. Instead, only re-execute when a single explicitly specified input changes (the thing that you pass to the first argument).

So your previous impression was partly incorrect--it has nothing to do with whether the object is mentioned in ui.R. If the object listened to is not used in the code AND it is important that be the ONLY reason a reexecution happens, then that's when you would use observeEvent.

cc @daattali: I've been meaning to convey this to you, as I noticed you sometimes use observeEvents where I would stick with observe, e.g.

```r
observeEvent(input$text, {
  toggleState("radios", nchar(input$text) > 3)
})
```

to me ought to be

```r
observe({
  toggleState("radios", nchar(input$text) > 3)
})
```

**Comment by Make42** [comment]
So what do you do if an the object is not used in the code, but the code should *additionally* be re-executed if another input object is changed?

Also: What should be done if there are *multiple* objects that are not used in code, but the change of *each single one* - or alternatively the change of *all* (which I imagine would be even trickier) - should re-execute the code?

**Comment by daattali** [comment]
It is kind of in the shiny tutorial - to make an observer or reactive expression evaluate when an input changes, you just need to use that input in the code. Even just having an expression be `input$btn` counts. You don't necessarily have to do anything important, just have it in there.

The same goes for multiple objects. If you have an observer with some code and you also want it to run when `input$btn1` or `input$btn2` change, just do

```
observe({
  input$btn1
  input$btn2
  ...
})
```

I would recommend posting any further questions to the [shiny discuss google group](https://groups.google.com/forum/#!forum/shiny-discuss) unless they're directly related to leaflet and this issue
