### ISSUE TITLE
Error in icon$iconUrl : $ operator is invalid

### ISSUE THREAD

**Issue by pfuhlert** [rstudio/leaflet#117]
Hi, 

thanks for working on that package. I was just trying out the stuff here:

http://myrprogram.blogspot.de/2015/03/experiments-with-leaflet-package-for-r.html

but when I try to add an icon like this:

mymap %>% addMarkers(data=df,df[1,"Lon"],df[1,"Lat"], popup = "Test",
                              icon = JS("L.icon({iconUrl: 'http://icons.iconarchive.com/icons/artua/star-wars/128/Master-Joda-icon.png',
                                               iconSize: [75, 75]
                                               })"))

 I get the following error:
Error in icon$iconUrl : $ operator is invalid for atomic vectors

Do you have any idea what is going on?

**Comment by jcheng5** [comment]
We've greatly improved the way custom icons are handled. See the documentation and example here:
http://rstudio.github.io/leaflet/markers.html

**Comment by pfuhlert** [comment]
Wow thanks for the fast reply. It works perfectly!
