### ISSUE TITLE
Setting the shape of a marker equal to a variable?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#127]
My data looks something like this:

    df1 <- data.frame(long=c(0.6,1,1.4), lat=c(-2, -.8, -0.2), color=c(10,8,6), 
                      shape=c('A', 'A', 'B'), size=c(2,4,6)) 

I would like to set the shape of the markers equal to `shape`. Is that possible? Right now my code looks like this:

    library(leaflet)
    # Create a continuous palette function
    pal <- colorNumeric(
      palette = "Reds",
      domain = df1$color
    )    
    leaflet(height = "400px") %>% 
      addTiles() %>%
      addCircleMarkers(data = df1, lat = ~lat, lng =~long, 
                       radius = ~size,
                       color = ~pal(color),
                       stroke = FALSE, fillOpacity = 0.9) 

thanks!

**Comment by jcheng5** [comment]
We don't have text-based markers, the closest you could do with the current feature set is custom icons:
http://rstudio.github.io/leaflet/markers.html#customizing-marker-icons
