### ISSUE TITLE
[Feature request] [Leaflet.awesome-markers plugin]

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#128]
It would be great to have https://github.com/lvoogdt/Leaflet.awesome-markers implemented in R. Having markers that can change color and size according to a variable would be very useful.

Thanks for your great work!

**Comment by yihui** [comment]
It is already on our list #91.

**Comment by ignacio82** [comment]
Thanks a lot @yihui . Can you give me an idea of how long it will take to implement? Couple of weeks, months, half-year, etc?

**Comment by yihui** [comment]
I don't think it is difficult to implement. I will discuss with the team and let you know.

**Comment by jcheng5** [comment]
@ignacio82 We don't generally make promises about when features will or won't make it in. Most of the time it's not a matter of how long it would take to implement, but rather weighing the opportunity cost of all the other work we want to do.

That said, I think it'd be a very useful feature too...

**Comment by ignacio82** [comment]
@jcheng5 I understand, I was just trying to decide if I should look for an alternative solution or wait for this one. Thanks for your amazing work!

**Comment by bhaskarvk** [comment]
@jcheng5 I've added awesome marker support in my pull request https://github.com/rstudio/leaflet/pull/184.
