### ISSUE TITLE
DivIcon

### ISSUE THREAD

**Issue by botanize** [rstudio/leaflet#130]
Please support DivIcon in addition to image icons.This would greatly simplify creating all sorts of custom icons.
http://leafletjs.com/reference.html#divicon

**Comment by bhaskarvk** [comment]
In master you can now do `addLabelOnlyMarkers`, there is also `addAwesomeMakers` w/ options to customize. 
Closing for now, but feel free to reopen if DivIcon support is a must.

**Comment by botanize** [comment]
AwesomeMarkers certainly do look awesome, but they don't replace the fully custom functionality of DivIcon markers. I'm not sure this is a huge priority, but I think it's worth exposing as much of the leaflet API as possible.
