### ISSUE TITLE
addLegend with addRaster?

### ISSUE THREAD

**Issue by lbuckley** [rstudio/leaflet#133]
Followed the leaflet raster example https://gist.github.com/jcheng5/a1c48a18d0ea3623c0e6. I manually sourced the addLegend and associated functions, but can't figure out how to modify addLegend (e.g., the value argument) to work with rasters. Leads or an addLegend function compatible with rasters would be appreciated. Thank you.

**Comment by jcheng5** [comment]
I think just values=values(r) should work, can you try that?

**Comment by lbuckley** [comment]
Thank you for the tip. <code> addLegend(pal=pal, values=values(r))</code> returns <code> Error in UseMethod("lhs") : 
      no applicable method for 'lhs' applied to an object of class "c('double', 'numeric')"</code>. The line  <code> values = evalFormula(values, getMapData(map)) </code> is causing the initial error in a series.
      
I found in some additional troubleshooting that I'm running into broader issues with AddLegend when I install the version of leaflet with addRaster (<code>devtools::install_github("rstudio/leaflet@raster")</code>).  AddLegend examples (not on rasters) no longer run following the install.  Trying to work out the inconsistencies and to develop an example.

**Comment by mbacou** [comment]
FYI addLegend() works for me with addRasterImage() no problem. Have an example end of that page http://tools.harvestchoice.org/cell5mValidate/ (source: https://github.com/harvestchoice/hc-shiny/blob/master/cell5mValidate/viValidate.Rmd ).

**Comment by lbuckley** [comment]
Thanks, Melanie. It's now working for me as well.  I think I was running into version inconsistencies.  Noticed that there is now a nice example here as well: <a href= "https://rstudio.github.io/leaflet/raster.html">https://rstudio.github.io/leaflet/raster.html</a>.
