### ISSUE TITLE
Does input$mymap_marker_mouseover work?

### ISSUE THREAD

**Issue by efh0888** [rstudio/leaflet#134]
I've just tried to implement an info control utilizing input$mymap_marker_mouseover but it remains NULL even when I hover over different markers, using markers added by both addCircleMarkers() and addMarkers(). Do you guys know if there's a bug?

EDIT: so I figured out the issue, namely, I have a submitButton. It seems like it'd make the most sense to exclude certain inputs, such as these, from the submit button behavior. What do you think?

**Comment by yihui** [comment]
Just a minimal example showing this works:

```r
library(leaflet)
library(shiny)
shinyApp(
  ui = fluidPage(leafletOutput('mymap'), verbatimTextOutput('marker_id')),
  server = function(input, output) {
    output$mymap = renderLeaflet({
      leaflet() %>% addMarkers(0:1, 0:1, layerId = c('foo', 'bar'))
    })
    output$marker_id = renderPrint(input$mymap_marker_mouseover)
  }
)
```

Yes, submitButton() will hold all inputs. This is essentially the same issue as https://github.com/rstudio/shiny/issues/303 and please see Joe's reply there.

**Comment by jcheng5** [comment]
submitButton is useful only for the most simplistic cases. If I had thought of actionButton/observeEvent back then I probably would not have included submitButton at all.

**Comment by efh0888** [comment]
Joe and Yihui,

Thanks for the quick replies. I'll look more at issue #303 and into the realms of actionButton, observeEvent and isolate for a solution.
