### ISSUE TITLE
leaflet map stays blank (grey) [Ubuntu 14.04]

### ISSUE THREAD

**Issue by chamaoskurumi** [rstudio/leaflet#136]
I tried out the example

```
devtools::install_github("rstudio/leaflet");library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852,
    popup="The birthplace of R")
m  # Print the map
```
but it only produced a grey, blank map in the RStudio Viewer, as well as in my Firefox 38.0. Maybe this has something to do with Ubuntu?
Here my sessionInfo:

```
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8     LC_MONETARY=de_DE.UTF-8   
 [6] LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet_1.0.0.9999 rgdal_0.9-2        sp_1.0-17         

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.5        magrittr_1.5       devtools_1.7.0     MASS_7.3-41        munsell_0.4.2      colorspace_1.2-6   lattice_0.20-31   
 [8] stringr_0.6.2      httr_0.6.1         plyr_1.8.1         tools_3.2.1        grid_3.2.1         gtable_0.1.2       htmltools_0.2.6   
[15] yaml_2.1.13        digest_0.6.8       RJSONIO_1.3-0      RColorBrewer_1.1-2 reshape2_1.4.1     ggplot2_1.0.1      htmlwidgets_0.3.2 
[22] bitops_1.0-6       RCurl_1.95-4.5     scales_0.2.5       proto_0.3-10      
```

**Comment by jcheng5** [comment]
Can you check your web browser's JavaScript console for any errors?

**Comment by djhurio** [comment]
I am getting the same blank (grey) screen in RStudio Desktop (on Windows). I am getting following errors in the console:

Failed to load resource: Connection timed out http://b.tile.openstreetmap.org/15/32292/19996.png
Failed to load resource: Connection timed out http://b.tile.openstreetmap.org/15/32291/19997.png
Failed to load resource: Connection timed out http://b.tile.openstreetmap.org/15/32290/19995.png
Failed to load resource: Connection timed out http://b.tile.openstreetmap.org/15/32289/19996.png
Failed to load resource: Connection timed out http://b.tile.openstreetmap.org/15/32293/19995.png

But I can open the files if I just copy the link in the browser.

I have another instance of RStudio - RStudio Server (on linux) and I can not observe the same problem there.

**Comment by Eflores89** [comment]
same issue. Mac OS X. Seems to work depending on time of day (12 hrs ago it worked fine, same example right now is just gray).

**Comment by jcheng5** [comment]
Seems like openstreetmap issues, maybe? No problem for me right now.

**Comment by jcheng5** [comment]
Next time this happens maybe check https://wiki.openstreetmap.org/wiki/Platform_Status and see how the `render` and `tile` services are doing.

**Comment by dvictori** [comment]
I'm noticing the same issue. Tried the same example used by  chamaoskurumi and in the console I got the "Failed to load resource" error. But, when I opened the the map in Firefox (show in new window button), it worked. I believe it has something to do with proxy. I use Win10 and the system proxy settings has a http proxy server however, localhost calls will not go trough the proxy. Could that be the problem?

**Comment by bhaskarvk** [comment]
@djhurio / @chamaoskurumi Were either of you behind a SOCKs proxy or any forward proxy server ? Also did you try it with a base map provider other than OSM ? As this seems like a sporadic issue I suspect either OSM availability issues or proxy issues as @dvictori has mentioned. If you are indeed behind a proxy you can setup R to access web resources through a proxy as described in [this guide](https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy).
I am closing this for now, but feel free to reopen and add additional information.
