### ISSUE TITLE
MarkerclusterOptions to fit already specified polygons 

### ISSUE THREAD

**Issue by The-Dub** [rstudio/leaflet#138]
Hi,
I was going through the options for the newly implemented plug in MarkerCluster, and I couldn't find out if there was a way to use already specified boundaries to cluster the marker.

More details on the project. I'm trying to group markers by state, and then by county, using the shapes from the map package. From what I understood, the markercluster plugin in Rstudio creates shapes and then cluster the markers, but I might be wrong...

If it exists, could somebody give me a hint here, it would be greatly appreciated !

thank you very much.

**Comment by yihui** [comment]
Reading the documentation of the MarkerCluster plug-in, I don't see a way to specify the boundaries of clusters: https://github.com/Leaflet/Leaflet.markercluster so I don't think we can support it in this package, either. Sorry.

**Comment by The-Dub** [comment]
Damn, that's what I was fearing...
thanks for the answer yihui !
