### ISSUE TITLE
Is is possible to Customize the Clustered Markers?

### ISSUE THREAD

**Issue by agstudy** [rstudio/leaflet#140]
Is possible to customize the cluster marker icon ?  

For example , adding my own function for creating the Icon for the clustered markers. The quivalent in java script is :
```
var markers = new L.MarkerClusterGroup({
    iconCreateFunction: function(cluster) {
        return new L.DivIcon({ html: '<b>' + cluster.getChildCount() + '</b>' });
    }
});
```

Thank you in advance..

**Comment by yihui** [comment]
Yes, I believe you can use the `JS()` function, e.g.

```r
addMarkers(..., clusterOptions = list(iconCreateFunction = JS("
  function(cluster) {
    return new L.DivIcon({ html: '<b>' + cluster.getChildCount() + '</b>' });
  }
")))
```

**Comment by bhaskarvk** [comment]
I double checked and this works. Though adding CSS to a said icon will have to be added inline.
