### ISSUE TITLE
Fictional map?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#143]
Is it possible to use a fictional map with leaflet and add some markers to it? For example, I found http://opengeofiction.net/#map=9/59.2097/21.5222&layers=N

Thanks!

**Comment by jcheng5** [comment]
Seems to work:

```r
leaflet() %>% addTiles("http://opengeofiction.net/osm_tiles/{z}/{x}/{y}.png") %>%
  setView(21.5222, 59.2097, 9)

**Comment by ignacio82** [comment]
This is not longer working. Do you know if opengeofiction changed something??

**Comment by ignacio82** [comment]
To answer my own question:

leaflet() %>% addTiles("http://tile.opengeofiction.net/osmcarto/{z}/{x}/{y}.png") %>%
  setView(21.5222, 59.2097, 9)
