### ISSUE TITLE
Difficulty in clicking Circles in browser.  CircleMarkers unresponsive

### ISSUE THREAD

**Issue by pssguy** [rstudio/leaflet#147]
I am trying to have a map with clickable circles. The logic works fine and performs smoothly in RStudio but in a browser it is much more difficult to obtain a clickable area.

 Here is a toy example

```{r}
library(leaflet)
library(shiny)
app <- shinyApp(
 
  ui = bootstrapPage(
    
    leafletOutput('map'),
    textOutput('text')
   
  ),
  server = function(input, output) {
    output$map <- renderLeaflet({ 
      
      df <- data.frame(lng=-120,lat=+49,id=1)
      
      df %>% 
        leaflet() %>%
        addTiles() %>%
        addCircles(
          radius = 10,fillOpacity = 0.5,layerId =  ~ id)
      
      })
    
    output$text <- renderText({
      if (is.null(input$map_shape_click$id)) return()
      input$map_shape_click$id
    })
  }
)
runApp(app)
)
```

If I replace addCircles with addCircleMarkers, the clicking is not a problem but the map_shake_click does not work 

```{r}
library(leaflet)
library(shiny)
app <- shinyApp(
 
  ui = bootstrapPage(
    
    leafletOutput('map'),
    textOutput('text')
   
  ),
  server = function(input, output) {
    output$map <- renderLeaflet({ 
      
      df <- data.frame(lng=-120,lat=+49,id=1)
      
      df %>% 
        leaflet() %>%
        addTiles() %>%
        addCircleMarkers(
          radius = 10,fillOpacity = 0.5,layerId =  ~ id)
      
      })
    
    output$text <- renderText({
      if (is.null(input$map_shape_click$id)) return()
      input$map_shape_click$id
    })
  }
)
runApp(app)
)
```

**Comment by jcheng5** [comment]
I think for circle markers it's map_marker_click.

**Comment by pssguy** [comment]
Wow. That has to be a record response time. Yes that is correct

However, aesthetically. I prefer the circles so could you check that out as well
I seem to have to get to a radius=4 using CircleMarkers to get an easy response and for my
app which has a load of markers this isn't the best look. I'm using Chrome 

 [Check it out](https://mytinyshinys.shinyapps.io/climate)
cheers

**Comment by jcheng5** [comment]
For circles, the problem is that the units are in meters, not pixels. So you'll have to go much, much bigger than 10 if you want them to be easily visible/clickable. :)
