### ISSUE TITLE
Leafletproxy error with Shiny server

### ISSUE THREAD

**Issue by sanchez5674** [rstudio/leaflet#151]
Hi, 

A couple of days ago I asked this question in the Shiny discuss forum but I did not get any answers. Maybe, I have more luck here as I don't even know where to start to debug the problem. 

I have copied and pasted this example from the RStudio Leaftet page. It works fine running locally (runApp) but the JS explodes if I run it via Shiny server. As far as I can tell, it does not like the leafletProxy call. 

ui.R is as follows:
```
library(shiny)
library(leaflet)
library(RColorBrewer)

bootstrapPage(
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  leafletOutput("map", width = "100%", height = "100%"),
  absolutePanel(top = 10, right = 10,
                sliderInput("range", "Magnitudes", min(quakes$mag), max(quakes$mag),
                            value = range(quakes$mag), step = 0.1
                ),
                selectInput("colors", "Color Scheme",
                            rownames(subset(brewer.pal.info, category %in% c("seq", "div")))
                ),
                checkboxInput("legend", "Show legend", TRUE)
  )
)
```
server.R is as follows:

```
server <- function(input, output, session) {
 
  # Reactive expression for the data subsetted to what the user selected
  filteredData <- reactive({
    quakes[quakes$mag >= input$range[1] & quakes$mag <= input$range[2],]
  })
 
  # This reactive expression represents the palette function,
  # which changes as the user makes selections in UI.
  colorpal <- reactive({
    colorNumeric(input$colors, quakes$mag)
  })
 
  output$map <- renderLeaflet({
    # Use leaflet() here, and only include aspects of the map that
    # won't need to change dynamically (at least, not unless the
    # entire map is being torn down and recreated).
    leaflet(quakes) %>% addTiles() %>%
      fitBounds(~min(long), ~min(lat), ~max(long), ~max(lat))
  })
 
  # Incremental changes to the map (in this case, replacing the
  # circles when a new color is chosen) should be performed in
  # an observer. Each independent set of things that can change
  # should be managed in its own observer.
  observe({
    pal <- colorpal()
   
    leafletProxy("map", data = filteredData()) %>%
      clearShapes() %>%
      addCircles(radius = ~10^mag/10, weight = 1, color = "#777777",
                 fillColor = ~pal(mag), fillOpacity = 0.7, popup = ~paste(mag)
      )
  })
 
  # Use a separate observer to recreate the legend as needed.
  observe({
    proxy <- leafletProxy("map", data = quakes)
   
    # Remove any existing legend, and only if the legend is
    # enabled, create a new one.
    proxy %>% clearControls()
    if (input$legend) {
      pal <- colorpal()
      proxy %>% addLegend(position = "bottomright",
                          pal = pal, values = ~mag
      )
    }
  })
}
```

Everything runs fine locally but I get a very non-descriptive error if I run the app via shiny server which seems to point to leafletProxy as the source of the error:

```
Listening on http://127.0.0.1:55286
Warning: Unhandled error in observer: wrong arguments for subsetting an environment
observe({
    pal <- colorpal()
    leafletProxy("map", data = filteredData()) %>% clearShapes() %>%
        addCircles(radius = ~10^mag/10, weight = 1, color = "#777777",
            fillColor = ~pal(mag), fillOpacity = 0.7, popup = ~paste(mag))
})
```

Any ideas what might be causing the problem? I am using the same machine to run locally and via Shiny server.

Thanks,

Carlos

**Comment by jcheng5** [comment]
Sorry you didn't get a response on shiny-discuss. I'm having a hard time keeping up these days.

Very strange--your example works fine for me both locally and with Shiny Server. What version of Shiny Server are you using (or is this on ShinyApps.io)?

**Comment by sanchez5674** [comment]
Hi Joe, 

Let me first say you guys do an excellent job answering questions.  Thanks!

The problem is very strange indeed. I just checked and I'm running Shiny Server v1.2.1.362 on a Red Hat 6.6 server. The Shiny server version is probably pretty old but it did not give any problems until now. Let me try the newer version and see if that fixes the problem. 

Thanks again!

**Comment by sanchez5674** [comment]
Hi, 

I upgraded to the latest version of shiny-server but I'm still getting the same problem. I turned shiny.trace on to see if I learned anything but the console information is not telling me anything:

```
"
Listening on http://127.0.0.1:53926
SEND {
 "config": {
 "workerId": "",
"sessionId": "a3f8ebfbba293ea67dfd6a6742123332" 
} 
}
RECV {"method":"init","data":{"legend":true,"colors":"BrBG","range":[4,6.4],".clientdata_output_map_hidden":false,".clientdata_pixelratio":1,".clientdata_url_protocol":"http:",".clientdata_url_hostname":"10.210.4.65",".clientdata_url_port":"3838",".clientdata_url_pathname":"/sample-apps/Leaflet/",".clientdata_url_search":"",".clientdata_url_hash_initial":"",".clientdata_singletons":"",".clientdata_allowDataUriScheme":true}}
Warning: Unhandled error in observer: wrong arguments for subsetting an environment
observe({
    pal <- colorpal()
    leafletProxy("map", data = filteredData()) %>% clearShapes() %>% 
        addCircles(radius = ~10^mag/10, weight = 1, color = "#777777", 
            fillColor = ~pal(mag), fillOpacity = 0.7, popup = ~paste(mag))
})
" shiny-server.js:224:47
"Thu Jul 23 2015 11:44:47 GMT+0200 (Romance Standard Time): Connection closed. Info: {"type":"close","code":1000,"reason":"Normal closure","wasClean":true}"
```

If I remove the leafletProxy calls everything loads fine. Any ideas? 

Thanks for your help. 

Carlos

**Comment by sanchez5674** [comment]
Hi, 

It seems the leafletProxy calls are not causing the app to explode. It is the calls to clearShapes or addCircles which make the app very unhappy. 

By the way I'm running:
_ Red Hat 6.6
_ R 3.1.2
_ Shiny server 1.4

Carlos

**Comment by zhongxiali** [comment]
try to change the height to 900px instead of 100%

**Comment by jcheng5** [comment]
What version of Shiny is running on the server? (Note that the Shiny version installed on your server user account's personal library is probably not what is running when Shiny Server is involved--but rather either the `shiny` user's personal library, or the machine-wide library)

**Comment by sanchez5674** [comment]
Hi Joe, 

I apologize for not closing this before but I've been on travel and I totally forgot. Anyway, I was running an older version of htmlwidgets and that was causing my problems. Once I updated that package everything was working fine. 

Thanks!
