### ISSUE TITLE
leafletOutput inside shiny document

### ISSUE THREAD

**Issue by ziyadsaeed** [rstudio/leaflet#154]
leafletOutput doesn't show the map inside the shiny document. This is different than shiny app, where you use ```leafletOutput("map")``` inside the ui function and ```output$map <- renderLeaflet({ ...})``` inside server function.

In a shiny document you don't have ui and server functions and the above commands don't show any map. Map is shown if i use ```renderLeaflet({...})``` directly. But then I'm unable to Assign a MAPID to my map

**Comment by jcheng5** [comment]
I can't repro. This works for me:

```
---
title: "Untitled"
runtime: shiny
output: html_document
---

```{r}
library(leaflet)
leafletOutput("map")
output$map <- renderLeaflet({
  leaflet() %>% addTiles()
})

**Comment by ziyadsaeed** [comment]
add width and height, the map won't show

    leafletOutput("map" ,width = "50%", height = "100%")

**Comment by pssguy** [comment]
Same issue with setting width and height in shiny
Also in shiny initial map shows but with new set of data just grey. Will produce toy example in next day or so

**Comment by yihui** [comment]
I think `height = '100%'` was the culprit. An absolute height should work. It is unclear to me what 100% height means in this case.

**Comment by ziyadsaeed** [comment]
the leaflet shiny documentation uses height 100%. perhaps you should remove it from there.

**Comment by jcheng5** [comment]
@ziyadsaeed Do you mean here? http://rstudio.github.io/leaflet/shiny.html

**Comment by ziyadsaeed** [comment]
yes jcheng5

**Comment by yihui** [comment]
In that case, 100% is meaningful because of `tags$style(type = "text/css", "html, body {width:100%;height:100%}")`. If you want to create an elment of 100% height of the window, you may see this post for example: http://stackoverflow.com/questions/19122392/div-height-100-percent
