### ISSUE TITLE
100% height

### ISSUE THREAD

**Issue by zhongxiali** [rstudio/leaflet#156]
I was trying to set the leafletOutput with a 100% height, then the app just doesn't show anything and also popped a lot of error message.
I know the div() with style.css work around, but then the div it position:fixed. change it to relative will make it crush again.

**Comment by jcheng5** [comment]
In HTML, I believe `height:100%` and `position:relative` don't make sense to combine unless the parent element has a fixed height (and maybe not even then). What exactly are you trying to do?

**Comment by zhongxiali** [comment]
I was trying to put leaflet work with the shiny dashboard, let the map move when the side menu move out.
I played around with the outer CSS and finally find a way to make it work!
Thank you for your work on shiny and leaflet! It's really amazing work!

**Comment by jcheng5** [comment]
Great, glad you were able to figure it out!
