### ISSUE TITLE
urlTemplate specification

### ISSUE THREAD

**Issue by neuwirthe** [rstudio/leaflet#157]
The documentation seems not to indicate how to specify an urlTemplate for multiple urls
I want to use
`http://maps{s}.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png`
with the possible values for {s}
'','1','2','3','4'

How do I specify this?

**Comment by jcheng5** [comment]
This should work:

```
leaflet() %>%
  addTiles("http://maps{s}.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png",
      options = tileOptions(subdomains = "1234"))
```

**Comment by neuwirthe** [comment]
Alas, this does not work!

**Comment by jcheng5** [comment]
It works for me (though you have to zoom in quite a bit to get to the part of the map that actually has some content).

```r
leaflet() %>% setView(15, 46, zoom = 6) %>%
  addTiles("http://maps{s}.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png",
    options = tileOptions(subdomains = "1234"))
```

**Comment by einarhjorleifsson** [comment]
nice, thanks @jcheng5 for highlighting this option(s) in the leaflet package.
throwing in my towel here for further clarification to @neuwirthe: adding a more "global perspective" as an underlay to the austrian tiles one could do:
```
leaflet() %>% 
  setView(15, 46, zoom = 3) %>%
  addTiles(urlTemplate = "http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
           group="world") %>%
  addTiles(urlTemplate = "http://maps{s}.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png",
           options = tileOptions(subdomains = "1234"),
           group="austria") %>%
  addLayersControl(
    overlayGroups = c("world","austria"),
    options = layersControlOptions(collapsed = FALSE))
```
marvellous work you are doing.
einar

**Comment by jcheng5** [comment]
@einarhjorleifsson Nice.

I just noticed that the wien.gv.at server returns a lot of 404s. If that bothers you, you can specify bounds so that Leaflet will not request tiles that don't exist. The syntax is rather ugly unfortunately:

```r
addTiles("http://maps{s}.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png",
    options = c(tileOptions(subdomains = "1234"), list(bounds = list(list(46, 9.5), list(49.5, 17.5)))))
```

Note that the nested list for the bounds is in `lat, lng` order instead of `lng, lat`. Sigh...

**Comment by neuwirthe** [comment]
Thanks for all your help. I will work through this and report.
