### ISSUE TITLE
leaflet crash if leafletproxy("mymap")%>%addtiles() run after renderleaflet

### ISSUE THREAD

**Issue by zhongxiali** [rstudio/leaflet#160]
I am working on an app that use both shiny dashboard and leafletR.
the app has something heavy calculation in reactive().
I put output$mymap1 <-renderLeaflet(leaflet()) in the server to initialize the map. It seems like renderleaflet() will wait for those reactive and observe functions and run right before them.
However, if anyone click on another dashboard tab during the process will cause the renderleaflet() to hang and then things like leafletproxy("mymap")%>%addtiles() will crash the app.

I have been stuck on this problem for days and I was wondering if anyone can help me.
I tried session$onflush, observe(priority), and all kinds of stuff, but nothing works.
I was wondering if there is any way to force output$mymap1 <-renderLeaflet(leaflet())  to run immediately

Thank you!

**Comment by bthieurmel** [comment]
Perhaps you can try : 
``````
outputOptions(output, "mymap1", suspendWhenHidden = FALSE)
``````

**Comment by jcheng5** [comment]
I'd be very interested in reproducing this problem. Would it be possible to see your code? You can email me at joe@rstudio.com if you'd prefer to send it privately.

**Comment by sckott** [comment]
`leafletR` has a function `leafletR:::print.leaflet()` that causes problems, could that be the culprit
