### ISSUE TITLE
Potential bug - leafletProxy does not reset map properly after receiving all 0's

### ISSUE THREAD

**Issue by efh0888** [rstudio/leaflet#164]
In the below code, GAdata() returns a data.table and based on user input it is possible that the m numeric column contains only 0 entries. When that happens the map shows no markers as expected. However, from that point on I get strange results, i.e. no matter how I change the inputs the map only displays values for the same countries that had rows in the data.table with all 0 entries.

```
leaflet() %>%
      addTiles(group = "OpenStreetMap") %>%
      addProviderTiles(provider = "Stamen.TonerLite", group = "Stamen Toner Lite") %>%
      addLayersControl(baseGroups = c("MapBox High Contrast", "Stamen Toner Lite", "OpenStreetMap"),
                       position = "bottomleft",
                       options = layersControlOptions(collapsed = FALSE))%>%
      setView(lng = 80.85937, lat = 25.48295, zoom = 2)

...

pal <- colorNumeric(
      palette = brewer.pal(9, "Blues")[6:9],
      domain = GAdata()$m
    )

rad <- function (y) log(y$m) + 3

leafletProxy("mymap", data = GAdata()) %>%
        clearMarkers() %>%
        clearControls() %>%
        addCircleMarkers(fillOpacity = 0.9,
                         lng = ~longitude, 
                         lat = ~latitude, 
                         layerId = ~loc,
                         stroke = FALSE, 
                         color = ~pal(m),
                         radius = ~rad(GAdata())
```

I know I am resetting GAdata() properly overall based on the inputs because this solves my problem:
```
if(sum(GAdata()$m) > 0) {
    leafletProxy("mymap", data = GAdata()) %>%
            clearMarkers() %>%
            clearControls() %>%
            addCircleMarkers(fillOpacity = 0.9,
                             lng = ~longitude, 
                             lat = ~latitude, 
                             layerId = ~loc,
                             stroke = FALSE, 
                             color = ~pal(m),
                             radius = ~rad(GAdata())
} else{
    leafletProxy("mymap", data = GAdata()) %>%
            clearMarkers()
}
```

Seems like it could be caused by a bug in one of the functions in leaflet package, probably addCircleMarkers.

**Comment by jcheng5** [comment]
What do you mean by "m numeric column contains only 0 entries"? Do you mean m has non-zero length, but each element is 0? Or does the length of m equal 0?

Are there any errors in your web browser's javascript console when this happens?

**Comment by efh0888** [comment]
I mean m has non-zero length but each element is 0. 

Some more context might help. The user can select which column to analyze, 1 of 3, and that ends up being m. Obviously my actual code is slightly different to incorporate that:

```
  m <- eventReactive(input$action, { 
    as.name(input$metric)
  }, ignoreNULL = FALSE)
```

And then replace every `$m` with `[, eval(m(), .SD)]`. Note that GAdata() will only change when other inputs are changed, that is, when a metric is chosen I am not dropping the other 2 columns.


I mention this because there is, in fact, an error in the js console when run for the metric in question -- `Uncaught TypeError: Cannot read property 'lat' of null`. But when I run the same thing beforehand for the other two metrics it works just fine without the js error. All that is to say I can't imagine there's actually a NULL value in the latitude column.

**Comment by efh0888** [comment]
Also, when I try to set back to the original inputs, the js error then becomes:

```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by jcheng5** [comment]
Once the `Uncaught TypeError: Cannot read property 'lat' of null` error occurs, it's not surprising to me that others follow. Let's start with trying to figure out the problem with that one.

Can you try inserting a `browser()` call right before the leafletProxy call with the issue, and see if you can detect anything strange with `GData()`?

**Comment by jcheng5** [comment]
Scratch that, let's do this.

Before starting your app, call `options(shiny.trace=TRUE)`. Then run your app and repro the issue. There should be a ton of log spew in your console, please send it all to me. If there's something in there you wouldn't want public feel free to email me at joe@rstudio.com.

Thanks...

**Comment by efh0888** [comment]
Cool. Just sent you an email.
