### ISSUE TITLE
long legend title?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#168]
Is is possible to have a two-lines legend title? I tried `\n` but it does not work:

    library(RCurl)
    library(rgdal)
    library(leaflet)
    URL <- "https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson"
    # From http://data.okfn.org/data/datasets/geo-boundaries-world-110m
    countries <- readOGR(getURL(URL), "OGRGeoJSON")
    map <- leaflet(countries) %>% addTiles()
    
    
    pal <- colorNumeric(
      palette = "YlGnBu",
      domain = countries$gdp_md_est
    )
    map %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
                  color = ~pal(gdp_md_est)
      ) %>%
      addLegend("bottomright", pal = pal, values = ~gdp_md_est,
                title = "First line \nSecond line",
                labFormat = labelFormat(prefix = "$"),
                opacity = 1
      )

Thanks!

**Comment by einarhjorleifsson** [comment]
this is already a feature, you need to wrap text into html-code. e.g.:

```
map %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~pal(gdp_md_est)
  ) %>%
  addLegend("bottomright", pal = pal, values = ~gdp_md_est,
            title = "First line<br>Second line",
            labFormat = labelFormat(prefix = "$"),
            opacity = 1
  )
```
or 
```
map %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~pal(gdp_md_est)
  ) %>%
  addLegend("bottomright", pal = pal, values = ~gdp_md_est,
            title = "<p>First line</p><p>Second line</p>",
            labFormat = labelFormat(prefix = "$"),
            opacity = 1
  )
```

einar

**Comment by ignacio82** [comment]
Thanks!

**Comment by bac3917** [comment]
However, it seems this solution prevents Rmarkdown/KNITR maps from rendering.

**Comment by pssguy** [comment]
Am I missing something?

```
title = "Disposable household<br> income in  2014<br> Euros per annum",
```
works on one of my maps

**Comment by bac3917** [comment]
Did this work in RMarkdown inside code chunks?

**Comment by pssguy** [comment]
@bac3917 
Yep [here](https://www.mytinyshinys.com/2017/07/11/eurostat/)
about half way down post
