### ISSUE TITLE
Sizing of static leaflet maps in Shiny apps

### ISSUE THREAD

**Issue by wch** [rstudio/leaflet#17]
When adding a leaflet map dynamically to a Shiny app, it shows up as expected. For example:

```R
shinyApp(
  ui = bootstrapPage(div(
    leafletOutput("leaflet")
  )),
  server = function(input, output) {
    output$leaflet <- renderLeaflet({
      leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 17)
    })
  }
)
```

But if the map is added statically, it doesn't show up.

```R
shinyApp(
  ui = bootstrapPage(div(
    leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 17)
  )),
  server = function(input, output) { }
)
```

It would be useful in some cases to embed a static map into a Shiny app.

I think this is a sizing issue, similar to rstudio/dygraphs#12.

**Comment by doenertier83** [comment]
In the latest shiny version on CRAN 0.11.1 the static example still seems not to work (only grey background) while the "dynamic" example of wch is working

```{r}
shinyApp(
  ui = bootstrapPage(div(
    leaflet() %>% addTiles() %>% setView(-93.65, 42.0285, zoom = 17)
  )),
  server = function(input, output) { }
)
```

**Comment by yihui** [comment]
@doenertier83 Thanks! It should be fixed now.

**Comment by akshaybholee** [comment]
Is there an example of how we put a static map and on top of it dynamics layers?
