### ISSUE TITLE
leaflet map malfunction when not 1st tab

### ISSUE THREAD

**Issue by ndimhypervol** [rstudio/leaflet#173]
I have a sidebarPanel / mainPanel format with a tabsetPanel in the mainPanel, and I set up a conditionalPanel to make my leaflet map appear or disappear in the mainPanel depending on which tab is selected. This worked fine until I made a new tab that appears as the 1st tab, and tried to make the map disappear from this one too. When I do this, and click on tab 2, the map frame appears but is completely gray, and remains so even when I switch tabs. Any idea what is going on? Is this a bug?

**Comment by yihui** [comment]
Have you tested the latest version of the htmlwidgets package with the development version of leaflet?

```r
update.packages(ask = FALSE)
devtools::install_github('rstudio/leaflet')
```

If it still does not work, could you provide a self-contained minimal reproducible example? Thanks!

**Comment by ndimhypervol** [comment]
Updated packages and downloaded latest dev shiny, and still the same. Here's an example. If you change the first term of the logical in the conditionalPanel to any other tab but the first, the map plots. What am I doing wrong here?

runApp(list(
  
  ui = pageWithSidebar('jonny',
    sidebarPanel(
      "Tab Number:",
      uiOutput("tabNum")
    ),
    mainPanel(
      tabsetPanel(id = "tabs",
                  tabPanel("A", value=0),
                  tabPanel("1)", value=1),
                  tabPanel("2)", value=2),
                  tabPanel("3)", value=3),
                  tabPanel("4)", value=4),
                  tabPanel("5)", value=5),
                  tabPanel("6)", value=6),
                  tabPanel("7)", value=7),
                  tabPanel("8)", value=8)
                  ),
      fluidRow(
        conditionalPanel("input.tabs != 0 && input.tabs != 6 && input.tabs != 8", leafletOutput("map", height=600))
      )
    )
  ),
  
  server = function(input, output, session) {
    map <- leaflet() %>% addTiles() %>% setView(0, 0, zoom = 2)
    output$map <- renderLeaflet(map)
    output$tabNum <- renderUI(input$tabs)
  }
))

**Comment by jcheng5** [comment]
There's a JavaScript exception being raised. There's a definite bug here, I'll have to fix it in htmlwidgets.

**Comment by ndimhypervol** [comment]
Do you have an estimated timeline on the fix? Just wondering, because I need to push something out pretty soon, and it would be good to know if I should look into other solutions here. Thanks a ton, Joe!

**Comment by jcheng5** [comment]
Worked around in e051039a21dda2718c4b38aeff31cc01651a55f9

**Comment by ndimhypervol** [comment]
It is now fixed. Thanks a ton!

**Comment by GTBoon72** [comment]
Worked for me too, thanks jcheng5!

**Comment by AkbarBakhshi** [comment]
Hello. I am relatively new to R. I am facing this same issue right now. Could you please let me know what exactly I need to do? Thanks!

**Comment by AkbarBakhshi** [comment]
Hello. I am relatively new to R. I am facing this same issue right now. Could you please let me know what exactly I need to do? Thanks!
