### ISSUE TITLE
popup when hover instead of click?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#180]
With google charts you get a popup when you hover over a state, and the state changes color:

![Imgur](http://i.imgur.com/eKPqRh2.png)

Is it possible to replicate this behavior with leaflet? I'm able to get a popup when I click over a state, but cannot figure out if hovering is an option (much less changing color)

Thanks!

**Comment by bhaskarvk** [comment]
I submitted a PR for the Leaflet.label plugin which gives you that exact behavior. 
https://github.com/rstudio/leaflet/pull/181

e.g.
http://rpubs.com/bhaskarvk/leaflet-label

**Comment by ziyadsaeed** [comment]
That is one sweet popup. How to replicate that popup?

**Comment by bhaskarvk** [comment]
Closing Support for Leaflet.label has been implemented in 1.0.1
