### ISSUE TITLE
CRS bug

### ISSUE THREAD

**Issue by Tr0pe** [rstudio/leaflet#186]
Hi,

if you try to change CRS using WMSTileOptions you'll get a javascript error:
`Uncaught TypeError: this._crs.project is not a function`

Function *this._crs.project* is defined in *leaflet-src.js* in function *onAdd*.

Example without crs defined (works):
```r
leaflet() %>% setView(-93.65, 42.0285, zoom = 4) %>%
  addWMSTiles(
    "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
    layers = "nexrad-n0r-900913",
    options = WMSTileOptions(format = "image/png", transparent = TRUE))
```

Example with crs defined (does not work)
```r
leaflet() %>% setView(-93.65, 42.0285, zoom = 4) %>%
  addWMSTiles(
    "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
    layers = "nexrad-n0r-900913",
    options = WMSTileOptions(format = "image/png", transparent = TRUE, crs="EPSG:4326"))
```
Please note that map is already using epsg:4326 so first and second example should have same result.

**Comment by pingoose** [comment]
I'm also having problems with this.

Is there any work around that will allow me to use an EPSG:4326 WMS?

**Comment by embiuw** [comment]
Hi, I'm also having this problem, trying to add a WMS layer which only exists in EPSG:4326. Did either of you ever get a reply on this privately (since there's nothing here)?

**Comment by pingoose** [comment]
Hi embiuw, I've not had any reply and haven't got round to trying again to get around it myself. Let me know if you find anything!

**Comment by bhaskarvk** [comment]
The master branch now supports CRS. I will have an answer for you later today.
In the mean time I have various examples at http://rpubs.com/bhaskarvk that you can checkout.

**Comment by bhaskarvk** [comment]
Here's the working code

```r
leaflet() %>% 
  setView(-93.65, 42.0285, zoom = 4) %>%
  addWMSTiles(
    "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
    layers = "nexrad-n0r-900913",
    options = WMSTileOptions(format = "image/png", transparent = TRUE, 
                             crs=leafletCRS("L.CRS.EPSG4326")))
```

You need to build leaflet from github using `devtools::install_github('rstudio/leaflet')`. Should be on CRAN soon.

**Comment by embiuw** [comment]
Thank you very much Bhaskar! Great help!
Martin
