### ISSUE TITLE
Cannot use color palettes for addMarkers, only for addCircleMarkers

### ISSUE THREAD

**Issue by sdevine188** [rstudio/leaflet#187]
Unless I am just missing it in the documentation, the addMarkers function does not take an argument for color, like the addCircleMarkers does.  It would be helpful to be able to pass addMarkers() the same type of custom color palette arguments as addCircleMarkers().  Apologies if this functionality already exists.  Thanks - I love the package!

Regards,
Steve

**Comment by jcheng5** [comment]
It's not supported because the markers are PNG images--they're not dynamically colored. There is a PR coming that adds Awesome Markers which have a limited palette of colors: https://github.com/lvoogdt/Leaflet.awesome-markers

**Comment by jcheng5** [comment]
PR #184
