### ISSUE TITLE
addPolylines does not support lines broken in several pieces

### ISSUE THREAD

**Issue by jiho** [rstudio/leaflet#213]
This example has two lines identified separately in a `SpatialLines` object and it works
```r
x1 <- SpatialLines(
  LinesList = list(
    Lines( slinelist=list( Line(cbind(c(5,6,7),c(43,44,45))) ), ID=1),
    Lines( slinelist=list( Line(cbind(c(8,9,9),c(43,44,45))) ), ID=2)
  )
)
leaflet() %>% addTiles() %>% addPolylines(data=x1)
```

Now with two pieces of a line with the same ID, `addPolylines` only shows the first piece.
```r
x2 <- SpatialLines(
  LinesList = list(
    Lines( slinelist=list(
        Line(cbind(c(5,6,7),c(43,44,45))),
        Line(cbind(c(8,9,9),c(43,44,45)))
      ), ID=1
    )
  )
)
leaflet() %>% addTiles() %>% addPolylines(data=x2)
```

Getting pieces of lines is usual when computing them (using `rasterToContour` for example).

There is probably a way to convert from
```r
leaflet:::polygonData.SpatialLinesDataFrame(x2)
```
to
```r
leaflet:::polygonData.SpatialLinesDataFrame(x1)
```
But I am guessing there is probably something more clever to be done!

NB: given that the code is much of the same, I suspect this bug is also true for polygons which are composed of several sub-polygons.

**Comment by coolbutuseless** [comment]
+1 for this problem.   I went to the trouble of creating a minimal example, and so will leave it here for posterity

```
library(dplyr)
library(leaflet)
library(sp)

packageVersion('sp')
packageVersion('leaflet')

#----------------------------------------------------------
# Vertical and horizontal line to make
# left side and top of triangle
# i.e.    _____
#         |
#         |
#
#----------------------------------------------------------
coords1a <- matrix(c(
  0, 0,
  0, 1,
  1, 1
), nrow = 3, byrow = TRUE)


#----------------------------------------------------------
# Diagonal line to complete triangle i.e.
#
#              /
#             /
#            /
#
#----------------------------------------------------------
coords1b <- matrix(c(
  0, 0,
  1, 1
), nrow = 2, byrow = TRUE)


#----------------------------------------------------------
# Create an sp::SpatialLines object
#----------------------------------------------------------
line1a   <- Line(coords1a)
line1b   <- Line(coords1b)
S1       <- Lines(list(line1a, line1b), ID="tri")
sp_lines <- sp::SpatialLines(list(S1))


#----------------------------------------------------------
# plot looks like a triangle
#----------------------------------------------------------
plot(sp_lines)


#----------------------------------------------------------
# Leaflet only plots the first set of coordinates!  *******
# i.e. it does not draw the diagonal!               *******
#----------------------------------------------------------
sp_lines %>% leaflet() %>% addPolylines()
```

**Comment by jcheng5** [comment]
@bhaskarv Not sure what to do about this, but worth thinking about for a minute to see if there's a natural solution.

**Comment by bhaskarvk** [comment]
@jiho / @coolbutuseless 

If I do this to sp_lines

```r
if(length(sp_lines@lines) ==1 && length(sp_lines@lines[[1]]@Lines) >1) {
  id <- 0
  sp_lines.fix <- sp::SpatialLines(
    purrr::map(sp_lines@lines[[1]]@Lines, function(line){
      id <<- id + 1
      Lines(line,id)
    }))
}
```

And plot the sp_lines.fix object it works.
Essentially it's just a hack to convert a `SpatialLines(list(Lines(list(l1, l2), id='ID')))`  to 
`SpatialLines(list(Lines(l1, id="1") , Lines(l2, id="2")))`. 

Does this work for you ? @jcheng5  The fix is fairly trivial so not sure if this needs to go in Leaflet, or just document it for end user to implement on their own data.

**Comment by jcheng5** [comment]
I'm inclined to just document the workaround, or, use the multiPolyline feature in Leaflet. Maybe for vNext.

**Comment by bhaskarvk** [comment]
Defi vNext, I would much rather upgrade to Leaflet 1.0 after v1.1 and then go after this. 
I'm closing this w/ my workaround in https://github.com/rstudio/leaflet/issues/213#issuecomment-248173590
