### ISSUE TITLE
adding popup option to different object types and addLayersControl()

### ISSUE THREAD

**Issue by tyokota** [rstudio/leaflet#214]
When adding the popup option to a map that combines both addMarker() and addPolygon(), I can no longer see the layer control.

**Comment by jcheng5** [comment]
Can you please provide a small example? Thanks!

**Comment by tyokota** [comment]
@jcheng5 just learned the importance of ordering. Made a difference to put layer control first and then the marker and polygon. I think it's okay to close. TY!
