### ISSUE TITLE
Feature Request: Add text (e.g. static labels) to map

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/leaflet#218]
This request stems from another `leaflet` package user's  [question posted on Stackoverflow.](http://stackoverflow.com/questions/31745525/leaflet-with-r-add-text-labels)

I'd like to add static text labels to a leaflet map that I built and deployed with `shiny`. 

You can check it out here: [https://maynardandking.shinyapps.io/Census-Data-and-Leaflet-Map](https://maynardandking.shinyapps.io/Census-Data-and-Leaflet-Map)

And the code is available here: [https://github.com/tiernanmartin/Census-Data-and-Leaflet-Map/blob/master/app.R](https://github.com/tiernanmartin/Census-Data-and-Leaflet-Map/blob/master/app.R)

As you can see, I'm currently using the `leaflet` package's popup objects to label the counties. It sorta works, but I don't really like that there's a caption box around the text – it's eye-catching and it distracts the viewer from the main point of this choropleth: the color of the census tracts.

I also am not too happy with the way that the basemap's labels are blocked by the polygon layers. I know I could address this by adjusting the opacity of the polygon layer, but I'd prefer to leave the opacity as-is and add my own labels layer on top of the polygons.

Could you add a feature that allows text to be added to a location on the map *without using popups or markers*? I'm thinking of a function that is identical to `addPopups` except that it just displays the text and inherits styling from the map's .css file.

Thanks for the great package!

**Comment by onehundredpercenttexan** [comment]
Seconded. It would be a huge boost in efficiency to be able to do static labels in the native R code...

**Comment by bhaskarvk** [comment]
Already supported via the Leaflet.Label plugin.
Check out https://github.com/rstudio/leaflet/blob/master/inst/examples/labels.R

**Comment by tiernanmartin** [comment]
@bhaskarvk Thanks for mentioning the Leaflet.Label plugin. It's pretty close to what I'm looking for.

Would it be possible to add a 'boxOpacity' to the 'labelOptions' argument? I'd like to end up with a map with static text labels *without any boxes around them*.

**Comment by bhaskarvk** [comment]
I'm not the original author of the Leaflet.label plugin, but what ever options it supports as documented in https://github.com/Leaflet/Leaflet.label#options are supported by the `labelOptions` class.
There is a opacity option, and you should be able to customize the label using 'className'. Though you will have to figure out a way to load your custom CSS with your map.

**Comment by tiernanmartin** [comment]
Thanks for the [link](https://github.com/Leaflet/Leaflet.label#options)! 

The `opacity` argument of `labelOptions` allows users to adjust the opacity of the label text and its padding box. There doesn't seem to be a way to adjust just the opacity of the label box (or to remove it entirely, which is really what I want).  

Unless there's a way to do it with CSS?

**Comment by tiernanmartin** [comment]
Here's the CSS file for the Leaflet.label: [https://github.com/Leaflet/Leaflet.label/blob/master/dist/leaflet.label.css#L3([https://github.com/Leaflet/Leaflet.label/blob/master/dist/leaflet.label.css#L3])

@bhaskarvk Is this CSS file installed on my local machine when I install leaflet from Github?  If so, would it be possible for me to add `background-opacity: 0` to this file on my local machine?

**Comment by bhaskarvk** [comment]
@tiernanmartin The CSS is indeed bundled with the R package.
You can find it at
https://github.com/rstudio/leaflet/blob/master/inst/htmlwidgets/lib/Leaflet.label/leaflet.label.css

git clone this repo, change the CSS as per your needs and do a devtools::install(.) at the base of the repo.

**Comment by mhusseinmidd** [comment]
@tiernanmartin did you ever manage to find a way to post text directly to a map on R using leaflet?

**Comment by gisgisgis** [comment]
HI, I'm fairly new to Leaflet. How can I add the label option to the leaflet package in R?
Thanks
jaya

**Comment by bhaskarvk** [comment]
Jaya, The label plugin in already part of master. Just build the package from github using `devtools::install_github('rstudio/leaflet')` and then follow examples in https://github.com/rstudio/leaflet/blob/master/inst/examples/labels.R

**Comment by tiernanmartin** [comment]
@bhaskarvk Is it currently possible to add a layer of labels like the one used in [this map](https://georgejosephatlantic.carto.com/viz/fc27f37e-75ca-11e6-933e-0e05a8b3e3d7/public_map)?

You'll notice that their z-index is higher than the colored polygons, and that they are responsive to the zoom level.

**Comment by gisgisgis** [comment]
thanks @bhaskarvk ! so installing using devtools offers additional functionalities that are not available in regular installation thru RStudio?

**Comment by bhaskarvk** [comment]
@tiernanmartin 
I checked that site, they are not labels added to markers/polygons. they come from the 'CartoDB.PositronOnlyLabels' Tiles.
To replicate that map.
a) add CartoDB.PositronNoLabels Tiles
b) add your polygons with z-index < 1, so that the underly basemap tiles show a bit.
c) add the CartoDB.PositronOnlyLabels Tiles with zIndex > 1 so they show above the other two layers.

Hope that helps.

**Comment by bhaskarvk** [comment]
@gisgisgis yes! The new stuff should be in CRAN soon, but no date is fixed yet.

**Comment by gisgisgis** [comment]
Labels work great, except that I'm not able to add a new line while using leaflet. '\n' doesn't work, or am i missing something?

**Comment by bhaskarvk** [comment]
```
label= htmltools::HTML("Line 1<br/>Line2")
```

OR if using formula then e.g.

```
label=htmltools::HTML(sprintf('%s<br/>%s',field1, field2))
```

change your argument to sprintf as per what you want the label content to be and use the fields you want shown.

**Comment by gisgisgis** [comment]
Thanks @bhaskarvk, but an equivalent label for `popup = paste0( file$field1,"<br>","Field2", file$field2, "<br>"))` is what I'm trying. Those htmltools codes paste all record values on to each marker.

**Comment by bhaskarvk** [comment]
Give me reproducible code sample.

**Comment by gisgisgis** [comment]
Am working with shapefiles, so code not reproducible.  But it goes like this
``leaflet(map1) %>% 
  addMarkers(data =file, group = "All files",popup = paste0( file$field1,"<br>","Field2 :", file$field2, "<br>")) %>% ``
'file' is a point shapefile to be labeled (mouseover/hover) with field1 and field2 on 2 lines. The above code works fine when I use popup.

**Comment by bhaskarvk** [comment]
Change
`popup = paste0( file$field1,"<br>","Field2 :", file$field2, "<br>")`
to 
`popup = ~paste0( file$field1,"<br>","Field2 :", file$field2, "<br>")`

You need to append the `~` to make leaflet interpret it as a formula.

**Comment by gisgisgis** [comment]
welll its not popup that i'm having a problem with, poupup works fine, even without the '~'. I want to use 'label' instead.

**Comment by bhaskarvk** [comment]
In absence of reproducible sample I don't know how I can help more. 
FWIW here's a working example from the inst/examples/leaflet.R which does HTML Labels.

```r
cities <- read.csv(textConnection("
City,Lat,Long,Pop
Boston,42.3601,-71.0589,645966
Hartford,41.7627,-72.6743,125017
New York City,40.7127,-74.0059,8406000
Philadelphia,39.9500,-75.1667,1553000
Pittsburgh,40.4397,-79.9764,305841
Providence,41.8236,-71.4222,177994
"))

library(htmltools)
leaflet(cities) %>% addTiles() %>%
  addMarkers(lng = ~Long, lat = ~Lat,
             label = mapply(function(x, y) {
               HTML(sprintf("<em>%s:</em> %s", htmlEscape(x), htmlEscape(y)))},
               cities$City, cities$Pop, SIMPLIFY = F),
             labelOptions = lapply(1:nrow(cities), function(x) {
               labelOptions(direction='auto')
             }))
```

Also I just merged all my changes to master so you may want to rebuild again.

**Comment by bhaskarvk** [comment]
I'm locking this conv. please open a new BR if further issues.
