### ISSUE TITLE
`projectRasterForLeaflet` should support `method="ngb"`

### ISSUE THREAD

**Issue by adrfantini** [rstudio/leaflet#219]
The `raster` package supports nearest neighbour projection in `projectRaster`, by issuing `method="ngb"`. This should be possible in `projectRasterForLeaflet` too - it's useful for a number of different datasets.

**Comment by tim-salabim** [comment]
I totally agree that there needs to be an option for re-projecting factorial rasters using nearest neighbor. The linear interpolation of the bilinear re-projection (the default in `raster::projectRaster` produces floating point values which, in addition to being false values for factorial raster layers, also mess up the legend produced with `leaflet::colorFactor`.

In mapview we actually do the raster projection outside the `leaflet::addRasterImage` call like this (lines 178 - 187 in https://github.com/environmentalinformatics-marburg/mapview/blob/master/R/leafletControls.R):

```r
is.fact <- raster::is.factor(x)[1]
if (is.fact) {
    x <- raster::projectRaster(
      x, raster::projectExtent(x, crs = sp::CRS(wmcrs)),
      method = "ngb")
    x <- raster::as.factor(x)
  } else {
    x <- raster::projectRaster(
      x, raster::projectExtent(x, crs = sp::CRS(wmcrs)),
      method = "bilinear")
  }
```

The user still needs to make sure that their raster is of class factor (as having integer values does not necessary mean factorial, hence the explicit call to `raster::as.factor` after the re-projection), but that can be easily done with `raster::as.factor`
