### ISSUE TITLE
[Feature Request] - WebGL

### ISSUE THREAD

**Issue by masip85** [rstudio/leaflet#220]
I guess this is a huge goal:
--> webGL integration <--
rBokeh is focused into this aim.
Leaflet has some plugins with webGL integration like:
http://goo.gl/r6nqg
https://goo.gl/IN50Ag

**Comment by bhaskarvk** [comment]
Added WebGL heatmap support in https://github.com/bhaskarvk/leaflet.extras which will soon be on CRAN.
Demo http://rpubs.com/bhaskarvk/leaflet-heatmap.

For the other please raise an issue on leaflet.extras
