### ISSUE TITLE
Include heatmap on leaflet as layer

### ISSUE THREAD

**Issue by Stophface** [rstudio/leaflet#223]
I want to include this heatmap (https://github.com/Leaflet/Leaflet.heat) as a layer on my leaflet map in `R`.

Currently I am drawing the leaflet map for a shiny app in `js` and include this in my `R` files. I am aware of sending the data between `js` and my `R-Shiny` scripts like so

    newPoints<- cbind(lat,lng)
        session$sendCustomMessage(type = "myCallbackHandler", newPoints)

My `js`

        Shiny.addCustomMessageHandler("myCallbackHandler",function(newPoints) {
            var addressPoints = newPoints;
            console.log(addressPoints);
            heat = window.myHeat;
            heat.setLatLngs(addressPoints);
          });

Here I overlay the heatmap on leaflet.

        var heat = L.heatLayer(addressPoints).addTo(map);

However, I want to draw my leaflet map in `R` completeIy. But, I dont want to use `rMaps`. I am aware of this: http://rmaps.github.io/blog/posts/leaflet-heat-maps/index.html
So, how would I overlay the heatmap on a leaflet map, drawn in `R`! Is there a way to do this?

**Comment by bhaskarvk** [comment]
Added heatmap support in https://github.com/bhaskarvk/leaflet.extras which will soon be on CRAN.
Demo http://rpubs.com/bhaskarvk/leaflet-heatmap
