### ISSUE TITLE
Possible to use Stamen map tiles?

### ISSUE THREAD

**Issue by sebastianbarfort** [rstudio/leaflet#23]
Is it possible to use the [Stamen](http://maps.stamen.com/test/leaflet.html) map tiles in the `leaflet` package similar to what Ramnath did in his [Citibike visualization](http://ramnathv.github.io/bikeshare/)? 

Thanks for what is going to be a great package.

**Comment by efh0888** [comment]
Did the plugin for Google Maps get incorporated?
