### ISSUE TITLE
Feature Request: fullscreen control button

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/leaflet#231]
Would it be possible to add the [Leaflet.control.fullscreen plugin](https://github.com/brunob/leaflet.fullscreen)? It would be especially handy for leaflet maps that are embedded in presentation documents. Here's a demo of the plugin in action: <http://brunob.github.io/leaflet.fullscreen/>

Thanks!

**Comment by caycek** [comment]
+1

**Comment by amormachine** [comment]
+1

**Comment by ehyaei** [comment]
+1

**Comment by byzheng** [comment]
It is simple to add full screen plugin. Check here: https://github.com/byzheng/leafletplugins

**Comment by 18chains** [comment]
+1!

**Comment by digital-dharma** [comment]
+1!

**Comment by bhaskarvk** [comment]
Added in [leaflet.extras](https://github.com/bhaskarvk/leaflet.extras), you will need to build leaflet from Github though.
