### ISSUE TITLE
Feature Request: `changeLayer` method for `addMiniMap`

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/leaflet#234]
The `addMiniMap` function is great! 

Could you add the `changeLayer` method (mentioned [here](https://github.com/Norkart/Leaflet-MiniMap) and demonstrated [here](https://github.com/Norkart/Leaflet-MiniMap/blob/master/example/example_layerchange.html)) so that users can customize their mini map base layer?

Thanks!

**Comment by bhaskarvk** [comment]
Support now in trunk. But it has to be done from the JS side inside onRender.
e.g. 
https://github.com/rstudio/leaflet/blob/master/inst/examples/minimap.R
Demo
rpubs.com/bhaskarvk/leaflet-minimap

If there is a strong case for supporting this via an R api, we might consider it, but R support would be limited to Shiny, while the JS approach is flexible for both Shiny/non-Shiny cases.
