### ISSUE TITLE
Leaflet heatmap

### ISSUE THREAD

**Issue by zornosaur** [rstudio/leaflet#239]
Is there a way to incorporate the Leaflet.heat plugin in the Leaflet package?

I saw someone did it with rMaps, but that's not compatible with shiny: rmaps.github.io/blog/posts/leaflet-heat-maps/index.html

**Comment by jcheng5** [comment]
For reference: https://github.com/rstudio/leaflet/pull/174

**Comment by bhaskarvk** [comment]
Heatmap Support via an alternative but more performant plugin https://github.com/ursudio/webgl-heatmap-leaflet Now in trunk of https://github.com/bhaskarvk/leaflet.extras/
