### ISSUE TITLE
How to incorporate leaflet plugins? Specifically proj4leaflet

### ISSUE THREAD

**Issue by bungalow-bill** [rstudio/leaflet#24]
There are lots of <a href="http://leafletjs.com/plugins.html">leaflet plugins</a> that are quite useful.  The one I need is proj4leaflet, which allows the use of other map projections.  My specific interest is to load the GIBS data from NASA using the polar stereographic projection for the Arctic.  <a href="https://earthdata.nasa.gov/labs/gibs/examples/leaflet/arctic-epsg3413.html">Here is an example.</a>

**Comment by jmlondon** [comment]
I would also like to express support for use of base maps that are in non-Web Mercator projections. The [ESRI Arctic Ocean Basemap](http://www.arcgis.com/home/item.html?id=ee27a893c7914598983a7fb3ed5244ac) is another example

**Comment by maarten-vermeyen** [comment]
See also: #233

**Comment by bhaskarvk** [comment]
Closing as this is being tracked already in #233.
