### ISSUE TITLE
A potential bug of leafletProxy in the shiny module

### ISSUE THREAD

**Issue by byzheng** [rstudio/leaflet#243]
I am using the latest version of leaflet in github (52c792d ) and shiny module. Inside a module, I have to use the `module-name` + `-` `map-id` in `leafletProxy` function (i.e. `leafletProxy("ns_map-map")`). 

See an example here: (https://gist.github.com/byzheng/83fd3fcff9e3614e8b82).

Not sure this is desired feature or a bug in leaflet of shiny.

**Comment by jcheng5** [comment]
You can do `leafletProxy(session$ns("map"))`. That's by design.

**Comment by jcheng5** [comment]
Wait, I need to think about this more.

**Comment by jcheng5** [comment]
@wch Let's discuss this tomorrow

**Comment by jcheng5** [comment]
It feels to me like it makes sense for `leafletProxy` to call `session$ns`, but I don't love that this will break anyone who's already used leafletProxy with a module. I was wondering whether it'd make sense for Shiny's `NS` function to (by default) only namespace strings that aren't already namespaced.

**Comment by jcheng5** [comment]
With the PR I just submitted, you can call `leafletProxy("map")` and the namespace will be added automatically for you. But, if you already took my earlier advice and changed it to `leafletProxy(session$ns("map"))`, that will also work.

**Comment by cpechhacker** [comment]
I have a shiny app with two modules. One module acts as simple calculator, that sums up two values.
Another module uses the quakes data and the leaflet package to display the data.

Note that, there are three UI's:
-  ui1:  simple UI with bootstrapPage
- ui2:  UI with dashboard from package "shinydashboard"
- ui3:  UI with dashboard from package "shinydashboard" (the only difference is in the order of the menuItems in sidebarMenu)

Calling shinyApp(ui1, server) works as well as shinyApp(ui2, server),
However, when calling  shinyApp(ui3, server) the quakes data are not displayed accordingly. Why?

See example: https://github.com/rstudio/leaflet/files/723736/shiny_bug.txt

[shiny_bug.txt](https://github.com/rstudio/leaflet/files/723748/shiny_bug.txt)
