### ISSUE TITLE
how use plugin-draw.R

### ISSUE THREAD

**Issue by ziina** [rstudio/leaflet#244]
I've tried to run the plugin-draw.R example from the blog but but I did not understand how to operate it, thank you to repley please..

**Comment by ssoulier** [comment]
see my answer in #227

**Comment by bhaskarvk** [comment]
Closing and tracking under bhaskarvk/leaflet.extras#2

**Comment by bhaskarvk** [comment]
I have implemented this in https://github.com/bhaskarvk/leaflet.extras. Demo at http://rpubs.com/bhaskarvk/leaflet-draw
