### ISSUE TITLE
Shape click  event in draw plugin

### ISSUE THREAD

**Issue by byzheng** [rstudio/leaflet#250]
It seems the draw.plugin cannot catch the click event in a leaflet map. 

I  used my own fork leaflet  package (https://github.com/byzheng/leaflet) which merge draw branch into latest master branch, and add a few new features.

This is a minimum example to reproduce my problem. After draw a few shapes (e.g. polygon), there are not output in the `summary` output through clicking shapes. 

```
 library(leaflet)
library(shiny)

ui <- fluidPage(
    leafletOutput('map'),
    verbatimTextOutput('summary')
)

server <- function(input, output, session) {
    output$summary <- renderPrint({
        event <- input$map_shape_click
        print(event)
    })

    output$map <- renderLeaflet({
        leaflet() %>%
            addTiles() %>% 
            setView(10, 10, 4) %>% 
            addDrawToolbar(
                layerID = 'draw')

    })
}
shinyApp(ui, server)
```

**Comment by bhaskarvk** [comment]
draw now in leaflet.extras
