### ISSUE TITLE
addMagnifyingGlass doesn't support custom layers

### ISSUE THREAD

**Issue by jcheng5** [rstudio/leaflet#252]
It looks to me like only tile layers show up in the magnifying glass?

```
library(leaflet)

leaflet(quakes) %>%
  addTiles() %>%
  addMarkers() %>%
  addMagnifyingGlass()
```

**Comment by bhaskarvk** [comment]
Yes unfortunately for now that's the case. Once I have some free time (early June), I'm going to revisit this and the minimap plugins to see how the markers, polygons can show up in the magnifier and the minimap.

**Comment by jcheng5** [comment]
If this can't be fixed easily, let's just drop support for addMagnifyingGlass--it feels too limited as-is.

**Comment by bhaskarvk** [comment]
The only way to do this is add the markers/lines/ploygons to both the base tile layer as well as the tile layer used in the magnifying glass. This could end up being a very slow operation if there are lots of markers/polygons.
Alternate is to figure out the bounding box|circle of the magnified region and add only those markers/polygons/lines to the tile layer of the magnifying glass which is going to be a complex and possibly impossible.
So for now I'll just take it out.
