### ISSUE TITLE
[feature request] Add/link legend to a group

### ISSUE THREAD

**Issue by bocinsky** [rstudio/leaflet#253]
Hi there. Fantastic job with the leaflet package!
One thing I'm trying to do is make legends appear and disappear with their corresponding layers. As far as I understand it, adding the legend to the same group as the layer would accomplish this—perhaps a "group" option in addLegend() or a generic "add_layer_to_group()" function would work.
Thanks!

**Comment by jasdumas** [comment]
I agree that this would be a useful feature for many layers

**Comment by ScottSchwalm** [comment]
This would be very useful.  Please consider adding this in the near future.

**Comment by rloudon** [comment]
This would be very helpful for polygon baselayers.

**Comment by jcheng5** [comment]
This is now supported on master.

**Comment by bhaskarvk** [comment]
Code sample https://github.com/rstudio/leaflet/blob/master/inst/examples/groupOptions.R and demo http://rpubs.com/bhaskarvk/group-options
