### ISSUE TITLE
LineString GeoJSON not rendering corerctly - potential bug

### ISSUE THREAD

**Issue by sidharthanr** [rstudio/leaflet#259]
A reproducible example below, sessionInfo() after that. What is happening is that a light shade is created between the first point in linestring and last point in linestring within the current view area. Problem is there with all LineStrings I tested. If this is not clear/reproducible I can attach a screenshot of the problem.

Same geojson object looks good in Github
https://github.com/sidharthanr/MiscItems/blob/master/simpleLineString.geojson

**Reproducible example**

library(leaflet)
sampleLineString = list(
  type = "Feature",
  geometry = list(
    type = "LineString",
    coordinates = list(
      c( -101.744384765625, 39.32155002466662 ),
      c( -101.5521240234375, 39.330048552942415 ),
      c( -101.40380859375, 39.330048552942415 ),
      c( -101.33239746093749, 39.364032338047984 ),
      c( -101.041259765625, 39.36827914916011 ),
      c( -100.975341796875, 39.30454987014581 ),
      c( -100.9149169921875, 39.24501680713314 ),
      c( -100.843505859375, 39.16414104768742 ),
      c( -100.8050537109375, 39.104488809440475 ),
      c( -100.491943359375, 39.10022600175347 ),
      c( -100.43701171875, 39.095962936305476 ),
      c( -100.338134765625, 39.095962936305476 ),
      c( -100.1953125, 39.027718840211605 ),
      c( -100.008544921875, 39.01064750994083 ),
      c( -99.86572265625, 39.00211029922512 ),
      c( -99.6844482421875, 38.97222194853654 ),
      c( -99.51416015625, 38.929502416386605 ),
      c( -99.38232421875, 38.92095542046727 ),
      c( -99.3218994140625, 38.89530825492018 ),
      c( -99.1131591796875, 38.86965182408357 ),
      c( -99.0802001953125, 38.85682013474361 ),
      c( -98.82202148437499, 38.85682013474361 ),
      c( -98.44848632812499, 38.84826438869913 ),
      c( -98.20678710937499, 38.84826438869913 ),
      c( -98.02001953125, 38.8782049970615 ),
      c( -97.635498046875, 38.87392853923629 )
    )
  ),
  properties = list(
    name = "Sample"
  )
)
leaflet() %>% addTiles()  %>%  setView(lng=-101.41,lat=39.33,zoom=9) %>% addGeoJSON(sampleLineString) 

**Session Info**
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet_1.0.1

loaded via a namespace (and not attached):
[1] htmlwidgets_0.6 magrittr_1.5    htmltools_0.3.5 tools_3.2.3     yaml_2.1.13    
[6] Rcpp_0.12.3     jsonlite_0.9.19 digest_0.6.9

**Comment by sidharthanr** [comment]
I looked at this a little more and this is happening because by default fillOpacity is 0.2 for addGeoJSON function. For LineString GeoJSON object fillOpacity > 0 doesn't make much sense but expected behavior can be achieved by using fillOpacity =0.

**Comment by bhaskarvk** [comment]
Setting fillOpacity=0 is an acceptable workaround in this case. The defaults were chosen so as to have sensible defaults for lines and shapes.

**Comment by sidharthanr** [comment]
Thank you. fillOpacity =0 is a good work around visually but when you hover the mouse around you will notice that the geojson objects gets selected (mouse pointer turns to hand) even when you are not hovering over the line string. So for some applications this work around may not be ideal.
