### ISSUE TITLE
Box selection

### ISSUE THREAD

**Issue by tjmckinley** [rstudio/leaflet#265]
Firstly, fantastic job with this package, thanks!

I am writing a Shiny app and would like to be able to brush a leaflet map and select all the markers within the selection box. Something similar has been raised on stackoverflow:

http://stackoverflow.com/questions/17611596/multiple-marker-selection-within-a-box-in-leaflet

However, try as I might I can't figure out how to port these ideas to R. Any ideas would be greatly appreciated. Many thanks.

**Comment by bhaskarvk** [comment]
I'm looking in to this now.

An easier way to do this is via a plugin.

These are the options.

- [LocationFilter](https://github.com/kajic/leaflet-locationfilter/)
    - Draggable/resizable selection rectangle with free aspect ratio.
- [AreaSelect](https://github.com/heyman/leaflet-areaselect/)
    - Non-draggable centered selection rectangle with lock-able aspect ratio.
- [FreeDraw](https://github.com/Wildhoney/Leaflet.FreeDraw)
    - Very flexible and feature rich.
- [Leaflet.Draw](https://github.com/Leaflet/Leaflet.draw)
    - Already implemented in leaflet.extras

I don't think Leaflet.Draw is a right tool for this job, it's more for drawing/editing/styling geometries and not really selecting points. It can do selections too but would be an overkill for just that purpose.

FreeDraw too is mostly for drawing, but it is very powerful and feature rich and can be easily adapted for selection purposes.
AreaSelect and LocationFilter are complimentary and I see use cases for both. 

My vote is for combination of AreaSelect + LocationFilter with a matching Toolbar (can be done easily using `addEasyButtonBar. This will allow users to select rectangular coordinates on the map and bring them back into shiny.

FreeDraw will be ultimate flexibility but will probably require more coding time.

Thoughts/comments @timelyportfolio / @tim-salabim

**Comment by bhaskarvk** [comment]
Fixed in #335

**Comment by tjmckinley** [comment]
Hi @bhaskarvk , thanks very much for looking into this. Much appreciated! As soon as I get some time I'll have a play with these ideas. Thanks very much. TJ

**Comment by bhaskarvk** [comment]
@tjmckinley, @jcheng5 is reworking this in crosstalk3 branch.

**Comment by bhaskarvk** [comment]
crosstalk is now in master
