### ISSUE TITLE
addProviderTiles in leaflet 1.0.1.9004

### ISSUE THREAD

**Issue by natrot** [rstudio/leaflet#268]
Hi, im not sure if it is just a syntax change, but my script doesnt add provider tiles anymore.

It worked with the leaflet package 1.0.1.9002, I updated the package to 1.0.1.9004 and it stopped working.

The below example from the website also fails to load the provider tile:

m <- leaflet() %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12)
#This loads the base map
m %>% addTiles() 
#But this doesnt load the provider map
m %>% addProviderTiles("Stamen.Toner")

**Comment by jcheng5** [comment]
Yup, I broke it :( Thanks for the report, I'll get that fixed immediately.

**Comment by jcheng5** [comment]
Fixed in e2751ff

**Comment by natrot** [comment]
wow, 11 mins to fix it.

Thanks Joe and co.

Downloaded the new package and works perfect now.

Thanks!!!


On 27 May 2016, at 18:31, Joe Cheng <notifications@github.com> wrote:

Fixed in e2751ff <https://github.com/rstudio/leaflet/commit/e2751ffc763911840fb93680289ab213981f0530>
