### ISSUE TITLE
CRAN bump

### ISSUE THREAD

**Issue by nikolai-b** [rstudio/leaflet#270]
Hi,

I'd really like to use some of the newer features without installing `devtools` on our server.  Thanks for all the work you've done, would you mind bumping the version on CRAN?

**Comment by jcheng5** [comment]
This is definitely on my mind, I want to do one more round of cleanup first but the goal is to do that soon--ideally before useR.

**Comment by bhaskarvk** [comment]
CRAN ver 1.1 is live.
