### ISSUE TITLE
Zero-row data causes Leaflet to get into bad state

### ISSUE THREAD

**Issue by jcheng5** [rstudio/leaflet#272]
```r
leaflet(quakes[FALSE,]) %>% addMarkers()
```

See also more complete scenario in https://github.com/rstudio/leaflet/issues/271

**Comment by digital-dharma** [comment]
Adding a bit of detail, this issue can interestingly manifest in different ways.  

- When Leaflet enters a corrupt state within RStudio, previously plotted points no longer disappear.  This holds true even when the app is rendered in a browser.  
- When that same app is pushed to ShinyApps.io, once in the corrupted state, all points fail to appear.

A potential solution seems to be leveraging the `req` function to ensure an empty data frame is never passed to Leaflet.

**Comment by bhaskarvk** [comment]
Closing as duplicate and tracking under #304
