### ISSUE TITLE
zoom control layer order

### ISSUE THREAD

**Issue by kissmygritts** [rstudio/leaflet#273]
The zoom control in a shiny app (dashboard) is on top of select input options. I'm not certain where this issue belongs, however it may be similar to #179. A solution for my issue would be to be able to hide the zoomControl. 

The input is in a fluidrow, I've tried wrapping in a box and column, but still the same behavior.

Picture for reference.
![zoom issue](https://cloud.githubusercontent.com/assets/8335176/16158409/ef8f113c-3471-11e6-8d3a-6d8a1474b943.jpg)

**Comment by bhaskarvk** [comment]
It is now possible to disable zoom control. The fix has not yet made it to cran but if you build using `devtools::install('rstudio/leaflet')` you can pass `option=leafletOptions(zoomControl=FALSE)` to your `leaflet()` call.
