### ISSUE TITLE
SuperZip example does not work with github leaflet version

### ISSUE THREAD

**Issue by mubashirqasim** [rstudio/leaflet#275]
I am using github version of leaflet package especially for **makeAwesomeIcon**  and **addAwesomeMarkers** functions.  

I just noticed that SuperZip example does not run under github version.
and CRAN verions does not have above functions. I wonder if there is any possibility of having **makeAwesomeIcon**  and **addAwesomeMarkers** functions in CRAN version.

Many thanks...

**Comment by jcheng5** [comment]
Which copy of the SuperZip example are you looking at? There are a couple of versions floating around unfortunately.

I've been dying to get a new leaflet version onto CRAN, sorry. Hopefully once this upcoming version of Shiny is shipped I can get someone to do that.

**Comment by jcheng5** [comment]
I believe this version should work:
https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example

**Comment by mubashirqasim** [comment]
Thanks for prompt response.  New version runs good. Hey just one more quick thing, I just replaced **addCircle** with **addCircleMarkers** in the example to add some functionality, but popup on click stopped working.

leafletProxy("map", data = zipdata) %>%
      clearShapes() %>%
      addCircleMarkers(~longitude, ~latitude, radius=5, layerId=~zipcode,
                 stroke=FALSE, fillOpacity=0.4, fillColor=pal(colorData)) %>%
      addLegend("bottomleft", pal=pal, values=colorData, title=colorBy,
                layerId="colorLegend")

**Comment by jcheng5** [comment]
Am I missing something or did you forget to provide a popup argument...?

**Comment by mubashirqasim** [comment]
Popups are shown with the following:

# Show a popup at the given location
  showZipcodePopup <- function(zipcode, lat, lng) {
    selectedZip <- allzips[allzips$zipcode == zipcode,]
    content <- as.character(tagList(
      tags$h4("Score:", as.integer(selectedZip$centile)),
      tags$strong(HTML(sprintf("%s, %s %s",
        selectedZip$city.x, selectedZip$state.x, selectedZip$zipcode
      ))), tags$br(),
      sprintf("Median household income: %s", dollar(selectedZip$income * 1000)), tags$br(),
      sprintf("Percent of adults with BA: %s%%", as.integer(selectedZip$college)), tags$br(),
      sprintf("Adult population: %s", selectedZip$adultpop)
    ))
    leafletProxy("map") %>% addPopups(lng, lat, content, layerId = zipcode)
  }

  # When map is clicked, show a popup with city info
  observe({
    leafletProxy("map") %>% clearPopups()
    event <- input$map_shape_click
    if (is.null(event))
      return()

    isolate({
      showZipcodePopup(event$id, event$lat, event$lng)
    })
  })
