### ISSUE TITLE
Empty sp objects cause error

### ISSUE THREAD

**Issue by coolbutuseless** [rstudio/leaflet#278]
Problem: An 'sp' object with no data will cause leaflet to throw an error.
Expected behaviour: if there's no data, and using a leaflet proxy (in shiny) just leave the map state unchanged. Otherwise show a blank canvas or something rather than an error.
Example: see code below

Possibly related: https://github.com/rstudio/leaflet/issues/272 https://github.com/rstudio/leaflet/issues/271

```r
library(dplyr)
library(leaflet)
library(sp)

coords      <- matrix(c(1,2,3,4), nrow=2)
line        <- Line(coords)
sp_lines    <- SpatialLines(list(Lines(list(line), ID=1)))
sp_lines_df <- sp::SpatialLinesDataFrame(sp_lines, data=data.frame(x=1))

# This works ok
sp_lines_df %>% leaflet() %>% addPolylines()

# Subset the data to get SpatialLinesDataFrame without data
sub_df <- sp_lines_df[sp_lines_df$x > 1,]

# The following fails with:
# - Error in bb[1, ] : incorrect number of dimensions
sub_df %>% leaflet() %>% addPolylines()
```

**Comment by bhaskarvk** [comment]
Closing as duplicate and tracking under #304
