### ISSUE TITLE
Adapt coordinate system to a map with custom tiles

### ISSUE THREAD

**Issue by MichelV2** [rstudio/leaflet#284]
Hello everyone,

I am working on a shiny app with a map that is made of custom tiles similarly to the example given here:

https://gherardo.shinyapps.io/exampleLocalTiles/

My question is, how can we add markers on this map using either pixel coordinates  or some sort of normalized coordinates in the map space? I believe there is an option in javascript for this (crs = "L.CRS.Simple") but I don't know how I could integrate that in R.

Thank you,

Michel

**Comment by MichelV2** [comment]
Just added the option in leaflet.js : 
`  HTMLWidgets.widget({
    name: "leaflet",
    type: "output",
    initialize: function(el, width, height) {
      // hard-coding center/zoom here for a non-empty initial view, since there
      // is no way for htmlwidgets to pass initial params to initialize()
      var map = L.map(el, {
        center: [51.505, -0.09],
        **crs: L.CRS.Simple,**
        zoom: 13
      });`

Seems to work for me.

**Comment by jamesdalg** [comment]
This seems amazing! can you add a few lines to show precisely what you did on some example data? I've been wanting to do something like this for a long time; it would really help my application.
