### ISSUE TITLE
Click event handlers are added but not cleared

### ISSUE THREAD

**Issue by wch** [rstudio/leaflet#29]
A `click` event handler is added here each time the map receives an update, but it isn't cleared. This results in the data being sent to the server more and more times.

https://github.com/rstudio/leaflet/blob/8353463bc232795d97d6dcc116f2bf82eccdf841/inst/htmlwidgets/leaflet.js#L529-L535

The same may be true for the `moveend` event a few lines below.

Edit: I think that `shiny.onInputChange` may collapse multiple calls into a single data item sent to the server. But `shiny.onInputChange` is still called an increasing number of times as more clicks occur.

**Comment by jcheng5** [comment]
Whoops.

The nonce should prevent the multiple calls from being collapsed, it'd be weird if you're not seeing multiple messages being sent to the server.

Do you mind taking care of these while you're in there adding "if first time rendering then..." logic?

**Comment by wch** [comment]
The `onInputChange` still collapses them into a single thing to send to the server. I think it's because they all happen before the next `setTimeout(0)`.

https://github.com/rstudio/shiny/blob/f066a4bdf495f1ddb6a111ee0fe33a967c7c682c/inst/www/shared/shiny.js#L356-L387
