### ISSUE TITLE
Support for DivIcon

### ISSUE THREAD

**Issue by cuche27** [rstudio/leaflet#291]
It looks that one can define custom icons but not divIcons ( http://leafletjs.com/reference.html#divicon )

**Comment by bhaskarvk** [comment]
I've added textOnly param to support textOnly markers.
https://github.com/bhaskarvk/leaflet/commit/8b5dd82d4b7519fce798e17d507b34a8a6561107

That should give you something similar. You still get a 1px transparent png w/ it, but it allows you to style the label as you want.

For demo see http://rpubs.com/bhaskarvk/leaflet-labels.

This should land in trunk and subsequently in CRAN soon. I might still add support of DivIcon for completeness.

**Comment by bhaskarvk** [comment]
Support for labelOnly markers has been merged in trunk. Closing issue.
