### ISSUE TITLE
Adding a label tiles above paths

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/leaflet#296]
Apologies for the repeat (or is this a continuation) of a [previously opened issue](https://github.com/rstudio/leaflet/issues/218). 

I'd like to add a layer of tiles that renders on top of my basemap and path layers. This type of map is referred to [here](https://carto.com/blog/let-your-labels-shine/) as a "sandwich" map, and is illustrated in this [leaflet map](https://georgejosephatlantic.carto.com/viz/fc27f37e-75ca-11e6-933e-0e05a8b3e3d7/public_map).

@bhaskarvk [suggested](https://github.com/rstudio/leaflet/issues/218#issuecomment-247685540) that this can be done by doing the following steps:

> a) add CartoDB.PositronNoLabels Tiles
>b) add your polygons with z-index < 1, so that the underly basemap tiles show a bit.
>c) add the CartoDB.PositronOnlyLabels Tiles with zIndex > 1 so they show above the other two layers.

However, I haven't been able to recreate this map "sandwich" despite my best efforts. Is there a way to set the zIndex of a path layer (e.g. polygons, circles, etc.)? If so, why isn't it a parameter in the `pathOptions` function?  Is there another way of achieving the desired effect of have unobstructed label tiles?

Here's what I've tried:

```
library(leaflet)

cities <- read.csv(textConnection("
City,Lat,Long,Pop
  Boston,42.3601,-71.0589,645966
  Hartford,41.7627,-72.6743,125017
  New York City,40.7127,-74.0059,8406000
  Philadelphia,39.9500,-75.1667,1553000
  Pittsburgh,40.4397,-79.9764,305841
  Providence,41.8236,-71.4222,177994
  "))

leaflet() %>%
        addTiles('http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png',options = tileOptions(zIndex = -1)) %>%
        addTiles('http://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png',options = tileOptions(zIndex = 1000)) %>%
        addCircles(data = cities,lng = ~Long, lat = ~Lat, weight = 1,
                   radius = ~sqrt(Pop) * 30, fillOpacity = .85)
```
Many thanks,

Tiernan

**Comment by bhaskarvk** [comment]
OK I looked at Leafet code a bit and it's possible but not straight forward.
Finally got it working 

```r

leaflet() %>%
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
  addProviderTiles(providers$CartoDB.PositronOnlyLabels,
                   layerId = 'labels_layer' ) %>%
  addCircles(data = cities,lng = ~Long, lat = ~Lat, weight = 1,
             radius = ~sqrt(Pop) * 30, fillOpacity = 0.8) %>%
  htmlwidgets::onRender("function(el, t){
    var myMap = this;
    var shadowPane = myMap.getPanes().shadowPane;
    shadowPane.appendChild(
      myMap.layerManager._byLayerId['tile\\nlabels_layer'].getContainer());
  }")
```

The addProviderTiles(providers$...) is now available in master, so you can use that after doing a fresh build. Else add tiles the way you have using URL template.

See in action at http://rpubs.com/bhaskarvk/issue-296

**Comment by tiernanmartin** [comment]
It seems that this solution renders popups inaccessible to the user. Any thoughts on a work-around there?

**Comment by bhaskarvk** [comment]
add
`shadowPane.style.pointerEvents = 'none';`

So full code.


```r
library(leaflet)

cities <- read.csv(textConnection("
                                  City,Lat,Long,Pop
                                  Boston,42.3601,-71.0589,645966
                                  Hartford,41.7627,-72.6743,125017
                                  New York City,40.7127,-74.0059,8406000
                                  Philadelphia,39.9500,-75.1667,1553000
                                  Pittsburgh,40.4397,-79.9764,305841
                                  Providence,41.8236,-71.4222,177994"))

leaflet() %>%
  addProviderTiles(providers$CartoDB.PositronNoLabels) %>%
  addProviderTiles(providers$CartoDB.PositronOnlyLabels,
                   layerId = 'labels_layer' ) %>%
  addCircles(data = cities,lng = ~Long, lat = ~Lat, weight = 1,
             radius = ~sqrt(Pop) * 30, fillOpacity = 0.8,
             popup = ~City) %>%
  htmlwidgets::onRender("function(el, t){
                        var myMap = this;
                        var shadowPane = myMap.getPanes().shadowPane;
                        shadowPane.style.pointerEvents = 'none';
                        shadowPane.appendChild(
                        myMap.layerManager._byLayerId['tile\\nlabels_layer'].getContainer());
                        }")
```
