### ISSUE TITLE
colorFactor is broken with qualitative color brewer palette

### ISSUE THREAD

**Issue by kent37** [rstudio/leaflet#300]
For example try `previewColors(colorFactor("Set1", levels = 1:4), 1:4)`. Of the four colors shown, only one is actually part of `Set1`. It's unfortunate that the palette builder for quantitative values can't use a quantitative palette.

This is basically a duplicate of https://github.com/hadley/scales/issues/62 because the `colorFactor`code is derived from `scales::col_factor` and they share the same issue.

**Comment by jcheng5** [comment]
@bhaskarvk This actually would be a great one to fix for v1.1, and we can send the fix upstream to scales too.
