### ISSUE TITLE
Unable to find "doColorRamp" function

### ISSUE THREAD

**Issue by BardoBravo** [rstudio/leaflet#305]
Hello,
When I try to execute function addPolygons() from package leaflet, I receive the following error:
Error in f(x) : could not find function "doColorRamp"

Such issue only happens if I use the color parameter with a collorPalette:

> leaflet::leaflet(nhmap)  %>%  leaflet::addProviderTiles("CartoDB.Positron")  %>%  leaflet::addPolygons(stroke=FALSE, smoothFactor = 0.2, fillOpacity = .8, popup = nhpopup, fillColor = ~clintonPalette(nhmap@data$ClintonPct))

I have already used require() and library() functions, but even so the issue persists.

Any help would be great.
Regards,
Cláudio

**Comment by bhaskarvk** [comment]
Could you share the code for the `clintonPalette` function, and version of your R and leaflet ?

**Comment by BardoBravo** [comment]
Hello,

clintonPalette code
> clintonPalette <- colorNumeric(palette = "Blues", domain=nhmap$ClintonPct)

Regarding R and leaflet versions, I just installed them yesterday (windows), so they should be the latest available version.

Hugs

**Comment by bhaskarvk** [comment]
Thanks , is the nhmap data available publicly or can you share it ?

Also from your R console can you run the following two commands and send me the output ?

```r
sessionInfo()
packageVersion('leaflet')
```

**Comment by bhaskarvk** [comment]
I won't be able to reproduce it until have your data. In the mean time, here's a full working example with a diff. data set.
http://rpubs.com/bhaskarvk/polygon-colors

I'm closing this as non repoducible, but feel free to reopen if my code in the Rpubs link above doesn't work too, or if you can give me your data, and the info I ask for in the comment above this.

**Comment by BardoBravo** [comment]
Hi,
I was not able to answer earlier to your questions.
nhmap is defined via the Hew Hampshire map data from U.S. government - in fact, I am just following the steps described in the webpage [http://www.computerworld.com/article/3038270/data-analytics/create-maps-in-r-in-10-fairly-easy-steps.html?nsdr=true&page=1]

When running the mentioned commands, I get the following responses:
> R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

>locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
 [1] quantmod_0.4-6  TTR_0.23-1      xts_0.9-7       zoo_1.7-13      colorRamps_2.3 
 [6] magrittr_1.5    scales_0.4.0    Formula_1.2-1   survival_2.39-4 lattice_0.20-33
[11] psych_1.6.9     sp_1.2-3       

>loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7      splines_3.3.1    mnormt_1.5-4     munsell_0.4.3   
 [5] colorspace_1.2-6 plyr_1.8.4       tools_3.3.1      parallel_3.3.1  
 [9] grid_3.3.1       gtable_0.2.0     htmltools_0.3.5  yaml_2.1.13     
[13] leaflet_1.0.1    digest_0.6.10    Matrix_1.2-6     htmlwidgets_0.7 
[17] jsonlite_1.1     foreign_0.8-66

and

>[1] '1.0.1'

**Comment by BardoBravo** [comment]
Oh, and I cannot re-open the issue.

**Comment by bhaskarvk** [comment]
I'll try and reproduce tomorrow. I have reopened the issue. in the mean time could you try my code and see if it works.

**Comment by BardoBravo** [comment]
OK, thanks

**Comment by BardoBravo** [comment]
Hi,
I went through your example and also re-did all paths from the original step-by-step I sent you before and it worked.
I think it was a error with the way I was calling the library command.
Thanks for your support.
Cláudio Ramos
