### ISSUE TITLE
Add a legend for the WMS tile 

### ISSUE THREAD

**Issue by para2x** [rstudio/leaflet#312]
Hi there, 
I was wondering if there is there anyway we can add the legend for the WMSTiles ?
Thanks

**Comment by bhaskarvk** [comment]
Is there an example I can look at? doesn't the existing addLegend work for you?

**Comment by para2x** [comment]
No, there is no explicit variable you can pass to the legend function for values and etc.
This an example of plug-in that creates a legend for WMS :
https://github.com/kartoza/leaflet-wms-legend

**Comment by bhaskarvk** [comment]
Ah OK a plugin, I think I can integrate it in my [leaflet.extras](https://www.github.com/bhaskarvk/leaflet.extras) package.

**Comment by bhaskarvk** [comment]
This issue was moved to bhaskarvk/leaflet.extras#5
