### ISSUE TITLE
How to programmatic remove objects created by drawing tool ?

### ISSUE THREAD

**Issue by para2x** [rstudio/leaflet#318]
Hello all, 
Is there any way to clear a drawn feature from the map ? I tried "clearshap" and etc and didn't work. But when I used cleargroup("drawnItems") it removes all the shapes but it doesn't show anything if you try to draw a new shape after that. I'm trying to create a kind of a reset button. The spatialdataframe of "drawnItems_features" is also read-only and there seem to be no way to manipulate that. Can anybody think of a way ?

**Comment by bhaskarvk** [comment]
Could you provide a minimal reproducible sample code ?

**Comment by para2x** [comment]
here is a simple example based on coded in Issue#227:
`#devtools::install_github("ssoulier/leaflet")


library(shiny)
library(miniUI)
library(leaflet)
library(rgdal)

myGadgetFunc <- function() {

  ui <- miniPage(
    gadgetTitleBar("leaflet Draw"),
    miniContentPanel(
      leafletOutput("mymap")
    ),textOutput("consol"),actionButton("clearbtn","clear")
  )
  
  server <- function(input, output, session) {

    myMap <- reactive({
      return(leaflet() %>%
               addTiles() %>%
               addDrawToolbar(edit=F)%>% addLayersControl(
                 overlayGroups = c("drawnItems"),
                 options = layersControlOptions(collapsed = FALSE)
               ))
    })
    


    # Define reactive expressions, outputs, etc.
    output$mymap <- renderLeaflet({
      myMap()
   
    })
    

    observeEvent(input$clearbtn, {
      leafletProxy("mymap")%>%clearShapes()%>%clearGeoJSON()%>%
      clearTopoJSON()

    })

    observeEvent(input$mymap_drawnItems_created, {

      output$consol<-renderPrint({
        obj<-input$mymap_drawnItems_features
        print(obj)

      })
    })

    # When the Done button is clicked, return a value
    observeEvent(input$done, {
      stopApp()
    })
  }
  runGadget(ui, server)
}
myGadgetFunc()`

**Comment by para2x** [comment]
No luck in here ?

**Comment by bhaskarvk** [comment]
Draw support is now in https://github.com/bhaskarvk/leaflet.extras/ and that supports clearing of drawn items.
