### ISSUE TITLE
geojson popup max width

### ISSUE THREAD

**Issue by jrounds** [rstudio/leaflet#325]
Hi,

What is a good way to set the max width of a popup placed into a geojson features.properties.popup field and then added via addGeoJson()?

**Comment by ScientificProgrammer** [comment]
I'm not certain, but I believe that the popup properties are controlled by the Leaflet container, so whether you created the map layer with AddGeoJSON or not, the same code should work. The Leaflet pop-up has a ·MaxWidth· property. Have you tried it? Here's some untested sample code.

···
content <- paste(sep = "<br/>", "<b><a href='http://www.samurainoodle.com'>Samurai Noodle</a></b>", "606 5th Ave. S", "Seattle, WA 98138" )

leaflet() %>
 addTiles() %>%
 addPopups( -122.327298,
                      47.597131,
                      content,
                      options = popupOptions(MaxWidth = 200 ))

···

**Comment by jrounds** [comment]
I did not provide a good working bit of code to illustrate the issue (and the search for a solution.  I don't think that does it because it puts the popup at a spot, and I am thinking of shape geojson.

Here is a working bit of code that makes the popup, and I am searching how to tell leaflet to use a maxwidth on the popups that get inputed through the geojson.  It may just be knowing how leaflet works in javascript.

```
library(jsonlite)

# From http://data.okfn.org/data/datasets/geo-boundaries-world-110m
geojson <- readLines(file("https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson"), warn = FALSE) %>%
  paste(collapse = "\n") %>%
  fromJSON(simplifyVector = FALSE)

# Default styles for all features
geojson$style = list(
  weight = 1,
  color = "#555555",
  opacity = 1,
  fillOpacity = 0.8
)

# Gather GDP estimate from all countries
gdp_md_est <- sapply(geojson$features, function(feat) {
  feat$properties$gdp_md_est
})
# Gather population estimate from all countries
pop_est <- sapply(geojson$features, function(feat) {
  max(1, feat$properties$pop_est)
})

# Color by per-capita GDP using quantiles
pal <- colorQuantile("Greens", gdp_md_est / pop_est)
# Add a properties$style list to each feature
geojson$features <- lapply(geojson$features, function(feat) {
  feat$properties$style <- list(
    fillColor = pal(
      feat$properties$gdp_md_est / max(1, feat$properties$pop_est)
    )
  )
  feat$properties$popup = paste(rep(letters,3), sep = "", collapse = "")
  feat
})

#---------------------------------------------------------------------------------
# Adding popups
#---------------------------------------------------------------------------------

# Add the now-styled GeoJSON object to the map
leaflet() %>% addGeoJSON(geojson)
```

**Comment by jrounds** [comment]
I am not going to pretend I understand everything in this file, but it seems to me that this could be simple if the list in feature.properties are automatically converted from R to javascript.

For example, at this line:
https://github.com/rstudio/leaflet/blob/master/inst/htmlwidgets/leaflet.js#L1461

If it checked for popupOptions in the same way that it checks for popups and passes it to the bindPopup function appropriately than every single popup control would be exposed in leaflet.

http://leafletjs.com/reference.html#popup-options

And in terms of the code above where I put
feat$properties$popup
I could also put
feature$properties$popupOptions = list(...)

**Comment by jrounds** [comment]
Added a pull request to illustrate the solution, but I only tested it with the following snippet, which seems to work.  Unfortunately I have a sponsor that has to have code from CRAN, so there is nothing I can do with developing and testing this solution on my own.


```
library(jsonlite)
library(leaflet)
# From http://data.okfn.org/data/datasets/geo-boundaries-world-110m
geojson <- readLines(file("https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson"), warn = FALSE) %>%
  paste(collapse = "\n") %>%
  fromJSON(simplifyVector = FALSE)

# Default styles for all features
geojson$style = list(
  weight = 1,
  color = "#555555",
  opacity = 1,
  fillOpacity = 0.8
)

# Gather GDP estimate from all countries
gdp_md_est <- sapply(geojson$features, function(feat) {
  feat$properties$gdp_md_est
})
# Gather population estimate from all countries
pop_est <- sapply(geojson$features, function(feat) {
  max(1, feat$properties$pop_est)
})

# Color by per-capita GDP using quantiles
pal <- colorQuantile("Greens", gdp_md_est / pop_est)
# Add a properties$style list to each feature
geojson$features <- lapply(geojson$features, function(feat) {
  feat$properties$style <- list(
    fillColor = pal(
      feat$properties$gdp_md_est / max(1, feat$properties$pop_est)
    )
  )
  feat$properties$popup = paste(rep(letters,3), sep = "", collapse = "")
  #
  feat$properties$popupOptions = list(maxWidth = 1000, keepInView = TRUE)
  feat
})

#---------------------------------------------------------------------------------
# Adding popups
#---------------------------------------------------------------------------------

# Add the now-styled GeoJSON object to the map
leaflet() %>% addGeoJSON(geojson)


```

**Comment by bhaskarvk** [comment]
`addGeoJSONv2` from my leaflet.extras package has various customization supported rpubs.com/bhaskarvk/geojsonv2. You will need to build leaflet and leaflet.extras from Github.

```r
devtools::install_github('rstudio/leaflet')
devtools::install_github('bhaskarvk/leaflet.extras')
```

**Comment by bhaskarvk** [comment]
Closing in favor of `leaflet.extras::addGeoJSONv2`
