### ISSUE TITLE
Add a existing polygon to leaflet draw plugin (category drawItems)

### ISSUE THREAD

**Issue by byzheng** [rstudio/leaflet#327]
I have a few existing polygons, and potted with addPolygons and want them are editable. The editable feature is not the one in core of leaflet through option editable: true. I would like them to handle by leaflet.draw plugins. 

After googling, I can call js script after creating layers in js.
 
    drawnItems.addLayer(layer);

This code can be called in the separate function or in addPolygons. So my question is how to get a layer id its name (if I have specified it when creating) and the category "drawItems" after calling addDrawToolbar in js script.

**Comment by bhaskarvk** [comment]
This can be done easily in Shiny but not pure HTML+JS.

**Comment by bhaskarvk** [comment]
The draw plugin in leaflet.extras now supports adding existing features as part of initialization. I feel comfortable closing this.
