### ISSUE TITLE
Legend labels formatting is messy/incorrect.

### ISSUE THREAD

**Issue by bpb824** [rstudio/leaflet#330]
It looks like something in the current version of the leaflet package is causing legend labels for categorical entries to be formatted incorrectly. This is true even on RStudio's [leaflet package documentation](https://rstudio.github.io/leaflet/legends.html) site: 
![image](https://cloud.githubusercontent.com/assets/6157035/20468369/e44fb570-af4a-11e6-8f43-9cab846efb1b.png)

It may be a problem with the package, or perhaps the latest leaflet code itself.

**Comment by clausgp** [comment]
We have had the same problem in Chrome. An intermediate solution is to adjust the browser zoom to 100%, then the legend will adjust correctly, but only while it stays at 100%.

**Comment by jcheng5** [comment]
Yeah I think this is a long-standing problem that occurs with browser zoom. The leaflet doc site has not changed in almost a year I believe.

**Comment by bhaskarvk** [comment]
![Imgur](http://i.imgur.com/JfZrDIG.png)

I don't see this. Also I think this a problem only when the leaflet widget is embedded in a website that uses a CSS which interferes with leaflet's CSS. 
@bpb824 / @clausgp Could you guys confirm that you see this issue only when using the widget inside a Rmd which is knitted to a website using it's own CSS ? Or does this happen always ?

**Comment by clausgp** [comment]
I have only experienced the issue in the Chrome browser on a Windows machine, when the browser zoom is not at 100%. I have seen it from the leaflet example shown here, and running a shiny app, through rstudio opened in chrome browser.

**Comment by bhaskarvk** [comment]
OK Cool thanks for that. So it's not a problem with CSS, but with zooming.

**Comment by tiernanmartin** [comment]
I can confirm that I'm seeing this bug (Chrome browser, Windows Machine) and that it is impacted by the browser zoom level, but in my experience it only displays correctly when the browser zoom is 80% or below:

#### 100% Zoom
![ss-1](https://cloud.githubusercontent.com/assets/8197328/24075704/77e10d0e-0bdd-11e7-9cfd-cc8ca6d948a1.PNG)

#### 90% Zoom
![ss-2](https://cloud.githubusercontent.com/assets/8197328/24075709/97396ff2-0bdd-11e7-92f5-07b63420d2ac.jpg)

#### 80% Zoom (ahh... that's better)
![ss-3](https://cloud.githubusercontent.com/assets/8197328/24075713/a171c7a8-0bdd-11e7-89a5-9131a805c3bc.jpg)

**Comment by bhaskarvk** [comment]
@tiernanmartin could it be that your browser was already set to a zoom level > 100% ?
Can you do `Ctrl + 0` or `Cmd + 0` (on Mac) and see how the legend behaves ?

**Comment by tim-salabim** [comment]
I just tried with Chromium on Linux and there it seems that every zoom level that is not divisible by 50 is affected (50, 100, 150, 200, 300, ... are fine but 75, 80, 90, 125, 175, ... are messed up).

**Comment by jcheng5** [comment]
Wonder if we should switch to svg for the legend...

**Comment by jcheng5** [comment]
Never mind, it was just a float issue. Fixed in master now. You can check it with the second legend [here](https://rstudio.github.io/leaflet/legends.html), which used to exhibit the issue on Chrome.

**Comment by tim-salabim** [comment]
jip, this fixed the issue in chromium afaict

**Comment by tiernanmartin** [comment]
That commit fixed the issue for me too. Nice, @jcheng5 👍

**Comment by smartinsightsfromdata** [comment]
@jcheng5 @bhaskarvk  Sorry to spoil the party: the problem seems to persist with shinydashboard.

If I use Chrome and shinydashboard (latest releases for all R components) at zoom levels different from 100% the legend appears messy.

**Comment by smartinsightsfromdata** [comment]
Aha! I thought the changes had gone in the version on CRAN already.

The version on github fixes, also for shinydashboard.  Apologies for the confusion.
