### ISSUE TITLE
Adding more color options in makeAwesomeIcon

### ISSUE THREAD

**Issue by mubashirqasim** [rstudio/leaflet#331]
Hi there,
Possible color values  in makeAwesomeIcon are 'red', 'darkred', 'orange', 'green', 'darkgreen', 'blue', 'purple', 'darkpuple', 'cadetblue'. Is there any possibility of more colors here? For example yellow etc.

Many thanks

**Comment by bhaskarvk** [comment]
Not as of now, but I'll investigate if it can be supported in the future.

**Comment by mubashirqasim** [comment]
Many thanks for your prompt response. Really appreciate that!

**Comment by RealCoChenchao** [comment]
Do we have some color updates here?
