### ISSUE TITLE
crosstalk integration

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/leaflet#333]
What are plans for integrating `crosstalk`?  I know it is still alpha/experimental and there is this branch https://github.com/rstudio/leaflet/tree/crosstalk2 and #281, but I am not sure with all @bhaskarvk new work, if we should start from scratch or try to rebase `crosstalk2`.  I am happy to get to work on this, but I just want to make sure that I am aligned.

cc @tim-salabim

**Comment by bhaskarvk** [comment]
Actually I was waiting for 1.1 to hit cran. I haven't abandoned leaflet ;). rebasing the branch should be fairly straight forward.

**Comment by bhaskarvk** [comment]
@jcheng5 This can be closed no? Crosstalk was added in master.
