### ISSUE TITLE
Which version of leaflet, rstudio or jcheng5?

### ISSUE THREAD

**Issue by mbacou** [rstudio/leaflet#34]
Hi, could you clarify which version of the leaflet package is to be developed and maintained in the future? I have been using jcheng5 for now, but see more updates in this repo now.
This is a very useful package, would like to see support for quick legends and for re-symbolizing existing layers in the client (instead of having to pass complete features with each request).
Thanks for the hard work, --Mel.

**Comment by wch** [comment]
@mbacou The rstudio/leaflet repository is the one that will be maintained in the future.

**Comment by mbacou** [comment]
OK thanks!
