### ISSUE TITLE
Map with polygons and points

### ISSUE THREAD

**Issue by jeancabouat** [rstudio/leaflet#341]
Hi,

I have a dataframe with points (x:y coordinates) and a shapefile with polygons.
I can create two different maps with leaflet.
How can I overlay them on the same map using leaftlet ?

Thks

**Comment by bhaskarvk** [comment]
You can overlay as many layers you want by piping various `addPolygons` `addMarkers` calls.

**Comment by jeancabouat** [comment]
This is what I did, thks !
