### ISSUE TITLE
Error: No value provided for variable {x} [for addWMSTiles()]

### ISSUE THREAD

**Issue by Timag** [rstudio/leaflet#356]
Hi,

first of all thank you for the great package. 
Could you help me with the following error?

Error message:
Error: No value provided for variable {x}
(leaflet.js:6:1561)
Received from Firefox (JS) Console (same for Chrome)

Leaflet version: Pulled from github on 17.01.2017

**Code and application at:**
(Reproducible code is shown on external server, because you require permission to access their data)
http://www.big-data-scientist.de/shiny/rstudio/sample-apps/Tryer4/

**Code is mainly from:**
https://rstudio.github.io/leaflet/shiny.html

except for marked adaptions: 
addWMSTiles(baseUrl = "https://wmts10.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{x}/{z}/{y}.jpeg")
--> so the error should comes from this line.

**Reasons I can rule out:** 
1) The source does not work:
It works: See this example (plain leaflet): https://codepen.io/geoadmin/pen/grGOLV?editors=0010
2) The source does not work on my server:
I requested access for my server and it works: http://www.big-data-scientist.de/shiny/rstudio/sample-apps/wmts/index2.html

**Further remarks:**
In the running leaflet version, I see the following specifications in the javascript:
crs: L.CRS.EPSG3857, --> seems to be default: http://gis.stackexchange.com/questions/44928/what-is-the-default-projection-in-leaflet  
continuousWorld: true,
  --> added in the R code
worldCopyJump: false
 --> set in leafletOptions of R code

Thank you for your help!

**Comment by bhaskarvk** [comment]
You are confusing the syntax of WMS and Tile Servers. This has got nothing to do with the default CRS.
You can use either option below to get what you want. FWIW I prefer option 1 as data received over a tile server seems faster than over a WMS.

```r
library(leaflet)

# Option1 using tiles
leaflet(options = leafletOptions(worldCopyJump = FALSE)) %>% 
  setView(lng = 8,lat = 47, zoom = 10) %>%
  addTiles(
    urlTemplate = 'https://wmts10.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg',
    options = tileOptions(continuousWorld = TRUE))


# Option 2 using WMS
leaflet(options = leafletOptions(worldCopyJump = FALSE)) %>% 
  setView(lng = 8,lat = 47, zoom = 10) %>%
  addWMSTiles(
    baseUrl = 'https://wms.geo.admin.ch/?', 
    layers = 'ch.swisstopo.pixelkarte-farbe-pk1000.noscale',
    options = WMSTileOptions(continuousWorld = TRUE))

```
