### ISSUE TITLE
Feature Request: Pie chart markers (or another chart) on leaflet

### ISSUE THREAD

**Issue by kuzmenkov111** [rstudio/leaflet#370]
Hi everyone!

Anybody knows how to make pie chart icons on leaflet map? There is no extension for leaflet in R.

**Comment by FrancoisGuillem** [comment]
Hello, you may be interested by the new package (leaflet.minicharts)[https://github.com/rte-antares-rpackage/leaflet.minicharts]. It can add pie charts, bar charts and polar area charts to a leaflet map.

**Comment by kuzmenkov111** [comment]
Excellent!!!!!!! Thank you for reply!!!

**Comment by gbbjvijay** [comment]
Hi everyone..
please help me in clustering piechartmarkers and i need piechart representation at clustering level too

**Comment by behramkhan** [comment]
Hi I have similar issue as gbbjvijay
Can we use piechartmarkers as cluster options? Current clusteropiton in leaflet only shows a circle with the number of elements in the cluster. Can we use piechartmarkers to show a pie chart rather that just a circle?

**Comment by Neato-Nick** [comment]
I've found some users have figured it out for cluster markers

see here: https://github.com/SINTEF-9012/PruneCluster#categories

And here: http://bl.ocks.org/gisminister/10001728

But it certainly would be nice as a native feature

**Comment by schloerke** [comment]
leaflet.minicharts solves the piechart issue. 

I believe clustered piecharts is not a core feature R leaflet package.  This issue should either be moved into leaflet.minicharts or into leaflet.extras.  Will submit an issue into leaflet.minicharts

**Comment by schloerke** [comment]
Closing, as the original issue is solved with leaflet.minicharts and clustered leaflet pie charts will not be included in leaflet R pkg.  

An issue has been submitted to leaflet.minicharts to implement clustered pie charts
