### ISSUE TITLE
Error color for fontawesome Icon in makeAwesomeIcon

### ISSUE THREAD

**Issue by Lchiffon** [rstudio/leaflet#374]
This error is only shown in  'fa' (fontawesome) icons in `makeAwesomeIcon`, `glyphicon` and `ion` are working well.

```
leaflet() %>% addTiles() %>%
  addAwesomeMarkers(lng=174.768, lat=-36.852,
                    icon = makeAwesomeIcon(icon = "home","fa"))
```
The icon color should be white, well, turn out to be black

![image](https://cloud.githubusercontent.com/assets/7221728/22877883/6bcf5c8a-f212-11e6-81d6-7993aab008f8.png)

Add `iconColor` parameter is not working either.
```
leaflet() %>% addTiles() %>%
  addAwesomeMarkers(lng=174.768, lat=-36.852,
                    icon = makeAwesomeIcon(icon = "home","fa",iconColor="white"))

```

**Comment by bhaskarvk** [comment]
Wow, it seems it doesn't work with only 'white' and that too only for fontawesome icons. I tested with other icon colors using names (blue, green, cyan etc.) and it works.
For white though I had to use the hex string '#FFFFFF', that works!
