### ISSUE TITLE
Is fillOpacity no longer honored for addPolygons?

### ISSUE THREAD

**Issue by okjed** [rstudio/leaflet#377]
My apologies for not posting a succinct example but I upgraded to the github version of the package and discovered that my fillOpacity settings were no longer being honored as well as for some of the examples within the package.

**Comment by jcheng5** [comment]
Works fine for me. Can you provide an example?

```r
leaflet(mapview::gadmCHE) %>% addPolygons(fillOpacity = 1, fillColor = "white", weight = 1)
```

**Comment by okjed** [comment]
I should have simplified my scenario - your example does work fine. I will look into it some more but my Shiny app worked fine minus some features I wanted to leverage from the newer leaflet such as labels. When I upgraded, I lost opacity with the polygons in my app. I must be triggering a failure somewhere else.
