### ISSUE TITLE
Double-clicking on polygon no longer zooms in

### ISSUE THREAD

**Issue by jcheng5** [rstudio/leaflet#381]
In this example, double-clicking on the map doesn't zoom in if the mouse pointer happens to be over a polygon. This isn't the case for the current CRAN version (1.0.1).

```r
library(leaflet)
library(albersusa)

ne_states <- c("CT","ME","MA","NH","RI","VT","NY","NJ","PA")

states <- usa_composite()
states <- states[states$iso_3166_2 %in% ne_states,]

pal <- colorQuantile("Blues", states$pop_2014)

leaflet(states) %>%
  addPolygons(
    weight = 1.5, fillOpacity = 0.5, smoothFactor = 0.5,
    color = "black", fillColor = ~pal(pop_2014))
```

**Comment by jcheng5** [comment]
@bhaskarvk @tim-salabim FYI I think this is a blocker for submitting Leaflet 1.1 to CRAN. I'm planning to investigate today.

**Comment by tim-salabim** [comment]
confirmed. same here:
```r
library(sf)
library(mapview)
states %>% st_as_sf() %>% mapview()
```

**Comment by bhaskarvk** [comment]
Strange, I never even knew that this was the default behavior. FWIW the JS lib has no such behavior out of the gate. Is this something that was part of the R package?

**Comment by jcheng5** [comment]
The default behavior (from the JS lib) is clicking anywhere on the map causes zoom-in. The polygons interfering with that is new. I've git bisected it to the recent multipolygon work I just merged, digging into why now.

**Comment by bhaskarvk** [comment]
got it.

**Comment by jcheng5** [comment]
This appears to be a problem with the underlying `L.multiPolygon`. My PR changes all polygons to `L.multiPolygon`. With Leaflet 1.x, the distinction goes away; there's no `L.multiPolygon` function anymore but `L.polygon` can take multipolygon data.

My current thought is to work around this for now by detecting when a multipolygon is in fact a single polygon and using `L.polygon` in that case. At least this will not regress the package. And then in the next release when we move to Leaflet 1.x then I imagine the problem will disappear.

**Comment by tim-salabim** [comment]
Not sure if this helps, but afaik `library(sf)` will cast all polygons to `MULTIPOLYGON` if a mixed (POLYGON and MULTIPOLYGON) geometry is present (just as you do). So you may not be able to tell on the R side...

**Comment by jcheng5** [comment]
@tim-salabim The R side doesn't attempt to tell, and in fact the leaflet R code also casts everything to multipolygon essentially. The question now is what to do on the JS side.

I just tested my proposed solution and it's terrible. With the example above, you can double-click Vermont or New Hampshire and it zooms it, but not New York or Maine. It feels arbitrary and broken.

If I take the JS multipolygon data and concatenate all the rings from the multiple polygons into a single polygon, i.e. create a single `L.polygon` that contains multiple outer rings, then it all works fine--the polygons are all rendered correctly, including ones with holes, and double-click works as normal. I noticed that this was the case when I was implementing `MULTIPOLYGON` support originally: I was trying to demonstrate multipolygon `sp` objects failing with the old code and working with the new code, but I couldn't actually get the old code to fail.

I am tempted to move forward with this (multiple outer rings in a single polygon) since it doesn't regress the behavior from 1.0 and still appears to work with `MULTIPOLYGON`.

**Comment by tim-salabim** [comment]
If I understand you correctly, this should be fine. 
This would mean that highlighting will still highlight all polygons originally connected via multipolygon, even though they are now essentially one single polygon with multiple outer rings right? 
If that is the case, then it seems to be more of a technical issue that won't affect the end-user (assuming they won't investigate in the browser console).

**Comment by jcheng5** [comment]
@tim-salabim Yes, that appears to be the case. I can't see any downside. The scary thing is that this behavior isn't documented and I can't figure out from looking at the leaflet.js code how it's working. I would be more worried about that if Leaflet.js 1.0 didn't make this all moot.

**Comment by jcheng5** [comment]
@tim-salabim From what I can tell this whole issue appears not to affect `states %>% st_as_sf() %>% mapview()` anyway, as your own click handler seems to prevent double-click from zooming (as do built-in popups, so this isn't a bug but intentional behavior).

**Comment by tim-salabim** [comment]
@jcheng5 ok, one final thought. We might run into some issues with **mapedit** with this behavior, as we will not be able to tell which polygons belong to each other when passing things back to R (after editing for example), but that is a whole different story and miles away from being a usable product so I'd say your solution should be fine for now.

**Comment by jcheng5** [comment]
@tim-salabim The editing issue comes up here too (talking about Leaflet 1.0 though): https://github.com/Leaflet/Leaflet/issues/3498

**Comment by tim-salabim** [comment]
@jcheng5 thanks for the heads-up. I think we may be able to address this with a suitable index passed along the editing round-trip in **mapedit** as we know the MULTI* structure before passing to JS... Challenges are always good :-)
Thanks for all the work on leaflet! Much appreciated!

**Comment by bhaskarvk** [comment]
FWIW do keep this issue at the back of your mind. https://github.com/Leaflet/Leaflet/issues/3498
