### ISSUE TITLE
Feature Request: PruneCluster

### ISSUE THREAD

**Issue by Jano121** [rstudio/leaflet#383]
Hi, Is possible implent [this plugin](https://github.com/SINTEF-9012/PruneCluster) instead Leaflet.markerCluster?

**Comment by bhaskarvk** [comment]
Any specific reason why? There's already a lot of effort put into MarkerCluster plugin to make it play nicely with things like spidering/freeze-unfreeze/grouped-layers etc. And it performs fairly well for lots of points.

**Comment by bhaskarvk** [comment]
Closing as no further answer. In any case there is a sizable amount of R and JS code for supporting marker clustering properly and moving to PruneCluster is a nontrivial task which is not justified unless the plugin we are using has some limitations/bugs that PruneCluster addresses.
