### ISSUE TITLE
Leaflet no longer works after install from github

### ISSUE THREAD

**Issue by Monduiz** [rstudio/leaflet#387]
After running : `install_github('rstudio/leaflet')`

I am now getting this error:

    Error in get(Info[i, 1], envir = env) : 
      lazy-load database     '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/leaflet/R/leaflet.rdb' is corrupt
    In addition: Warning message:
    In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
    Error: package or namespace load failed for ‘leaflet’

I am running Rstudio 1.0.136 on macOS 10.11.6

**Comment by bhaskarvk** [comment]
Duplicate of #386.

Try
You can do

```r
addTiles(urlTemplate = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
```

**Comment by jcheng5** [comment]
This happens sometimes when using devtools to install a package that's already loaded. A quick session restart (Ctrl-Shift-F10) should clear it up.
