### ISSUE TITLE
Palette functions for addPolylines()

### ISSUE THREAD

**Issue by josiekre** [rstudio/leaflet#389]
I'm trying to use palette functions to color polylines according to a variable in the data, but they are only showing up as the last color in the scale.

Here's what the data looks like:

```
# A tibble: 100 × 4
x
      grp index       lon      lat
    <chr> <int>     <dbl>    <dbl>
1  219233 10005 -84.14247 34.10217
2  219233 10005 -84.21969 33.95469
3  167168 10056 -84.33130 34.04140
4  167168 10056 -84.34574 34.01926
5  208233 10131 -84.51261 33.91128
6  208233 10131 -84.21969 33.95469
7  219238 10141 -84.14247 34.10217
8  219238 10141 -84.12763 33.95239
9  145210 10362 -84.36784 33.91493
10 145210 10362 -84.31505 33.93641
# ... with 90 more rows
```

```
leaflet(x) %>%
  setView(lng = -84.42205, lat = 33.84635, zoom = 10) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolylines(lng = ~lon, lat = ~lat, group = ~grp,
               color = ~pal(index), weight = 2, opacity = 1) %>%
  addLegend(pal = pal, values = ~index, opacity = 1)
```

The legend builds correctly, but the polylines don't. Here's a screenshot: 

![screenshot 2017-02-27 17 47 51](https://cloud.githubusercontent.com/assets/5776153/23351381/e5ceed72-fd14-11e6-83c3-9ae60f3f1cbf.png)

I can make a dataframe that's reproducible if it would be helpful.

**Comment by bhaskarvk** [comment]
A fully reproducible example would be really useful for debugging.

**Comment by jcheng5** [comment]
There might be some confusion here about the `group` parameter. In ggplot2 this is used to identify which points belong to a given polyline. In leaflet, this is used instead to group multiple layers together to be [shown/hidden](http://rstudio.github.io/leaflet/showhide.html) together.

So I believe what's happening might be that the lat/lng data is being interpreted as a single polyline with 100 points. If you want this to be 50 polylines, you'll either need to insert `NA` rows between each polyline (ugh) or use either the `sp` or `sf` packages.

**Comment by jcheng5** [comment]
Here's a quick demo of how to use purrr to easily insert `NA` rows between polylines. And @bhaskarvk it turns out that `validateCoords` warns on this perfectly valid data :(

```r
# Dummy data
group <- c(219233,219233,167168,167168,208233,208233,219238,219238,145210,145210)
lng <- c(-84.14247,-84.21969,-84.33130,-84.34574,-84.51261,-84.21969,-84.14247,-84.12763,-84.36784,-84.31505)
lat <- c(34.10217,33.95469,34.04140,34.01926,33.91128,33.95469,34.10217,33.95239,33.91493,33.93641)
df <- data.frame(group=group, lng=lng, lat=lat)

# Demo of the problem--all points are considered part of same polyline
library(leaflet)
pal <- colorFactor("Accent", NULL)
leaflet(df) %>% addPolylines(lng = ~lng, lat = ~lat, color = pal(1:5))

# Helper function to split numeric vector with NA, based on a separate group vector
library(purrr)
grouped_coords <- function(coord, group) {
  data.frame(coord = coord, group = group) %>%
    slice_rows("group") %>%
    by_slice(~c(.$coord, NA), .to = "output") %>%
    .$output %>% unlist()
}

# Use the helper function to split the lines
library(leaflet)
pal <- colorFactor("Accent", NULL)
leaflet(df) %>% addPolylines(
  lng = ~grouped_coords(lng, group),
  lat = ~grouped_coords(lat, group),
  color = pal(1:5))
```

**Comment by josiekre** [comment]
Thanks for your help. I ended up editing the grouping function to make sure it draws the darker lines on top of the lighter lines. 

```{r}
library(purrr)
grouped_coords <- function(coord, group, order) {
  data_frame(coord = coord, group = group) %>%
    group_by(group) %>%
    by_slice(~c(.$coord, NA), .to = "output") %>%
    left_join(
      data_frame(group = group, order = order) %>% 
        distinct()) %>%
    arrange(order) %>%
    .$output %>%
    unlist()
}
```

Rewriting @jcheng5's example:
```{r}
group <- c(219233,219233,167168,167168,208233,208233,219238,219238,145210,145210)
lng <- c(-84.14247,-84.21969,-84.33130,-84.34574,-84.51261,-84.21969,-84.14247,-84.12763,-84.36784,-84.31505)
lat <- c(34.10217,33.95469,34.04140,34.01926,33.91128,33.95469,34.10217,33.95239,33.91493,33.93641)
count <- c(10005,10005,10056,10056,10131,10131,10141,10141,10362,10362)
df <- data_frame(group=group, lng=lng, lat=lat, count=count)

leaflet(df) %>% addPolylines(
    lng = ~grouped_coords(lng, group, index),
    lat = ~grouped_coords(lat, group, index),
    color = ~pal(index))
```

**Comment by BrunoSE** [comment]
Hello, first of all, thanks very much to all of you. I had the same issue than @josiekre . Now just for the sake of being perfectionist I believe the last lines of code you sent should be calling "count" and not index in the grouped function. This means it would end up like:

group <- c(219233,219233,167168,167168,208233,208233,219238,219238,145210,145210)
lng <- c(-84.14247,-84.21969,-84.33130,-84.34574,-84.51261,-84.21969,-84.14247,-84.12763,-84.36784,-84.31505)
lat <- c(34.10217,33.95469,34.04140,34.01926,33.91128,33.95469,34.10217,33.95239,33.91493,33.93641)
count <- c(10005,10005,10056,10056,10131,10131,10141,10141,10362,10362)
df <- data_frame(group=group, lng=lng, lat=lat, count=count)

leaflet(df) %>% addPolylines(
    lng = ~grouped_coords(lng, group, count),
    lat = ~grouped_coords(lat, group, count),
    color = ~pal(count))

I do have a question though, is "group" just an index variable to separate the data? If my dataframe doesn't have one, may I use row.names(df) as a proper group variable?

**Comment by dwisp** [comment]
I have come with a solution that seems more natural and simple to understand. To me, at least.
It basically assembles points into line fragments. 

* `dplyr` `lead()` - the opposite of `lag()` - pushes the vector one index behind to get lines that go from current point to the next.
* `str_c` returns NA when NA is in the output i.e. the last row that has no next point, so we drop NA
* transform df to spatial using `sf`
* ??? add color palette
* PROFIT

```
df = df %>%
    dplyr::mutate(
      lon = as.numeric(lon) + runif(nrow(dfRawTrack), -0.00025, 0.00025),
      lat = as.numeric(lat) + runif(nrow(dfRawTrack), -0.00025, 0.00025),
      # str_c returns NA when one of the arguments is NA
      # last lead() element is NA and will be dropped
      geom_wkt = stringr::str_c(
        "LINESTRING (",
        stringr::str_c(
          str_c(lon, lat, sep = " "),
          str_c(lead(lon), lead(lat), sep = " "),
          sep = ", "
        ),
        ")"
      # add your color palette here!
      ),
    ) %>%
    dplyr::select(-lon, -lat) %>%
    # readWKT cannot handle NAs
    tidyr::drop_na() %>%
    sf::st_as_sf(wkt = "geom_wkt", crs = 4326)
```
