### ISSUE TITLE
Value for radius assumes largest value

### ISSUE THREAD

**Issue by NathanDotTo** [rstudio/leaflet#398]
Hi

The code below draws a map with two airports.

The addCircleMarkers uses the airports_df such that the label is based on the IATA value, the popup on the Name value, and a calculation on the total_departures for the radius, which is also shown in the popup for debug purposes.

The resulting map shows the radius of the circles to be identical, and the value for the sqrt(total_departures) in the popup is also the same. This is wrong, as the value of total_departures for NHT is 0, so the formula should return 10 for the radius

What actually happens is that the value of sqrt(527) is being used for both circles.

Since the text for the popup and labels is correct, the correct row is being used for each circle marker, but not the correct value for total_departures.

I suspect that my syntax is wrong in some subtle way, but I can't see how. 

Help please?

Many thanks

Nathan

```
rm(list=ls())
require("leaflet")
require("dplyr")
Name <- c("London Heathrow Airport", "RAF Northolt")
IATA <- c("LHR", "NHT")
Lat <- c(as.numeric(51.4706), as.numeric(51.5530014038))
Long <- c(as.numeric(-0.461941), as.numeric(-0.418166995049))
total_departures <- c(527, 0)
airports_df <- data.frame(Name, IATA, Lat, Long, total_departures, stringsAsFactors = FALSE)
str(airports_df)
airports_map_circles <- leaflet() %>% addTiles() %>% 
  addCircleMarkers(data = airports_df, popup = ~paste(Name, " - ", max(sqrt(total_departures), 10), sep = ""), label = ~IATA, clusterOptions = markerClusterOptions(), color = "purple", radius = ~max(sqrt(total_departures), 10)) 
airports_map_circles
```

**Comment by jcheng5** [comment]
Can you try replacing both calls to `max` with `pmax` instead? The former returns one value while the latter gives a vector.

**Comment by NathanDotTo** [comment]
That was the solution. Thanks!
