### ISSUE TITLE
addPolylines integration doesn't work?

### ISSUE THREAD

**Issue by cnowzohour** [rstudio/leaflet#406]
I've been trying to visualise some spatio-temporal data with Crosstalk and Leaflet - looks very cool! However, `addPolylines` doesn't seem to work with Crosstalk, see the example  below:

    library(crosstalk)
    library(leaflet)
    
    theta <- seq(0, 2*pi, len = 100)
    dat <- data.frame(
      lon = cos(theta),
      lat = sin(theta),
      t = 1:100
    )
    
    sd <- SharedData$new(dat)
    
    map <- leaflet() %>%
      addTiles() %>%
      addCircleMarkers(data = sd, lat = ~lat, lng = ~lon, color = "blue") %>%
      addPolylines(data = sd, lat = ~lat, lng = ~lon, color = "blue")
    
    bscols(
      filter_slider("t", "Time", sd, column = ~t),
      map
    )

I tried the changes from this PR (adapted to `addPolylines`), but it did not help.

**Comment by bhaskarvk** [comment]
Currently crosstalk works only with pointdata, support for polyline/polygon data is coming, but not in trunk as of now.

**Comment by cnowzohour** [comment]
OK thanks for clarifying - looking forward to this feature!
