### ISSUE TITLE
Why tms=TRUE in TileOptions not work

### ISSUE THREAD

**Issue by danzhuibing** [rstudio/leaflet#409]
I want to use Tencent Map in leaflet for R, but failed. Tecent Map is following in TMS standard, so I set `tms=TRUE` in `TileOptions`. But it does not work. Here is the full code:

``` r
leaflet() %>%
addTiles(
'http://rt1.map.gtimg.com/realtimerender?z={z}&x={x}&y={y}&type=vector&style=0',
  tileOptions(tms=TRUE, tileSize=256, minZoom=9, maxZoom=17),
  attribution = '&copy; Tencent Map</a>'
) %>% 
setView(116.40,39.90, zoom = 10)
```

But when I use leaflet in js, it works:

``` js
var mymap = L.map('mapid').setView([39.90, 116.40], 10);
L.tileLayer('http://rt1.map.gtimg.com/realtimerender?z={z}&x={x}&y={y}&type=vector&style=0', {
        maxZoom: 18,
        attribution: '&copy; Tencent Map ',
        tms: true
    }).addTo(mymap);
```

In addition, I found that some other options also not work, like `subdomains`.

**Comment by bhaskarvk** [comment]
You're passing it as the second argument which is not right. Pass it by explicitly setting the options argument.

**Comment by danzhuibing** [comment]
thanks~
