### ISSUE TITLE
Is drill-down in choropleth maps possible?

### ISSUE THREAD

**Issue by pssguy** [rstudio/leaflet#41]
If I create a chroropleth map of the US states, using addPolygons, is it possible to have an event which would select the chosen state so that county map data / and a resultant map of that state alone can be produced?

**Comment by jcheng5** [comment]
Yes, if the map outputId is `"foo"` you could look at `input$foo_shape_click` which will give you either `NULL` or a list like this:

```
list(
  lat = latitude,
  lng = longitude,
  id = layerId
)
```

**Comment by pssguy** [comment]
Thanks Joe. I can extract a lat and lon this way. 

However, I want to return the country clicked on, which is, say, in  the data$country field from the underlying data object. I assume I can use the data argument of addPolygons but I cannot seem to return it correctly

    getMapData = function(data,location,session){
    # want to return country
      })

    map <-    leaflet(data = data) %>%
    addTiles()

     map %>% 
    addPolygons(...,
     data = getMapData(map))

Any help appreciated

**Comment by blmoore** [comment]
Use `layerId` (e.g. set polygon layerId's to respective country), then capture as shown above?

**Comment by pssguy** [comment]
Thanks guys.  layerId = data$country looks good

**Comment by jcheng5** [comment]
Yep. You don't need to pass the `data` arg to addPolygons, as the
leaflet(data) argument is inherited by default. And you can do `layerId =
~country` instead of data$country, if you want to. Read this whole page for
more information: http://rstudio.github.io/leaflet/map_widget.html

**Comment by efh0888** [comment]
Hey Joe,

This was super helpful.

I've been able to implement a drill-down leaflet map going from country to state/province with an info control that changes on hover, but it's still pretty buggy. Would you mind looking at my code at https://github.com/efh0888/leafletDrilldown for some help? The README has all the details...
