### ISSUE TITLE
Passing an API key to the Thunderforest tiles API

### ISSUE THREAD

**Issue by skgrange** [rstudio/leaflet#410]
Hello Leaflet team,
A couple of months ago the Thunderforest API changed which requires the use of an API key. The API key is used as a suffix like so: `https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}`. I understand that the `providerTileOptions` function allows for some arguments to be passed to the tile API, but I cannot seem to successfully pass the API key. My tiles end up with an `API Key Required` printed on them. A simple example is: 

```
# Create an empty map with thunderforest tiles
leaflet() %>% 
  addProviderTiles(providers$Thunderforest.Outdoors, 
    options = providerTileOptions(apikey = "mykey"))
```

Is there an undocumented way to pass the API key in this example? Thanks.

**Comment by bhaskarvk** [comment]
We will need to rebuild leaflet w/ the latest version of leaflet-providers. For now you can do

```r
leaflet() %>%
  addTiles(
    urlTemplate = "https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}",
    attribution = "&copy; <a href='http://www.thunderforest.com/'>Thunderforest</a>,  &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>",
    options = tileOptions(variant='transport-dark', apikey = 'YOUR-KEY')
  )
```

You should pass in your key and use which ever variant you want.

**Comment by skgrange** [comment]
Thanks heaps!
