### ISSUE TITLE
argument elementId in leaflet()

### ISSUE THREAD

**Issue by tim-salabim** [rstudio/leaflet#411]
Would it be possible to add argument `elementId` to `leaflet()` and pass it through to `createWidget` so that we can get finer control over widget creation? I would need to access the widget later on, but currently I have no access as ids are randomly created. 
Or am I missing something?

**Comment by bhaskarvk** [comment]
Yes that is certainly doable, I'll have some PRs ready for @jcheng5 this weekend.
