### ISSUE TITLE
Discrepancy in the Map of India

### ISSUE THREAD

**Issue by bpr1989** [rstudio/leaflet#416]
Dear Team, I have recently gone through the 'Leaflet' package in R and I find a lot of discrepancy in the maps.

I am concerned about the map of India. A part of Jammu & Kashmir has been shown as part of Pakistan which is a very big mistake. How can this be rectified immediately ?

**Comment by bhaskarvk** [comment]
Basemaps co.e from providers not R or the Javascript lib.

**Comment by bpr1989** [comment]
So, what can be done ?
