### ISSUE TITLE
saveWidget render blank map in self contained html

### ISSUE THREAD

**Issue by yonicd** [rstudio/leaflet#417]
this gives a grey map back into the html

```
saveWidget(widget = leaflet() %>% addTiles(),file = 'leaflet.html',selfcontained = T)
```

getting this in the console

![screen shot 2017-04-07 at 14 28 44](https://cloud.githubusercontent.com/assets/1755487/24814167/9305cd1a-1b9e-11e7-9e9b-76c016b19113.png)

**Comment by bhaskarvk** [comment]
Yeah that's a known leaflet issue. It's fixed in master but the cran ver. has not been upfated yet. Try installing leaflet from github.
