### ISSUE TITLE
Changing size of zoom levels

### ISSUE THREAD

**Issue by bastianmanz** [rstudio/leaflet#419]
Hi there,

more of a feature request than a bug. I have mapped a polygon, but if I zoom into level 8 not the entire shape fits within the screen extent. If I zoom out to level 7, it only covers a quarter of the screen.

Can I adjust what a change of one step in zoom level does in real terms?

Thank you!

**Comment by bhaskarvk** [comment]
If you are using base maps then you are stuck with what ever zoom levels the base map supports. In that case the only option is to size your widget as big or as small as you want using the 'weight' and 'height' arguments to the `leaflet()` function.

How ever if you are not using base maps, you can use fractional zooms. See https://bhaskarvk.github.io/tilegramsR/articles/plotting/PlottingWithLeaflet.html for some examples.
