### ISSUE TITLE
LayerGroup and layer.control

### ISSUE THREAD

**Issue by kent37** [rstudio/leaflet#42]
Is there a way to add layers to groups and enable the layer group control? Possibly related: what is the layerId parameter for? I would like to do something like this example:
http://leafletjs.com/examples/layers-control.html
though in my case the layers are polygons rather than markers.

**Comment by kent37** [comment]
Is there any hope of a fix for this? Layer groups are a very nice feature of leaflet.js.

**Comment by jcheng5** [comment]
Yep, coming next week hopefully!

**Comment by jhollist** [comment]
This would be great, has it been added in yet?

**Comment by einarhjorleifsson** [comment]
guess a collaboration with https://github.com/rocalabern/rleaflet may be kosher. the implementation you are asking for is already there.
einar

**Comment by kent37** [comment]
I don't see any support for LayerGroup in rleaflet.

**Comment by kent37** [comment]
@einarhjorleifsson maybe you mean this one? https://github.com/chgrl/leafletR

**Comment by jcheng5** [comment]
OK, I have a branch with support for this now--it's a little rough but I would love some early testing/feedback.

See install instructions and details on the PR: https://github.com/rstudio/leaflet/pull/116

**Comment by jhollist** [comment]
:+1:

I'll give it a try when I get a chance.

**Comment by kent37** [comment]
I tried this today. It was trivial to get working and it does exactly what I wanted. Thank you!

**Comment by jcheng5** [comment]
Thanks. Anyone else? I'm getting ready to merge this to master and we'll follow with a CRAN release soon after, so if you want to weigh in now is the time...

**Comment by jhollist** [comment]
@jcheng5 Looks and works great.  Being able to "label" the various layers is a good idea.  

One thought I had (and didn't get to play around with) is how do the layer controls interact with legends?  For instance if I had multiple circle markers with different color schemes, you'd need two legends.  Would those legends turn off with the layer?  

Thanks for the quick turn around on this.  It is useful.

**Comment by jcheng5** [comment]
@jhollist No, currently legends can't belong to groups. I'll have to think about that.

**Comment by jhollist** [comment]
Next version, perhaps...  Thanks again for the quick turnaround.

On Tue, Jun 16, 2015 at 3:20 PM, Joe Cheng <notifications@github.com> wrote:

> @jhollist <https://github.com/jhollist> No, currently legends can't
> belong to groups. I'll have to think about that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rstudio/leaflet/issues/42#issuecomment-112534391>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by jcheng5** [comment]
Merged to master. Thanks all!
