### ISSUE TITLE
iconCreateFunction does not work when used in leafletProxy

### ISSUE THREAD

**Issue by gegrimm** [rstudio/leaflet#420]
see: http://stackoverflow.com/questions/43483696/iconcreatefunction-does-not-work-when-adding-markers-with-leafletproxy

basically when using markerClusterOptions(), if you try to pass your own JS to alter appearance of cluster, this only works when rendering leaflet() but breaks when later adding markers with leafletProxy()

**Comment by NilsOle** [comment]
Agree & can reproduce. Feel invited to view my post here: https://stackoverflow.com/questions/47922951/does-markercluster-work-together-with-leafletproxy-and-option-iconcreatefuncti

**Comment by nicocriscuolo** [comment]
I am experiencing the same problem. Have someone come up with a solution?

Thanks!

**Comment by micahwilhelm** [comment]
I've found the same problem. Will someone from rstudio please comment if this bug will be fixed?

**Comment by aavanesy** [comment]
Please update us on this.

**Comment by barengb** [comment]
I'm experiencing the same/similar problem. I don't succeed in adapting the colors of the marker-clusters when using leafletProxy, nor when using the iconCreateFunction, nor when trying it via CSS. Would be great if this can be solved. Thanks for your efforts!
