### ISSUE TITLE
Legend alpha / opacity not working for NA

### ISSUE THREAD

**Issue by mtennekes** [rstudio/leaflet#424]
I would like the color for missing values to be semi-transparent in the legend. This doesn't seem to work:

    leaflet() %>% addLegend(pal = colorNumeric(rainbow(6), domain = 1:6, alpha = FALSE, 
    na.color = "#FF0000"), opacity=.25, values=c(1:6, NA))

produces

![legend1](https://cloud.githubusercontent.com/assets/2444081/25660930/b4a6281e-300e-11e7-9209-7ffa9b11e89d.png)

    leaflet() %>% addLegend(pal = colorNumeric(rainbow(6, alpha=.25), domain = 1:6, alpha = TRUE, 
    na.color = "#FF000040"), values=c(1:6, NA))

produces

![legend2](https://cloud.githubusercontent.com/assets/2444081/25660935/b80fb06a-300e-11e7-85e2-84744c994017.png)

    leaflet() %>% addLegend(pal = colorNumeric(rainbow(6), domain = 1:6, alpha = FALSE, 
    na.color = "#FF000040"), opacity=.25, values=c(1:6, NA))

produces

![legend3](https://cloud.githubusercontent.com/assets/2444081/25660938/ba60fdba-300e-11e7-873a-df28d4c6ba35.png)

    Session info -----------------------------------------------------------------------------------------------------------
     setting  value                       
     version  R version 3.4.0 (2017-04-21)
     system   x86_64, linux-gnu           
     ui       RStudio (1.0.143)           
     language en_US                       
     collate  en_US.UTF-8                 
     tz       Europe/Amsterdam            
     date     2017-05-03                  

    Packages ---------------------------------------------------------------------------------------------------------------
     package     * version    date       source                          
     colorspace    1.3-2      2016-12-14 CRAN (R 3.3.2)                  
     crosstalk     1.0.0      2016-12-21 CRAN (R 3.3.2)                  
     devtools      1.12.0     2016-12-05 CRAN (R 3.3.2)                  
     digest        0.6.12     2017-01-27 CRAN (R 3.3.2)                  
     htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                  
     htmlwidgets   0.8        2016-11-09 CRAN (R 3.3.2)                  
     httpuv        1.3.3      2015-08-04 CRAN (R 3.3.2)                  
     jsonlite      1.4        2017-04-08 CRAN (R 3.4.0)                  
     leaflet     * 1.1.0.9000 2017-05-03 Github (rstudio/leaflet@00bb41c)
     magrittr      1.5        2014-11-22 CRAN (R 3.3.2)                  
     memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                  
     mime          0.5        2016-07-07 CRAN (R 3.3.2)                  
     munsell       0.4.3      2016-02-13 CRAN (R 3.3.2)                  
     plyr          1.8.4      2016-06-08 CRAN (R 3.3.2)                  
     R6            2.2.0      2016-10-05 CRAN (R 3.3.2)                  
     Rcpp          0.12.10    2017-03-19 CRAN (R 3.4.0)                  
     rstudioapi    0.6        2016-06-27 CRAN (R 3.3.2)                  
     scales        0.4.1      2016-11-09 CRAN (R 3.3.2)                  
     shiny         1.0.3      2017-04-26 CRAN (R 3.4.0)                  
     withr         1.0.2      2016-06-20 CRAN (R 3.3.2)                  
     xtable        1.8-2      2016-02-05 CRAN (R 3.3.2)                  
     yaml          2.1.14     2016-11-12 CRAN (R 3.3.2)

**Comment by jcheng5** [comment]
Thanks, should be fixed on master now.
