### ISSUE TITLE
leaftet.R is drawing baselayers on top of overlay layers when the base layer is changed

### ISSUE THREAD

**Issue by jzadra** [rstudio/leaflet#430]
I'm running into a problem with leaflet for R: When I change the base layer (polygons), the overlay layer gets pushed behind the base layer. From my reading of the leafletR help files, the overlay layers should always have a higher z-index than the base layers, and should stay on top.

```
require(acs)
require(tigris)
require(leaflet)
require(tidyverse)

leaflet(data = counties(state = "UT")) %>% 
  addPolygons(color = "red", fillColor = "orange", group = "base1", fillOpacity = 1) %>% 
  addPolygons(color = "pink", fillColor = "purple", group = "base2", fillOpacity = 1) %>% 
  addPolygons(color = "yellow", fillColor = "green", group = "overlay", fillOpacity = 1) %>% 
  addLayersControl(baseGroups = c("base1", "base2"), options = layersControlOptions(collapsed = F), overlayGroups = "overlay")
```
Output from the above code: http://rpubs.com/bvila/overdraw

Also posted here:
https://stackoverflow.com/questions/44122246/r-leaflet-is-drawing-base-layers-on-top-of-overlay-layers

**Comment by jzadra** [comment]
Any help on this would be greatly appreciated, as I'm up against a deadline. Does autoZIndex not work?   Is this overdrawing the expected behavior?  If so, is there any workaround?

**Comment by jcheng5** [comment]
> the overlay layers should always have a higher z-index than the base layers

What this means is that the polygon layers should always have a higher z-index than tile layers. The layers control uses this terminology because the base groups are intended to be base (tile) layers, and the overlay groups are intended to be overlay (polygon) layers.

You can work around this with a bit of JavaScript, see the `onRender` stage added to the pipe (you only have to do this once for a given map object):

```r
leaflet(data = counties(state = "UT")) %>% 
  addPolygons(color = "red", fillColor = "orange", group = "base1", fillOpacity = 1) %>% 
  addPolygons(color = "pink", fillColor = "purple", group = "base2", fillOpacity = 1) %>% 
  addPolygons(color = "yellow", fillColor = "green", group = "overlay", fillOpacity = 0.5) %>% 
  addLayersControl(baseGroups = c("base1", "base2"), options = layersControlOptions(collapsed = F), overlayGroups = "overlay") %>%
  htmlwidgets::onRender("
    function(el, x) {
      this.on('baselayerchange', function(e) {
        e.layer.bringToBack();
      })
    }
  ")
```

**Comment by jzadra** [comment]
Awesome.  Thank you so much!!

**Comment by t-stratmann** [comment]
When I run the htmlwidgets::onRender function I get the error: "Error in addHook(x, "render", jsCode, data) :  argument "jsCode" is missing, with no default." Looking at the help file you need to provide both  x (an HTML Widget object) and jsCode (character vector containing JavaScript code). This is beyond my coding skills. If possible, I would appreciate an update to the above issue, given this error message. Many thanks!
