### ISSUE TITLE
why I cannot use label arguments in addMarkers?

### ISSUE THREAD

**Issue by wikithink** [rstudio/leaflet#431]
unused arguments (label = "Default Label", labelOptions = labelOptions(noHide = T))

R 3.3.1
leaflet 1.1.0
centos 6.4 64bit

but I can use the label arguments in windows7,the leaflet version same to centos

why?

https://stackoverflow.com/questions/31745525/leaflet-with-r-add-text-labels

**Comment by bhaskarvk** [comment]
Full code please.

**Comment by wikithink** [comment]
library(leaflet)

leaflet() %>% addTiles() %>% setView(-118.456554, 34.09, 13) %>%
  addMarkers(
    lng = -118.456554, lat = 34.105,
    label = "Default Label",
    labelOptions = labelOptions(noHide = T)) %>%
  addMarkers(
    lng = -118.456554, lat = 34.095,
    popup= "kkk",
    label = "Label w/o surrounding box",
    labelOptions = labelOptions(noHide = T, textOnly = TRUE)) 

thanks

**Comment by wikithink** [comment]
![image](https://cloud.githubusercontent.com/assets/18325017/26477694/08968278-41fa-11e7-9d54-f6b509439122.png)

**Comment by wikithink** [comment]
I solved this prob with this code:
devtools::install_github('rstudio/leaflet')
and the version of leaflet package is 1.1.0.9000

it's ok
