### ISSUE TITLE
Assign multiple layerIds to group.

### ISSUE THREAD

**Issue by osh-chicago** [rstudio/leaflet#434]
Hi,

I would like to be able to assign multiple layerIds to a group rather than have to duplicate the same layer every time I want it to be part of a group. 

For example, I want to create three groups: "All Locations", "Loop", and "River North." "All Locations" has two layers in it and "Loop" and "River North" have one layer each.

Current Implementation: 

```r
map <- addPolygons(map, data = temp.loop.spdf, fillColor = ~temp.gary(eligibles_adj),group = "All Locations")  
map <- addPolygons(map, data = temp.river.spdf, fillColor = ~temp.gary(eligibles_adj),group = "All Locations") 
map <- addPolygons(map, data = temp.loop.spdf, fillColor = ~temp.gary(eligibles_adj),group = "Loop")  
map <- addPolygons(map, data = temp.river.spdf, fillColor = ~temp.gary(eligibles_adj),group = "River North") 
```

Ideal Implementation: 

```r
map <- addPolygons(map, data = temp.loop.spdf, fillColor = ~temp.gary(eligibles_adj),layerId = "Loop")  
map <- addPolygons(map, data = temp.river.spdf, fillColor = ~temp.gary(eligibles_adj),layerId = "River North") 

createGroup(group_name = "All Locations", layerIds = c("Loop","River North")
createGroup(group_name = "Loop", layerIds = c("Loop")
createGroup(group_name = "River North", layerIds = c("River North")
```

Thanks for your assistance!

**Comment by safc** [comment]
[This documentation](https://rstudio.github.io/leaflet/showhide.html) might help you some. LayerIDs are meant for individual markers, not sets of markers. I ran into the same problem as you yesterday, and I'll let you know if I find a workaround!

**Comment by osh-chicago** [comment]
Thanks! Any luck?

**Comment by safc** [comment]
None yet!

**Comment by bhaskarvk** [comment]
You are confusing the use case for layerID. layerIDs are meant to be individual identifiers for markers and shapes (polygons/rectanges/circles). It has nothing to do with the concept of "grouping". You typically use layerID when you are in a Shiny app and want to know which marker/shape is being interacted with.
layerID are typically set using a formula over the spatial data that returns a unique identifier for each shape in the data. So something like `addPolygons(spdf, layerID=~id)`, where spdf is a spatialpolygonsDataFrame and `id` is a unique identifier for each polygon in it.

If I read your issue correctly what you are after is the ability to add shapes only once and have them part of more than one group ( w/o needing to add them more than once). This is not possible for a simple reason that the underlying JavaScript library doesn't support it. We could provide an abstraction in the R layer for something like what you want, but underneath it we will still have to do manually what you now have to do explicitly. Providing that wrapper will give the wrong impression that a layer is shared between multiple groups, while in reality it was just duplicated. So if you built shiny app with the assumption that your markers/shapes are shared then it will not work, as they are actually duplicated.

Hope that helps.

**Comment by osh-chicago** [comment]
@bhaskarvk - Once again, thanks for a great explanation!

**Comment by bhaskarvk** [comment]
Closing!
