### ISSUE TITLE
iconCreateFunction does NOT work when adding Markers with leafletProxy

### ISSUE THREAD

**Issue by behramkhan** [rstudio/leaflet#440]
https://stackoverflow.com/questions/43483696/iconcreatefunction-does-not-work-when-adding-markers-with-leafletproxy

**Comment by jellegrammens** [comment]
anybody knows a work-around for this? Facing the same issue.

**Comment by NilsOle** [comment]
For your knowledge. This seems to be in need for further clarification / how-to. Thanks! https://stackoverflow.com/questions/47922951/does-markercluster-work-together-with-leafletproxy-and-option-iconcreatefuncti

**Comment by miccou** [comment]
+1 also faced with this issue

**Comment by miccou** [comment]
I wanted to control the iconCreateFunction to remove the colour coding from markers, so instead of green/yellow/orange, they were all grey. 

I found I could achieve this CSS: 

```
.marker-cluster {
	background-color: rgba(12, 12, 12, 0.7) !important;
	color: black;
}

.marker-cluster div {
	background-color: rgba(255, 255, 255, 0.85) !important;
	color: black;
}
```

This is for styling only, but may help some people. I'd prefer to have more control over the function still.

**Comment by aavanesy** [comment]
Please update us on this.
