### ISSUE TITLE
Increase line length using spiderLegPolyline

### ISSUE THREAD

**Issue by dmaupin12** [rstudio/leaflet#447]
Is there a way to increase the length of the spiderLegPolyline in markerClusterOptions, similar to weight=1,2,3 etc? Currently, I'm unable to click on cirlcles listed above the circle cluster because the line is to short? 

Thanks!

**Comment by bhaskarvk** [comment]
Try passing `spiderfyDistanceMultiplier=x` where x is some number > 1 to `markerClusterOptions` function.

To see a list of all options that can be passed to the function refer to the original plugin's docs at https://github.com/Leaflet/Leaflet.markercluster/tree/leaflet-0.7. We only implemented the major options on the R side, but made the `markerClusterOptions` function flexible enough to accept any option the original plugin accepts.

Please close out the issue if this solves your problem.

**Comment by dmaupin12** [comment]
Excellent. Thanks for your help! I'll try it out.
