### ISSUE TITLE
addPolylines in RMarkdown

### ISSUE THREAD

**Issue by restonslacker** [rstudio/leaflet#45]
This is similar to issue #22 but I'm trying to work with lines instead of markers.

I have a number of tracks in a `data.frame` where the structure is (ttid, lng, lat).  Using the `points_to_lines` function from (https://rpubs.com/walkerke/points_to_line) I was able to convert it into a `SpatialLines` object and plot it with leaflet.  However when I try to embed it in an RMarkdown document, I get an error:

> Error in `[.data.frame`(x@data, i, j, ..., drop = FALSE) : 
>  undefined columns selected

This code run at the console in RStudio works (it produces two different lines)
```
tracks <- data.frame(ttid=c(rep("foo",3),rep("bar",3)), lng = c(1:3, 1:3), lat = c(rep(0, 3),rep(1,3)), stringsAsFactors = F)
lls <- points_to_line(tracks, "lng","lat", id_field = "ttid")
leaflet(lls) %>% addTiles() %>% addPolylines()
```

This example RMarkdown document does not work.  I did verify that your previous example from #22 does work on my system.

\---
output: html_document
runtime: shiny
\---

\```{r, echo=FALSE}
library(sp)
library(maptools)

points_to_line <- function(data, long, lat, id_field = NULL, sort_field = NULL) {
  
  # Convert to SpatialPointsDataFrame
  coordinates(data) <- c(long, lat)
  
  # If there is a sort field...
  if (!is.null(sort_field)) {
    if (!is.null(id_field)) {
      data <- data[order(data[[id_field]], data[[sort_field]]), ]
    } else {
      data <- data[order(data[[sort_field]]), ]
    }
  }
  
  # If there is only one path...
  if (is.null(id_field)) {   
    lines <- SpatialLines(list(Lines(list(Line(data)), "id")))    
    return(lines)    
    # Now, if we have multiple lines...
  } else if (!is.null(id_field)) {      
    # Split into a list by ID field
    paths <- split(data, data[[id_field]])    
    sp_lines <- SpatialLines(list(Lines(list(Line(paths[[1]])), "line1")))   
    # I like for loops, what can I say...
    for (p in 2:length(paths)) {
      id <- paste0("line", as.character(p))
      l <- SpatialLines(list(Lines(list(Line(paths[[p]])), id)))
      sp_lines <- spRbind(sp_lines, l)
    }    
    return(sp_lines)
  }
}
\```

\```{r}
library(leaflet)
library(shiny)

renderLeaflet({
  
  tracks <- data.frame(ttid=c(rep("foo",3),rep("bar",3)), lng = c(1:3, 1:3), lat = c(rep(0, 3),rep(1,3)), stringsAsFactors = F)
  lls <- points_to_line(tracks, "lng","lat", id_field = "ttid")
  leaflet(lls) %>% addTiles() %>% addPolylines()
})
\```

**Comment by ramhiser** [comment]
I was able to reproduce the error. The error is due to a namespace issue when splitting `data` into a list by `id_field`. Instead of `split`, call `sp::split` to use the expected `split` method. That is,

```r
paths <- sp::split(data, data[[id_field]])
```

**Comment by walkerke** [comment]
Glad to hear you've found my script useful!  Also thanks to @ramhiser for discovering the error; I notice this can happen with some `sp` functions in Shiny as in issue #39.  I'll update the RPubs so no one else runs into the same problem.

**Comment by restonslacker** [comment]
@walkedrke Yeah, your function was exactly what i was looking for; thanks for sharing it.  I wish i had found it 7 hours sooner.  I was surprised by the lack of out of the box support for data is this pretty basic format. 

@ramhiser Your correction works on my system with the original data.  Thank you for taking the time to track down the problem
