### ISSUE TITLE
Leaflet returns an error for empty "sf" "dataframe" objects

### ISSUE THREAD

**Issue by martinjhnhadley** [rstudio/leaflet#452]
Leaflet handles empty tibbles happily:

```r
library("tidyverse")
library("leaflet")

my_points <- tibble(
  lat = c(10,20,30),
  lon = c(20,40,50),
  labels = c("a", "b", "c")
)
## This generates a map
my_points %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers()

## So does this
my_points %>%
  filter(lat < 5) %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers()
```

However, an sf object containing zero observations (0 rows) returns an error without a leaflet object:

```r
library("sf")

my_sf <- my_points %>%
  st_as_sf(coords = c("lon", "lat"))

my_sf %>%
  filter(labels == "d") %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers()
## Error: is.matrix(x) || inherits(x, "XY") is not TRUE
```

**Comment by tim-salabim** [comment]
Are you sure this error is generated by leaflet? I think this is an error message from sf.

**Comment by martinjhnhadley** [comment]
Could well be. There's an issue here from sf for handling empty data frames for plot - https://github.com/r-spatial/sf/issues/436 but the sf library explicitly provides support for base R plotting, whereas you folks explicitly provide support in leaflet.

The package creator @edzer was responsible for fixing issue 436, I'll link these to issues together.

**Comment by edzer** [comment]
The error message seems to come from `leaflet:::sf_coords`; it assumes the outcome is a matrix, but `rbind`-ing the elements of an empty list doesn't give you that.

**Comment by jcheng5** [comment]
Thanks for the input, everyone. This should be all set, AFAICT.
