### ISSUE TITLE
Overwrite temp folder and/or use LiveReload technology

### ISSUE THREAD

**Issue by barryrowlingson** [rstudio/leaflet#46]
At the moment every time I make a leaflet map this way I get a new tab in my browser and probably a new set of temp files as well. While it might be nice to have all the old maps I made, most of them are wrong in some way and hence useless. 

If I could tell leaflet() to use the same temp dir then I could simply hit reload on my browser and get my new map version.

Even better than that would be to integrate a LiveReload server. This can be set to watch folders for file changes. A JS script in the web page listens for messages from that server (on port 35729) and reloads the page automatically. This does require one script tag in the HTML and for the user to run a LiveReload server (for which various options exist) watching the folder. 

I think LiveReload would enhance most R packages that produce HTML output graphics... Who likes hitting reload or closing loads of tabs?

**Comment by barryrowlingson** [comment]
A hacky way of doing these things is presented here for those who cannot wait:

https://gist.github.com/barryrowlingson/d066a7ace15cf119681a

**Comment by yihui** [comment]
I think I have addressed this problem a long while ago in the servr package: https://github.com/yihui/servr It is a general problem of htmlwidgets, not specific to leaflet. It can even be generalized to any dynamic HTML content generated from R.

What you can do is write `leaflet()` in an R Markdown (v2) document, and `servr::rmdv2()` or `servr::make()` (if you decide to use `make` to compile the document). The HTML page will be automatically refreshed as you save the Rmd document.
