### ISSUE TITLE
Advice - hyperlink to trigger setView

### ISSUE THREAD

**Issue by richardbeare** [rstudio/leaflet#460]
Hi,
I have a lot of markers and I'd like to be able to create a table of links that trigger zooms to a specific marker. Various stackoverflow comments (https://stackoverflow.com/questions/25340051/leaflet-zoom-onto-location-using-link-and-map-setview) suggest that it is possible with base leaflet, but I'd like to add this capability to pages currently generated from Rmd. I'm happy to handcraft some html and javascript, but don't know my way around js/leaflet to get started. 

I think I need to construct a link which triggers a call to setView, but don't know how to set up the names I need.

Any advice appreciated.

Thanks

**Comment by jcheng5** [comment]
Here's how you'd create a link (not in a code chunk, just directly in your markdown narrative):

```
[Label goes here](#){#zoomout}
```

where `zoomout` should be a unique ID for each link you make. Then, when you inject your leaflet map, add a call to `htmlwidgets::onRender` at the end. You'll use JS to set up a click handler for each link.

```{r echo=FALSE}
library(leaflet)
leaflet(quakes) %>% addTiles() %>% addMarkers() %>% 
  htmlwidgets::onRender('
    function(el, x) {
      var map = this;
      // A click handler for a link
      $(document).on("click", "#zoomout", function(e) {
        e.preventDefault();
        map.setView([0, 0], 0);
      });
      // Another one
      $(document).on("click", "#newyorkcity", function(e) {
        e.preventDefault();
        map.setView([40.7, -74], 10);
      });
    }
    ')
```

**Comment by richardbeare** [comment]
Thankw - that looks perfect!
