### ISSUE TITLE
Canvas renderer?

### ISSUE THREAD

**Issue by araichev** [rstudio/leaflet#463]
Hi folks,

Is there a way to use [Leaflet canvas rendering](http://leafletjs.com/reference-1.2.0.html#canvas)?  I have a big GeoJSON file i'd like to map, and using canvas instead of SVG would help.

**Comment by bhaskarvk** [comment]
We are not on leaflet js 1.x, we are still using leaflet js 0.7.7 and according to http://leafletjs.com/reference-0.7.7.html#path-canvas , canvas render of 0.7.x suffers from a performance bug. We are soon going to migrate to 1.x and we will add an option to the `leafletOptions` function to support canvas renderer.

**Comment by araichev** [comment]
Thanks for the information.

**Comment by cmcaine** [comment]
`leafletOptions(preferCanvas = TRUE)` works as expected in v2 but isn't documented. Is it still recommended against?

**Comment by schloerke** [comment]
@cmcaine I do not see any warnings in the latest leaflet.js documentation about canvas (http://leafletjs.com/reference-1.3.0.html#canvas) as I do in the [prior link](http://leafletjs.com/reference-0.7.7.html#path-canvas).
