### ISSUE TITLE
Using Leaflet plugins in Shiny

### ISSUE THREAD

**Issue by fhaidacher** [rstudio/leaflet#484]
I am trying to use one of the many Leaflet plugins available for Leaflet.
http://leafletjs.com/plugins.html

For example, if I use **heatmap.js**, I need to create an instance of it using javascript.
https://www.patrick-wied.at/static/heatmapjs/docs.html#h337-create

I have already included the javascript file in a **www** project folder.
https://stackoverflow.com/questions/23599268/include-a-javascript-file-in-shiny-app

I tried to make it work with **shinyjs**.
**runjs()** instructions do work in the server section.  **But the heatmap does not display.**

How can I find out what is still missing to make sure that ...
1. The **heatmap.js** library is loading and ...
2. That the **MapPlot1** leaflet object is being referenced as the designated DOMNode container?

Here is my code...

```
library(leaflet)
library(shiny)
library(shinyjs)
library(shinydashboard)
library(V8)

header1 <- dashboardHeader(title = "My Dashboard")

sidebar1 <- dashboardSidebar(
  sidebarMenu(
    fileInput("file0", "Choose CSV File",
              multiple = TRUE,
              accept = c("text/csv",
                         "text/comma-separated-values,text/plain",".csv"))
  )
)

body1 <- dashboardBody(
  fluidRow(
    useShinyjs(),
    tags$body(tags$script(src="heatmap.js")),
    box(title = "Box title", status = "primary", width = 10, 
        leafletOutput("MapPlot1", height = 450)
    )
  )
)

ui <- dashboardPage(header1, sidebar1, body1)

# Define SERVER logic

server <- function(input, output, session) {
  output$MapPlot1 <- renderLeaflet({
    leaflet() %>% 
      addProviderTiles("HikeBike.HikeBike") %>% 
      setView(lng = -90.54, lat = 14.61, zoom = 12)
  })
  #JS CODE HERE
  #runjs("var today = new Date(); alert(today);")  #this line runs OK if not commented
  
  # create configuration object
  jsCode <- "var config = {
  container: document.getElementById('MapPlot1'),
  radius: 10,
  maxOpacity: .5,
  minOpacity: 0,
  blur: .75
  };"
  runjs(jsCode)
  
  # create heatmap with configuration
  jsCode <- "var heatmapInstance = h337.create(config)"
  runjs(jsCode)
  
  # initialize heatmap instance
  jsCode <- "dataPoint = {
  x: -90.54,
  y: 14.61,
  value: 100
  };"
  runjs(jsCode)
  
  jsCode <- "var data = {
  max: 100,
  min: 0,
  data: [dataPoint]
  };"
  runjs(jsCode)
  
  jsCode <- "heatmapInstance.setData(data);"
  runjs(jsCode)
  
} #server

# Run app
shinyApp(ui, server)
```

Thank you for helping me out!  :)

**Comment by fhaidacher** [comment]
By the way, it should be
`tags$**body**(tags$script(src="heatmap.js"))`
instead of
`tags$**head**(tags$script(src="heatmap.js"))`
But it still does not work.

**Comment by fhaidacher** [comment]
I was using the wrong js library.  It should be leaflet-heatmap.js.

**Comment by jcheng5** [comment]
There are a couple of different leaflet heatmap plugins supported by https://github.com/bhaskarvk/leaflet.extras
