### ISSUE TITLE
addLegend and NA work but only with a workaround

### ISSUE THREAD

**Issue by Demetrio92** [rstudio/leaflet#485]
Providing `addLegend` with values in the fashion `values = df$variable` rather than `values =~variable` solves an occurrence of the error: 
```
Error in UseMethod("metaData") : 
  no applicable method for 'metaData' applied to an object of class "NULL"
```
which happens if `variable` has NA's.

I don't see why isn't this the default behaviour. 

source:
https://stackoverflow.com/a/32011289/3494126

p.s. for instance, just following [this official tutorial ](https://rstudio.github.io/leaflet/legends.html) with my data I produced the abovementioned error. 

-------------------------------------------------------------------------------------------------------------------------------

Ok, @jcheng5 thanks for the explanation, now I can produce a working/non-working example:

```R
library(leaflet)
library(sf)

N = 10
center = c(16.37, 48.21)  # Vienna approx center
random_event = list()
random_event$lat = rnorm(N, center[1], sd = 0.001)
random_event$lon = rnorm(N, center[2], sd = 0.001)
random_event = as.data.frame(random_event)
random_event = st_as_sf(random_event, coords = c('lat', 'lon'), crs = 4326)

random_event$random_intensity = rbinom(N, 5, 0.4)

pal = colorFactor('Greens', domain = random_event$random_intensity)

leaflet_plot = (

    leaflet() %>%
    addProviderTiles(leaflet::providers$CartoDB.Positron) %>%
    addCircles(
        data = random_event$geometry,
        weight = 2, opacity = 0.5, color = pal(random_event$random_intensity),
        radius = 5.5, fill = T
    )
    %>%
    addLegend('bottomright',
        pal = pal,
        # values = random_event$random_intensity,  # works fine
        values = ~random_intensity   # doesn't work
    )

)
print(leaflet_plot)
```

Indeed, the mistake here is using `leaflet() %>%` instead of `leaflet(random_event) %>%` which then works with both versions. 

----------------------------------------------------------------------------------------------------------

I still thing this is a minor bug. But feel free to disregard it. I will try to improve the SO issue, so that anyone who does the same in the future understands why it is not a bug. Although, with your explanation it is definitely more informative.

**Comment by jcheng5** [comment]
Can you provide a reproducible example that's giving you that error? The tutorial examples work for me (other than the fact that the data has moved to https://github.com/datasets/geo-boundaries-world-110m/raw/master/countries.geojson, which I hadn't noticed). Thanks.

**Comment by jcheng5** [comment]
Let me also note that this error basically means, "you used the formula syntax which implies you gave us some data--but I didn't find any data". I suspect the fact that you're seeing this with `addLegend` means your map doesn't have any data (i.e. you didn't pass any data to `leaflet()`), only a specific marker/shape layer was given data. (It looks like `addLegend` doesn't itself have an explicit data argument, which is probably an oversight.)

**Comment by Demetrio92** [comment]
**SOLUTION**: don't use 
```R
leaflet() %>% otherStuff() 
``` 
always provide it with the data (as intended), e.g.
```R
leaflet(my_data) %>% otherStuff() 
```

**Comment by fabiofernandez** [comment]
had that problem when using fillColor, and the way I solved it was using pal(...) instead of ~pal(...), not sure why though
