### ISSUE TITLE
convert language R (tcl tk) to the web application with shiny?

### ISSUE THREAD

**Issue by mariemhammami** [rstudio/leaflet#49]
hello everyone,
My name is Myriam and I live in tunisia
  currently doing my research paper for devolloper an application with language R and shiny framework for the first step I have some questions to help me move I have written class R & I'll tcl tk convert to shiny but I do not know how to do to convert so I really would like you to help me to solve this problem
and thank you in advance

**Comment by ramhiser** [comment]
Hi, @mariemhammami. The [Shiny Google group](https://groups.google.com/forum/#!forum/shiny-discuss) is the perfect place to ask this type of question. Might I also suggest that you construct a [reproducible example](http://adv-r.had.co.nz/Reproducibility.html) before posting in the Google group. Cheers!

**Comment by Make42** [comment]
Consider what we wrote in: https://github.com/rstudio/leaflet/issues/47

**Comment by mariemhammami** [comment]
okey  :) I'll see that and thank you for your answer @Make42  and @ramhiser
