### ISSUE TITLE
Error if leaflet is used after leafletR.

### ISSUE THREAD

**Issue by Make42** [rstudio/leaflet#50]
I wrote two little scripts: One for rstudio/leaflet one for leafletR (https://github.com/chgrl/leafletR).
If I execute the leaflet-script first and the leafletR-script second, everything works.
But if I execute the leafletR-script first and then the leaflet-script second I get the error

Error in browseURL(x, ...) : 'url' must be a non-empty character string

after

library(leaflet)
m = leaflet::leaflet()
m

How come? browseURL() is from the package utils. I tried to look into the code but did not find the use of browseURL(). What can I do to not get this error?

**Comment by yihui** [comment]
I think it is because both packages defined the `print.leaflet` method, and there are conflicts. That is the potential problem of the S3 system in R.

**Comment by Make42** [comment]
So I guess there is nothing that can be done?

How come that everything works if I choose to execute the leaflet-script first and the leafletR-script second?

**Comment by yihui** [comment]
It can be different when A overrides B, or B overrides A. We can probably fix it, but my question is do you really have to use the two packages together?

**Comment by Make42** [comment]
Probably not in production, but in testing - but of course I can work around that somehow.
