### ISSUE TITLE
v 2.0.0 addLabelOnlyMarkers has labels and markers

### ISSUE THREAD

**Issue by tim-salabim** [rstudio/leaflet#516]
Hi,
I'm currently testing version 2.0.0 and came across the following issue (used to work fine with 1.1.0.9000).

The `addLabelOnlyMarkers` function has the icon hardcoded [here](https://github.com/rstudio/leaflet/blob/a4d20dae1a612463134e6b3201bb06757213002f/R/layers.R#L672). 

I assume the markers should be hidden when `textOnly` is set to `TRUE` in the `labelOptions` but they are not.

```r
leaflet() %>%
  addTiles() %>%
  addLabelOnlyMarkers(
    data = breweries91,
    label = as.character(breweries91$brewery),
    group = "brew",
    labelOptions = leaflet::labelOptions(
      noHide = TRUE,
      direction = "bottom",
      textOnly = TRUE,
      offset = c(0, -10),
      opacity = 1
    )
  )

```

**Comment by MatthiasHinz** [comment]
Oh, good! I came across the same issue and also wanted to submit it.

I can confirm that LabelOnlyMarkers are currently not "label only". The default marker always appears, although it should never do, independent of which parameters are set in the labelOptions.

**Comment by schloerke** [comment]
Fixed. 

Thank you @tim-salabim and @MatthiasHinz.  If you run across any more issues, please let me know!  

\- Barret

**Comment by tim-salabim** [comment]
Thanks! Will do

**Comment by jawadkeshawarz** [comment]
is it possible to customize the label font color?

**Comment by jay-sf** [comment]
@jawadkeshawarz Use JavaScript language, `addLabelOnlyMarkers(..., labelOptions=labelOptions(..., style=list('color'="#888888", 'fontSize'="25px")))`
