### ISSUE TITLE
popups don't close on click anymore

### ISSUE THREAD

**Issue by tim-salabim** [rstudio/leaflet#519]
Hi,
more testing with 2.0.0 reveals that popups are not closed when clicking the same location for the second time (anywhere else on the map closes the popup or opens another one). This used to be the default behaviour and I have come to like it. Thus, I would like to keep this behaviour in mapview, however, I cannot figure out how to manipulate `popupOptions` to bring it back.

Am I missing something obvious?

```r
library(leaflet)

leaflet() %>%
  addTiles() %>%
  addPolygons(data = gadmCHE, 
              popup = ~NAME_1)

leaflet(options = leafletOptions(closePopupOnClick = TRUE)) %>%
  addTiles() %>%
  addPolygons(data = gadmCHE, 
              popup = ~NAME_1,
              popupOptions = popupOptions(closeOnClick = TRUE))
```

**Comment by schloerke** [comment]
Ha! Found it! https://github.com/Leaflet/Leaflet/pull/4599
... that took way too long. Who disables pointer-events?!?

I have it overwritten in a PR. Will reference shortly
