### ISSUE TITLE
Lazy loading fails

### ISSUE THREAD

**Issue by enadol** [rstudio/leaflet#532]
The process of installing the latest update crashes as follows:

* installing *source* package 'leaflet' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'shiny', details:
  call: .Call("_httpuv_getRNGState", PACKAGE = "httpuv")
  error: '_httpuv_getRNGState' ist nicht verfügbar für .Call() aus Paket "httpuv"
ERROR: lazy loading failed for package 'leaflet'
* removing 'C:/Users/Enrique Lopez/Documents/R/win-library/3.3/leaflet'
Installation failed: Command failed (1)

**Comment by schloerke** [comment]
Please remove and then reinstall shiny and httpuv. Then restart your R
session.

Does this correct the error?

- Barret

**Comment by enadol** [comment]
Thank's! I did that, but still no change.

---------------------------------------------

install.packages("leaflet")
Installing package into ‘C:/Users/Enrique Lopez/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
leaflet  1.1.0  2.0.0             FALSE

installing the source package ‘leaflet’

trying URL 'https://cran.rstudio.com/src/contrib/leaflet_2.0.0.tar.gz'
Content type 'application/x-gzip' length 2056931 bytes (2.0 MB)
downloaded 2.0 MB

* installing *source* package 'leaflet' ...
** Paket 'leaflet' erfolgreich entpackt und MD5 Summen überprüft
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'shiny', details:
  call: .Call("_httpuv_getRNGState", PACKAGE = "httpuv")
  error: '_httpuv_getRNGState' ist nicht verfügbar für .Call() aus Paket "httpuv"
ERROR: lazy loading failed for package 'leaflet'
* removing 'C:/Users/Enrique Lopez/Documents/R/win-library/3.3/leaflet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Enrique Lopez\Documents\R\win-library\3.3" C:\Users\ENRIQU~1\AppData\Local\Temp\RtmponeKSB/downloaded_packages/leaflet_2.0.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘leaflet’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Enrique Lopez\AppData\Local\Temp\RtmponeKSB\downloaded_packages’

**Comment by schloerke** [comment]
@enadol Could you copy paste the output of this code, please?  This code should produce a leaflet world map.  If there are install errors, it should be isolated to this example.  Thank you!
\- Barret

```r
if (!require("reprex")) install.packages("reprex")
reprex::reprex({
  .libPaths(tempdir())

  install.packages("httpuv")
  install.packages("shiny")
  install.packages("leaflet")
  library(leaflet)
  leaflet() %>% addTiles()
})
```

From a similar error within httpuv: https://github.com/rstudio/shiny/issues/2030

**Comment by enadol** [comment]
Ok, good news. I tried your first solution and it works, finally. As per the above code, it outputs:

Error in reprex_(r_file) : 
Cannot render this code.
Error : Functions that produce HTML output found in document targeting markdown_github output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: yes

Note however that the HTML output will not be visible in non-HTML formats.

**Comment by schloerke** [comment]
Glad it works now. 

Closing as it's more of an httpuv issue.
