### ISSUE TITLE
Rendering of Flex Dashboard with leaflet map fails with pandoc

### ISSUE THREAD

**Issue by jenslaufer** [rstudio/leaflet#558]
I am having a flexdashboard with a leaflet map. Everything works fine in RStudio, but rendering the dashboard with pandoc on a docker container with R and pandoc fails with:

`
pandoc: Could not find data file /usr/local/lib/R/site-library/leaflet/htmlwidgets/lib/leaflet/
Error: pandoc document conversion failed with error 97
`

The folder exists and is not empty
`root@907c1a62f948:/development# ls //usr/local/lib/R/site-library/leaflet/htmlwidgets/lib/leaflet/
images  leaflet.css  leaflet.js`

![Screenshot](https://user-images.githubusercontent.com/2699798/41279730-8f3695a6-6e2d-11e8-8b59-7b86b5839361.png)

Any ideas what the problem might be?

I have tried it also with leaflet example code. So it's not an issue of my R code.

**Comment by schloerke** [comment]
With everything working in your local environment, I am leaning towards docker not having the correct permissions to view the folder.   Past (limited) experience tells me that docker images are fairly locked down by default.

Can the docker see that folder location?  Might need to share your /usr/local with your docker's /usr/local ([Maybe helpful link](https://linuxconfig.org/how-to-share-data-between-a-docker-container-and-host-system-using-volumes))

**Comment by jenslaufer** [comment]
Barret,
thanks. It's actually a folder within the container. I also thought it's a permisson problem and even "assigned" chmod 777 to the folder. Strange that pandoc doesn't see it....

**Comment by jenslaufer** [comment]
I fixed the problem the other day. There was an old version of pandoc running in the docker container. Upgrading to the newest version fixed the proble,.

**Comment by schloerke** [comment]
Thank you for the followup! (Closing issue)
