### ISSUE TITLE
Animated points/markers using mapbox for leaflet

### ISSUE THREAD

**Issue by hmaeda** [rstudio/leaflet#56]
Hi,

I was wondering is it possible to have a feature request to add animation capability to the leaflet maps as suggested in this example [here](http://zevross.com/blog/2014/09/30/use-the-amazing-d3-library-to-animate-a-path-on-a-leaflet-map/)

I believe it uses something called [mapbox](https://www.mapbox.com/mapbox.js/example/v1.0.0/animate-marker-along-line/).

**Comment by yihui** [comment]
Thanks for the example. It looks pretty cool. Currently it does not seem to be possible using this package (unless you write a ton of JavaScript), but I guess it might be possible after we complete the Shiny support, or if any [Leaflet plugins](http://leafletjs.com/plugins.html) can do it (we will work on plugins as well).

**Comment by jcheng5** [comment]
Possible now using Shiny (leafletProxy + invalidateLater, inside an observer)
