### ISSUE TITLE
Popups closing unexpectedly on version 2.0.0

### ISSUE THREAD

**Issue by alvaroclementev** [rstudio/leaflet#565]
I have a simple leaflet map in which i show some markers. I am using a function to show some information in a popup when a user clicks on the marker. I want users to be able to compare data from 2 markers, so I want to have multiple popups open at the same time.

The code I am using for this is the following

``` r
showCityPopup <- function(city.name, lat, lng) {
    city <- capitales[city.name, ]
    content <- createCityPopupHTML(city)
    
    leafletProxy("map") %>% addPopups(lat = lat, lng = lng, content, layerId = row.names(city))
  }
  
  
  observeEvent(input$map_marker_click, {
    event <- input$map_marker_click
    if(is.null(event))
      return()
    
    showCityPopup(event$id, event$lat, event$lng)
  })
```
Created on 2018-06-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Under leaflet version 1.1.0, this works just fine. But under leaflet version 2.0.0, this code closes automatically the popup when clicking on any other marker.

**Comment by tim-salabim** [comment]
You need to set some `popupOptions`, namely `autoClose = FALSE` and `closeOnClick = FALSE`:

```r
leaflet() %>%
  addTiles() %>%
  addMarkers(data = breweries91, popup = ~address,
             popupOptions = popupOptions(autoClose = FALSE,
                                         closeOnClick = FALSE))
```
As you do not provide a reproducible example, I cannot test whether this also works in your apps `showCityPopup` function.

**Comment by alvaroclementev** [comment]
That was it! The defaults for those options must've changed between versions.
Now the code that updates the map and creates the popups looks like this.
``` r
leafletProxy("map") %>% 
    addPopups(lat = lat, lng = lng, content, 
                       layerId = row.names(city),
                       options = popupOptions(autoClose = FALSE, closeOnClick = FALSE))
```

Thank you!
