### ISSUE TITLE
scales 1.0.0 change to colour_ramp to cause test failure

### ISSUE THREAD

**Issue by dpseidel** [rstudio/leaflet#570]
The upcoming scales 1.0.0 release has a minor change to the default settings and output of the `scales::colour_ramp()` function, introduced by r-lib/scales#109. This change sets the default `alpha = TRUE` and changes the output so that fully opaque colors are returned in  `"#RRGGBB"` format.

During our revdep checks, it seems that this change breaks a colors test for `leaflet`, speficifically the test starting at [L39 in the test-colors.r file](https://github.com/rstudio/leaflet/blob/eaee4d55ff59e6885ac6559778633cec57d0729a/tests/testit/test-colors.R#L39)

The error output is below:

```
Error from assert(identical(c("#000000", "#7F7F7F", "#FFFFFF"), colorNumeric(colorRamp(bw),  ...  at test-colors.R#34 
Error: identical(c("#000000FF", "#777777FF", "#FFFFFFFF", "#FFFFFF00", "blue"), colorNumeric(c(bw, "#FFFFFF00"),  ....  is not TRUE
Execution halted
```
Just wanted to give the maintainers a heads up. We expect to release shortly but don't expect this to be a breaking change to plots. Let me know if I can offer more clarity about the change.

**Comment by schloerke** [comment]
@dpseidel Thank you heads up!  

I'd like to challenge their code change though as to why an alpha value of `FF` is required in the string.  Seems redundant when the alpha value is not changing.

**Comment by dpseidel** [comment]
On the scales end, it no longer is returned. 

```{r}
library(leaflet)
bw <- c("black", "white")

# current test, failing with scales 1.0.0
identical(
  c("#000000FF", "#777777FF", "#FFFFFFFF", "#FFFFFF00", "blue"),
  colorNumeric(c(bw, "#FFFFFF00"), NULL, na.color = "blue", alpha = TRUE)(c(0, 0.25, 0.5, 1, NA))
)
#> [1] FALSE

# scales 0.5.0 behaviour
colorNumeric(c(bw, "#FFFFFF00"), NULL, na.color = "blue", alpha = TRUE)(c(0, 0.25, 0.5, 1, NA))
#> [1] "#000000FF"   "#777777FF"   "#FFFFFFFF"   "#FFFFFF00" "blue" 

# scales 1.0.0 bebaviour
colorNumeric(c(bw, "#FFFFFF00"), NULL, na.color = "blue", alpha = TRUE)(c(0, 0.25, 0.5, 1, NA))
#> [1] "#000000"   "#777777"   "#FFFFFF"   "#FFFFFF00" "blue" 

# an updated test, passing
identical(
  c("#000000", "#777777", "#FFFFFF", "#FFFFFF00", "blue"),
  colorNumeric(c(bw, "#FFFFFF00"), NULL, na.color = "blue", alpha = TRUE)(c(0, 0.25, 0.5, 1, NA))
)
#> [1] TRUE
```
