### ISSUE TITLE
leaflet crashing session without warning

### ISSUE THREAD

**Issue by Cristichu** [rstudio/leaflet#572]
I've been trying to make a map using leaflet and a shapefile. Once I reach the addPolygons function and the map starts to render in the Viewer it suddenly closes the session without a warning or explanation. It also doesn't save the environment or the history so I have to load all the libraries and run the whole code over and over to find that it closes it after rendering the map. I've been looking online but no one seems to have an answer to this problem. Thanks in advance!

Here is the code: 
```r
# libraries 
library(raster)
library(leaflet)
require(magrittr)
library(rgdal)
library(GISTools)

# dataset
llanos <- shapefile("SG_SIMD_2016.shp")

# making sure the coordinates are the correct ones
shapeData <- spTransform(llanos, CRS("+proj=longlat +datum=WGS84 +no_defs"))

# giving the color for the polygons
pal <- colorFactor(palette = "Blues", domain = shapeData@data$Rank)

# mapping
map <- leaflet(shapeData)
map %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~pal(Rank))

# in the end the session closes itself with no warning or error and everything is lost. 
```

**Comment by tim-salabim** [comment]
How big is your shapefile? I.e. how many polygons do you want to render? 
For large shapefiles it may help to tell leaflet to render things on the canvas:
```r
map = leaflet(shapeData, options = leafletOptions(preferCanvas = TRUE))
```
If that does not help, it may help to simplify your geometries using the **rmapshaper** package before generating the map.

**Comment by Cristichu** [comment]
Quite big, I have a feeling it has to do with that as it takes quite a lot of time to load. I have almost 7000 observations, 86MB. I'm trying to reduce this using maptools and shapefiles at the moment but I'll look into rmapshaper. 
I've tried that command but the viewer is grey with the zoom buttons only so back to square one unfortunately. I'll keep searching for an answer, thanks in either case.

**Comment by schloerke** [comment]
It is possible to share your shape file? (Maybe a public github repo containing `code.R` and `SG_SIMD_2016.shp`?) This would help me reproduce your setup.

**Comment by Cristichu** [comment]
@schloerke yeah, it was the shapefile that for some reason it was messing up with leaflet. I managed to get a GeoJSON file and I got to the point of having the boundaries of Scotland. Now my problem has moved to the addPolygon function which doesn't work, it fills everything black but that's another story. 
Thank you in either case!

**Comment by schloerke** [comment]
Glad you're able to move forward.  

I'd also check out `rmapshaper::ms_simplify`.  This should be able to reduce your shape file to not contain as much detail, making it more attainable within the browser.  It should have similar effect as Bostocks line simplification demo: https://bost.ocks.org/mike/simplify/

(closing issue for now)

**Comment by michellepepping** [comment]
I've experienced this before and found that it happened with data sets that had an apostrophe before the latitude and longitude values. Example  
Lat                Long 
'43.290127 | '-122.619747

change to 

43.290127 | -122.619747
