### ISSUE TITLE
choropleth + points on shape

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/leaflet#58]
Is possible (or will it be possible with the new design) to display at the same time on the same map:

- points on a layer as circle of different size or pop-ups (possibly with different icons), 
- polygons from a choropleth (of course using a low opacity in order not to obscure the pop-ups

In case, is there an example of it?

**Comment by jcheng5** [comment]
You can just call `addCircles` or `addCircleMarkers`, and then call `addPolygons` on the same object.

```r
leaflet(data) %>% addCircles(...) %>% addPolygons(...)
```
