### ISSUE TITLE
setVIew() not working for alternative Projection

### ISSUE THREAD

**Issue by Jellest** [rstudio/leaflet#582]
Using the ESPG:28992 projection (RD New) I try to make a custom basemap. With success I retrieve the tiles for each zoom layer (zoom levels work). Setting the view with `setview()`does not work however. Whatever I do, I always end up having the center point somewhere in the gray area as shown in the picture below. I have tried with both RD New and WGS84 coordinates (lng, lat). I have also played around with `setMaxBounds()` and the origin argument. 

Anyone any idea what is going on?

```r
library(leaflet)
resolutions <- c(3440.640, 1720.320, 860.160, 430.080, 215.040, 107.520, 53.760, 26.880, 13.440, 6.720, 3.360, 1.680, 0.840, 0.420)

minZoom <- 1
maxZoom <- 13
epsg28992 <- leafletCRS(crsClass = 'L.Proj.CRS', code = 'EPSG:28992',
                        proj4def = '+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs',
                        resolutions = resolutions
                        , bounds = c(-285401.92, 22598.08, 595401.9199999999, 903401.9199999999)
                        #, origin = C(0,0),#origin = c(7.1389803, 48.1833305)
                        ) 
leaflet(options = leafletOptions(
  crs = epsg28992
  , minZoom = minZoom, maxZoom = maxZoom)) %>%
  setView(5.18000, 52.10000, zoom = 2) %>% #RD new ccords: 140802.7, 456881.8
  addTiles('http://geodata.nationaalgeoregister.nl/wmts/?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=brtachtergrondkaart&TILEMATRIXSET=EPSG:28992&TILEMATRIX=EPSG:28992:{z}&TILEROW={y}&TILECOL={x}&FORMAT=image/png')
```
![image](https://user-images.githubusercontent.com/6051312/44846607-1c2f7200-ac51-11e8-8493-2a41a75ab67b.png)

**Comment by Jellest** [comment]
using the mapview package I have added mouse coordinates  trhough `addMouseCoordinates()` after which I figured the correct lat lng coordinate to use as input values.

**Comment by schloerke** [comment]
Thank you for following up @Jellest !
