### ISSUE TITLE
Update leaflet-omnivore st version to > 1.1.0

### ISSUE THREAD

**Issue by philmikejones** [rstudio/leaflet#585]
When deploying a leaflet map through github pages, I am informed about a network vulnerability in the [`st`](https://github.com/isaacs/st) package when using the `leaflet-omnivore` plugin.

I think the offending file is: https://github.com/rstudio/leaflet/blob/master/inst/htmlwidgets/lib/leaflet-omnivore/package.json

Please could you update the version of st used? I'm not sure if it's just a case of updating the reference in that file.
Thanks.

**Comment by philmikejones** [comment]
Thanks, I thought it would be something like that. Thanks for looking into it

**Comment by schloerke** [comment]
Closing as it looks like leaflet-omnivore is a ghost town.  #575 fixed the issue
