### ISSUE TITLE
Nautical Miles in addMeasure()

### ISSUE THREAD

**Issue by pythiantech** [rstudio/leaflet#586]
Is there any plan to add Nautical Miles as one of the primary length units in `addMeasure()`? Would be super useful for maritime applications.

**Comment by schloerke** [comment]
Hi @pythiantech 

leaflet R package currently uses the github.com/ljagis/leaflet-measure repo plugin for leaflet.js.  I'm going to redirect your issue there.  

Once adopted, ping this thread again, we'll reopen the issue and merge in the latest for the plugin.

Forwarding your issue to the leaflet-measure repo. https://github.com/ljagis/leaflet-measure/issues/126

Thank you,
Barret
