### ISSUE TITLE
Put color functions into a separate package

### ISSUE THREAD

**Issue by markusdumke** [rstudio/leaflet#611]
Hi,

 I am using the `color*` functions in one of my packages, therefore I have to list `leaflet` in Imports, which adds other dependencies like `shiny`. From a minimal dependency point of view it would be nice if the `color*` functions could be extracted into a separate package with less dependencies, so I could use this as a dependency for my package. I think these functions are useful on their own. 

What do you think?

**Comment by jcheng5** [comment]
You can use them from the scales package as well (they are named with a col_ prefix but otherwise the same).
