### ISSUE TITLE
Cannot display tiles locally or via GitHub

### ISSUE THREAD

**Issue by simon-tarr** [rstudio/leaflet#619]
Hello, I cannot seem to display tiles uploaded to a GitHub repo either within R Studio's Viewer or using my browser (latest version of Chrome). I created some tiles using [gdal2tiles.py](https://www.gdal.org/gdal2tiles.html). The script creates the tiles successfully and, if I view the script-generated .html files within the directory, the tiles display correctly.  However, I can't get the tiles to load using `leaflet`. I have been using [this](https://rpubs.com/walkerke/custom_tiles) tutorial to guide me. I can successfully display the 'snow' tiles at in the previous link if I copy this person's code (in a browser, not R Studio's Viewer) but cannot for the life of me get my own example to work.

I used the following code to generate my own tiles (projected in British National Grid):
`gdal2tiles.py -s EPSG:27700 -z 6 england_ancient_forest_25m.tif forest_6`

I have created a test data set of tiles at a single zoom level (6), so that I can quickly create a reproducible example. The tiles can be found [here](https://github.com/simon-tarr/tilestest).

I am using the following code:
```

library(leaflet)
library(rgdal)
library(leaflet.extras)
library(mapview)

leaflet() %>%
  addMouseCoordinates() %>%
  
# Set high zoom level as I have only created tiles at zoom level 6 for a quick example. If you can get this to display, it'll be tough to discern as it's quite zoomed out!

# This should center the view somewhere over the UK where my tiles have been created  
setView(0, 51.5135085, zoom = 6) %>%
# Added toner provider tiles as the white background makes it easier to see my custom tiles
 addProviderTiles(group = "Toner", providers$Stamen.Toner) %>% 
  addTiles(group="test", urlTemplate = "https://simon-tarr.github.io/tilestest/tiles/{z}/{x}/{y}.png",
           options = tileOptions(minZoom = 6, maxZoom = 6)) %>% 
    addLayersControl(
      overlayGroups = c("test"),
      options = layersControlOptions(collapsed = FALSE)
      
    )

```
Here is my `sessionInfo()`:
```

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.6.3        leaflet.extras_1.0.0 rgdal_1.4-3          sp_1.3-1             leaflet_2.0.2       

loaded via a namespace (and not attached):
 [1] remotes_2.0.4     sf_0.7-3          lattice_0.20-38   colorspace_1.4-1  usethis_1.5.0     htmltools_0.3.6   stats4_3.5.3      viridisLite_0.3.0
 [9] yaml_2.2.0        base64enc_0.1-3   rlang_0.3.4       pkgbuild_1.0.3    e1071_1.7-1       later_0.8.0       glue_1.3.1        withr_2.1.2      
[17] DBI_1.0.0         sessioninfo_1.1.1 munsell_0.5.0     raster_2.8-19     htmlwidgets_1.3   devtools_2.0.2    codetools_0.2-16  memoise_1.1.0    
[25] callr_3.2.0       httpuv_1.5.1      ps_1.3.0          crosstalk_1.0.0   curl_3.3          class_7.3-15      Rcpp_1.0.1        xtable_1.8-4     
[33] promises_1.0.1    scales_1.0.0      backports_1.1.4   classInt_0.3-1    satellite_1.0.1   desc_1.2.0        pkgload_1.0.2     webshot_0.5.1    
[41] jsonlite_1.6      fs_1.2.7          mime_0.6          png_0.1-7         digest_0.6.18     processx_3.3.0    shiny_1.3.2       grid_3.5.3       
[49] rprojroot_1.3-2   cli_1.1.0         tools_3.5.3       magrittr_1.5      crayon_1.3.4      prettyunits_1.0.2 assertthat_0.2.1  rstudioapi_0.10  
[57] R6_2.4.0          units_0.6-2       compiler_3.5.3   
```
I am using R Studio version 1.2.1335.

I have previously posted to StackOverflow [here](https://stackoverflow.com/questions/55845122/rendering-large-tile-dataset) in an attempt to just get the tiles to load locally but didn't receive a response.

I'd love to be able to display my custom tiles both locally (for development) and using GitHub to serve the images when I push my `leaflet` application onto the web.

Hoping someone can help me! Cheers.

**Comment by simon-tarr** [comment]
Quick update. I've since turned the repo to a GitHub pages repo and pushed the tiles again. If you navigate to [https://simon-tarr.github.io/tilestest/tiles/6/31/42.png](https://simon-tarr.github.io/tilestest/tiles/6/31/42.png) you will see that the tiles are no accessible via a URL. However, the above code is still not loading the tiles in either R Studio's Viewer or on Chrome.

**Comment by schloerke** [comment]
@simon-tarr I believe we need to add `tms = TRUE` for the `tileOptions` in `addTiles` call. 🤷‍♂ 

Stab in the dark insight: https://github.com/simon-tarr/tilestest/blob/e86557c9c0c0985bc6a74488849359184ba3fddf/tiles/leaflet.html#L56

Output:
![Screen Shot 2019-05-07 at 9 34 21 AM](https://user-images.githubusercontent.com/93231/57303460-5c31d900-70ab-11e9-9fd8-0ffb37308165.png)


Final code:
```r

library(leaflet)
library(rgdal)
library(leaflet.extras)
library(mapview)

leaflet() %>%
  addMouseCoordinates() %>%
  
  # Set high zoom level as I have only created tiles at zoom level 6 for a quick example. If you can get this to display, it'll be tough to discern as it's quite zoomed out!
  
  # This should center the view somewhere over the UK where my tiles have been created  
  setView(0, 51.5135085, zoom = 6) %>%
  # Added toner provider tiles as the white background makes it easier to see my custom tiles
  addProviderTiles(group = "Toner", providers$Stamen.Toner) %>%
  addTiles(group="test", urlTemplate = "https://simon-tarr.github.io/tilestest/tiles/{z}/{x}/{y}.png",
           options = tileOptions(tms = TRUE, minZoom = 6, maxZoom = 6)) %>% 
  addLayersControl(
    overlayGroups = c("test"),
    options = layersControlOptions(collapsed = FALSE)
    
  )
```

**Comment by simon-tarr** [comment]
Hi @schloerke thank you for replying. I can confirm that setting `tms=TRUE` has indeed fixed the issue - very pleased to have this resolved! I don't fully understand what the TMS flag does but I'm glad it has resolved the issue.

**Comment by tim-salabim** [comment]
TMS is an OSGeo specification for map tiles. That is why `gdal2tiles.py` adheres to that format. XYZ on the other hand is widely used by pretty much all web map tile providers usually used to display leaflet basemaps. That, I guess, is the reason why leaflet has it as default. The difference between the two is actually minor, a flipped y-axis. 

Some more info can be found here:
https://gist.github.com/tmcw/4954720
with some links provided to wiki pages and other resources explaining things in more detail.

In case it helps, I am currently working on an add-on function for R leaflet that let's you spceify the path to the top level folder of your tile pyramid. Probably not that useful, but we use that in `mapview` which will then figure out the appropriate zoom levels and map bounds based on the folder structure. 

https://github.com/r-spatial/leafem/blob/master/R/file.R#L152

NOTE that this currently only works for an interactive R session.
