### ISSUE TITLE
FR: format of addLegend entries

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/leaflet#62]
I had a play with the new legend added by @yihui - great work!.

I am using it to display unemployment % over population. I use colorBin to bin the unemployment percentages.
On the other hand the legend displays my percentages as absolute values.

It would be nice to be able to have a way to format the legend entries, as an option.

**Comment by jebyrnes** [comment]
Out of curiosity, can you include a reproducible example of the addLegend function at work?

**Comment by smartinsightsfromdata** [comment]
I plan to create a "complete" [tutorial on how to create choropleths in R](http://smartinsightsfromdata.github.io//2015/04/25/choropleths.html), based mainly on the leaflet package, covering spatial re-projections and geometry simplifications etc.

At the moment I've developed 4 parts. The addLegend example is in Part 4, inspired by @yihui . 

I will add more parts as soon as the new functionalities in the pipeline will be made available.

Let me know what you think.

**Comment by jcheng5** [comment]
Hi Enzo, the tutorial looks great! 

Can you give an example of what you want your formatted text to look like?

**Comment by jebyrnes** [comment]
FYI - whipped up a quick example here https://gist.github.com/jebyrnes/bb0a37b376757938c003

**Comment by jread-usgs** [comment]
`cols` is missing from gist @jebyrnes, but looks great and helpful.

**Comment by smartinsightsfromdata** [comment]
@jcheng5 thanks!
![rplot](https://cloud.githubusercontent.com/assets/3786727/7333547/eb582df2-eb6a-11e4-9c20-5c179bc5dd8a.png)

I would like to have:
0% - 2%
2% - 4%
etc.
I cannot use the `quantile` function (in `colorQuantile`) as unemployment is usually in ranges from 0 to around 12% (as in this real life example).

**Comment by yihui** [comment]
@smartinsightsfromdata I just [added](https://github.com/rstudio/leaflet/commit/7b34cd2477df1e7515022c0e52a500c295a6798a) a new argument `labelFormat` in `addLegend()` so you can format the labels with your own function. Please install the `feature/color-legend` branch if you want to test it out. I have provided a simple example in `?addLegend`.
