### ISSUE TITLE
addGeoJSON() fails to render valid geometries

### ISSUE THREAD

**Issue by aoles** [rstudio/leaflet#622]
Hi,

it seems that geoJSON geometry primitives such as `"Point"` or  `"Polygon"` are not displayed by `addGeoJSON()`. I would expect them to be valid input as according to the [specification](https://tools.ietf.org/html/rfc7946#section-3) and to `geojsonlint::geojson_validate()` they conform to the standard.

Cheers,
Andrzej

``` r
library(leaflet)
library(jsonlite)
library(geojsonlint)

polygon = list(
  type = "Polygon",
  coordinates = list(
    list(
      c(8.330469, 48.261570),
      c(8.339052, 48.261570),
      c(8.339052, 48.258227),
      c(8.330469, 48.258227),
      c(8.330469, 48.261570)
    )
  )
)

geojson_validate(toJSON(polygon, auto_unbox = TRUE))
#> [1] TRUE

leaflet() %>%
  addTiles() %>%
  addGeoJSON(polygon, color="#F00") %>%
  setView(lng = 8.330469, lat = 48.26157, zoom = 15)
```

![](https://i.imgur.com/RDn8AZi.png)

``` r

feature <- list(
  type = "Feature",
  properties = "",
  geometry = polygon
)

leaflet() %>%
  addTiles() %>%
  addGeoJSON(feature, color="#F00") %>%
  setView(lng = 8.330469, lat = 48.26157, zoom = 15)
```

![](https://i.imgur.com/C8eBBJS.png)

<sup>Created on 2019-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by schloerke** [comment]
This line is causing the issue: https://github.com/rstudio/leaflet/blob/44df7d18a2618e0aeecb4145d765e597ec65878b/javascript/src/methods.js#L594

**Comment by schloerke** [comment]
Check to make sure `properties` is not undefined.  Or use `extraInfo` object `properties`

**Comment by jcheng5** [comment]
Thanks, @aoles! Just one nit with this example: `properties = ""` isn't valid GeoJSON, that should either be `null` or `{}`. (But I think the PR is fine despite this, since both `""` and `null` are falsy)
