### ISSUE TITLE
How many bins in colorBin?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/leaflet#63]
I'm working with the feature/color-legend branch.
I use colorBin with unemployment data. This is the code:
```R
colorBin('YlOrRd', leedsShape@data$Unemployed_, bins= 5 ,na.color = "#808080")
...
attr(,"colorArgs")$bins
[1]  0  2  4  6  8 10 12 14
```
If I use `bins=5`  I get 8 bins.  I get 8 bins with `bins=6` all the way to  `bins=8`.
`bins=9`  gives 13!  (the 'YlOrRd' palette gets up to 9 colours).

If I use `bins=4` I get four bins:
```R
colorBin('YlOrRd', leedsShape@data$Unemployed_, bins= 4 ,na.color = "#808080")
...
attr(,"colorArgs")$bins
[1]  0  5 10 15 
```
As ` leedsShape@data$Unemployed_,` is the vector with the actual data (including NA) I've tried to give the domain as a range ( `0:12.83` or `c(0, 12.83`).

Using `domain= c(0,12.83)`:
If I use `bins=4` I get four bins.  I get 8 bins with `bins=6` all the way to  `bins=8`.
Using `domain= 0:12.83`:
If I use `bins=4` I get four bins.  I get 7 bins with `bins=6` all the way to  `bins=8`.

**Comment by yihui** [comment]
`colorBin()` is based on `pretty()`, and the price of making bins "pretty" is that it is you are unlikely to get exactly n bins. If you want to get exactly n bins, the cut points will not be "pretty" (e.g. numbers with 16 digits after the decimal point).

**Comment by smartinsightsfromdata** [comment]
@yihui great to know, but...

I think we should clearly spilt the problem in two:
- how many bins do I want to use? I must be able to specify the number of bins I want to use, either using `colorBin` (or `colorFactor`). If `colorBin` (or `pretty()`) decides for me how many bins is using, it is not (much) useful.
- what is the format of the data in the legend? On the legend data format issue I've already posted a feature request [here](https://github.com/rstudio/leaflet/issues/62). This discussion reinforces the need to address legend data formatting (maybe using the scale package?).

Suppose that I've used a not-pretty number of bins (e.g. with lots of decimals).  I wouldn't see a problem if the legend data is just **approximate**: I would use a popup to display the actual value in each area to clarify any ambiguity.  What would it matter to know **precisely** where the cut occurred? In most cases it wouldn't.

For me, a legend of a choropleth map needs to give an idea at a glance of the order of magnitude of the areas, especially if there is an easy way to get the actual detail (e.g. popup).

In any case, may I suggest to mention in the help that the number of bins are forced by `pretty()`?

At the moment it says only:
```
colorBin also maps continuous numeric data, but performs binning based on value (see the cut function).
```

Thanks

**Comment by smartinsightsfromdata** [comment]
@yihui As a way to extend the ability to define different binning approached, I suggest to integrate the package ‘classInt’ by Roger Bivand.

**Comment by yihui** [comment]
Thanks! I have addressed the documentation in #53, in which you will also be able to format the labels by yourself if you provide the `bins` vector of non-pretty numbers.

**Comment by smartinsightsfromdata** [comment]
:+1:  thanks (but I would prefer pretty as an option...)

**Comment by yihui** [comment]
@smartinsightsfromdata Just added an argument `pretty = TRUE` to `colorBin()`, so you can choose to use exactly n bins generated from `seq(min, max, length = n)`.

**Comment by smartinsightsfromdata** [comment]
:+1:  :+1:

**Comment by yihui** [comment]
I forgot to mention it was still in the PR #53 and has not been merged to the master branch yet.
