### ISSUE TITLE
addMeasure does not work in most browsers

### ISSUE THREAD

**Issue by trafficonese** [rstudio/leaflet#635]
The `addMeasure` function seems to be broken in quite some browsers, including Chrome, IE, Edge, Opera. That's the error msg I am getting in Chrome:

> GET http://127.0.0.1:6718/leaflet-measure-2.1.7/leaflet-measure.min.js 500 (Internal Server Error)

> Uncaught SyntaxError: Unexpected identifier
>     at eval (<anonymous>)
>     at jquery.min.js:2
>     at Function.globalEval (jquery.min.js:2)
>     at text script (jquery.min.js:4)
>     at Xb (jquery.min.js:4)
>     at y (jquery.min.js:4)
>     at c (jquery.min.js:4)
>     at Object.send (jquery.min.js:4)
>     at Function.ajax (jquery.min.js:4)
>     at Function.n._evalUrl (jquery.min.js:4)

The only browser where it worked for me was **Firefox**. I dont know about Safari, as I dont have a Mac to test.

```r
library(shiny)
library(leaflet)

ui <- fluidPage(
  leafletOutput("map")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addMeasure() %>%
      addTiles()
  })
}

shinyApp(ui, server)
```

**Comment by YsoSirius** [comment]
It works for me in Chrome and Edge.

`sessionInfo()`

> R version 3.5.2 (2018-12-20)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] leaflet_2.0.2 shiny_1.3.2  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1      digest_0.6.18   later_0.8.0     mime_0.6        R6_2.4.0        xtable_1.8-3    jsonlite_1.6    magrittr_1.5    rlang_0.3.4    
> [10] promises_1.0.1  tools_3.5.2     htmlwidgets_1.3 crosstalk_1.0.0 httpuv_1.5.1    yaml_2.2.0      compiler_3.5.2  htmltools_0.3.6
> 
>

**Comment by trafficonese** [comment]
Updating `mime` and `digest` apparently solved the issue.

**Comment by schloerke** [comment]
Thank you for the followup and solution!
