### ISSUE TITLE
We will need to rebuild leaflet w/ the latest version of leaflet-providers. For now you can do

### ISSUE THREAD

**Issue by mikeshaw-omnicell** [rstudio/leaflet#637]
Hello, I'm having issues accessing Thunderforest tiles through Leaflet.  I found this post on the subject from two years ago:

https://github.com/rstudio/leaflet/issues/410

We will need to rebuild leaflet w/ the latest version of leaflet-providers. For now you can do

```r
leaflet() %>%
  addTiles(
    urlTemplate = "https://{s}.tile.thunderforest.com/{variant}/{z}/{x}/{y}.png?apikey={apikey}",
    attribution = "&copy; <a href='http://www.thunderforest.com/'>Thunderforest</a>,  &copy; <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>",
    options = tileOptions(variant='transport-dark', apikey = 'YOUR-KEY')
  )
```

You should pass in your key and use which ever variant you want.

_Originally posted by @bhaskarvk in https://github.com/rstudio/leaflet/issues/410#issuecomment-290471333_

The method described does not seem to be working.  Has leaflet been rebuilt (as hinted) with updated syntax?  

Thanks!

**Comment by mikeshaw-omnicell** [comment]
Please disregard, the method works fine.  There is an issue with my environment.

**Comment by schloerke** [comment]
@mikeshaw-omnicell 
Please check out #636 
We are outsourcing leaflet providers to a separate package to be able to update it more often.  

Please let us know if you run into issues.
