### ISSUE TITLE
Developing a new standalone plugin for R leaflet

### ISSUE THREAD

**Issue by am2222** [rstudio/leaflet#660]
Hi,
Sorry about possible wrong place for asking this question. I wanted to develop a kind of plugin on top of the R leaflet but being able to install it seperate than leaflet. My main goal is to add just a few more functions. I was wondering if there is any structure to develop such plugins?
I looked at the source of some leaflet plugins in this repository but it seems they are not htmlwidgets. Is there any example or such things that I can start with to get more about the structure of this package? I know js and have some idea about how htmlswidgets work but don't know how is it possible to develop a kind of plugin for another package.
thanks

**Comment by am2222** [comment]
Ok seems there is a hidden page in the docs
http://rstudio.github.io/leaflet/extending.html
but when I use the following example it does not work
```
addTestProvider <- function(
  map,
  provider,
  layerId = NULL,
  group = NULL,
  options = providerTileOptions()
) {
  # map$dependencies <- c(map$dependencies, leafletProviderDependencies())
  invokeMethod(map, getMapData(map), "addTestProvider ",
               provider, layerId, group, options)
}
```
and in my js file
```
LeafletWidget.methods.addTestProvider = function(provider, layerId, group, options) {
  alert("addTestProvider ");
  //this.layerManager.addLayer(L.tileLayer.provider(provider, options), "tile", layerId, group);
};
```
Am I missing something?

**Comment by tim-salabim** [comment]
May I ask what functionality your planning to add with your plugin?

**Comment by am2222** [comment]
It is just a custom vector tile layer. which is developed on top of `leaflet.vector.grid` plugin.
