### ISSUE TITLE
leaflet::fitBounds and method.fitBounds signatures do not match

### ISSUE THREAD

**Issue by mplourde** [rstudio/leaflet#67]
This a minor thing. The arguments for `methods.fitBounds` in **inst/htmlwidgets/leaflet.js** do not match the order of arguments in `leaflet::fitBounds`. The lat's and lng's are flipped:

```{javascript}
methods.fitBounds = function(lat1, lng1, lat2, lng2)
```

```{r}
fitBounds <- function(map, lng1, lat1, lng2, lat2)
```

Since both can be called from R, perhaps it would be good to have them match.

Thanks.

**Comment by yihui** [comment]
The JavaScript library Leaflet uses the convention `(lat, lng)`, but some R users prefer `(lng, lat)`. That is why we always use `(lng, lat)` in the R interface functions. Yeah, it is always painful whenever there are two styles and neither one is uniformly better than the other...

**Comment by mplourde** [comment]
This issue is no longer relevant due to the new API change.
