### ISSUE TITLE
Plotting a map from the console

### ISSUE THREAD

**Issue by jwhendy** [rstudio/leaflet#670]
How does one plot outside of RStudio? I noted this from [the tutorial](https://rstudio.github.io/leaflet/):
> Once installed, you can use this package at the R console, within R Markdown documents, and within Shiny applications.

But in practice when I try from a regular R console, I get this:
```
> library(leaflet)
> m <- leaflet() %>% addTiles() %>% addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
> m
Error in viewer(index_html) : 
  'browser' must be a non-empty character string
```

Is it implied that from the console one must `saveWidget` and subsequently open in a browser? It's not clear to me where one would supply the `browser` argument.

If this is something silly I'm overlooking with respect to getting rendering from the console, could this be added to [the tutorial](https://rstudio.github.io/leaflet/)?

**Comment by schloerke** [comment]
This should work right away.  I run your exact code outside of RStudio and it runs as expected.

Do you have a default web browser set for R? 

Mine (macOS) is currently (which opens Chrome)
```r
getOption("browser")
#> [1] "/usr/bin/open"
```

Example of setting your browser to non-default values: https://cran.r-project.org/web/packages/googlesheets/vignettes/alternative-browser.html

**Comment by jwhendy** [comment]
Weird, I had nada. Not sure where this is supposed to get picked up from on linux? I added `export BROWSER=firefox` to my `.bashrc` but R still comes up empty for `getOption("browser")`.

This works as a fix, though again, I'm not sure where it is supposed to come from in absence of setting it explicitly.

```
$ cat ~/.Rprofile
options(browser="/usr/bin/firefox")
```

Thanks for the tip!
