### ISSUE TITLE
Leaflet maps don't appear in RStudio Viewer Pane (Windows + R v4.0)

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/leaflet#678]
```
Leaflet Version:   2.0.3
RStudio Edition :  Desktop
RStudio Version :  1.2.5042
OS Version      :  Windows 10 x64
R Version       :  R version 4.0.0 (2020-04-24)
```

After I upgraded to R 4.0, `leaflet` stopped working correctly in RStudio.

### Reprex

Running the following leaflet map command results in a blank Viewer Pane:

```r
library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map
```

Leaflet commands run in an R session _outside_ of the RStudio IDE work as expected.

The problem appears to be related to a JavaScript exception (see @jmcphers's comment [here](https://github.com/rstudio/rstudio/issues/6737#issuecomment-620205087).)

### Related Issues

https://github.com/rstudio/rstudio/issues/6737

**Comment by kmcd39** [comment]
I'm having a similar problem. Bizarrely, after I restart an R session, the first leaflet appears in Viewer as expected, but then subsequent leaflets do not. The same command runs the first time, but if I clear plot an re-run, it won't show up the second time (it just shows a white box).

My session info:
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.9-3              leaflet_2.0.3         appHelpers_0.0.0.9100
[4] dplyr_0.8.5    
```

**Comment by jmcphers** [comment]
What version of RStudio are you using? We have a workaround for this problem in the most recent preview release:

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kmcd39** [comment]
> What version of RStudio are you using? We have a workaround for this problem in the most recent preview release:
> 
> https://www.rstudio.com/products/rstudio/download/preview/

Ah thanks. I'm using rstudio version 1.2.5042.
Had ended up re-installing an older version of R (3.6.3) for work around for now.

**Comment by tiernanmartin** [comment]
This problem appears to be resolved after upgrading to the latest RStudio preview: [RStudio v1.3.957-1](https://rstudio.com/products/rstudio/download/preview/)

See https://github.com/rstudio/rstudio/issues/6737
