### ISSUE TITLE
addPolylines leads to "Don't know how to get path data from object of class data.frame"

### ISSUE THREAD

**Issue by name-name** [rstudio/leaflet#68]
Hi,

I get a "Don't know how to get path data from object of class data.frame"
when I replace the "addCircles" with an "addPolylines" in the following code, but shouldn't it guess the proper columns in the very same way?

    ## app.R ##
    library(shiny)
    library(shinydashboard)
    library(leaflet)
    
    data(quakes)
    dat = quakes
    
    
    runApp(list(
      ui = dashboardPage(
        dashboardHeader(title = "quakes"),
        dashboardSidebar(
          sliderInput("slider", "#observations frequency:", 1, 100, 1)
        ),
        dashboardBody(
            leafletOutput("map", height = 600)
        )
      ),
      server = function(input, output) {
        
        output$map <- renderLeaflet({
          
          map <- leaflet() %>% addTiles()
          
          map %>% addCircles(data=dat[seq(from = 1, to = nrow(dat), by=input$slider), ],   #input$slider
                               fillOpacity = 1.0)
        })
      }
    ))

**Comment by yihui** [comment]
Thanks for the report. I think you are right. We should have guessed the lat/long columns from quakes in this case for `addPolylines()` as well. I will fix it.

**Comment by jcheng5** [comment]
No, this is the correct behavior. Circles only require points (single lat/long) to be rendered. Polylines require... well, polylines--that is, a list of coordinates per row.

What behavior were you hoping for here? For a single polyline that connects all the quakes?

**Comment by yihui** [comment]
I don't know what @name-name was hoping for, but I'd expect a single polyline in this case. I'm thinking of the base R graphics syntax `polygon()`/`lines()`: you provide x and y, you get a single line; if there are NAs in x/y, you get multiple polylines.

**Comment by jcheng5** [comment]
That seems (to me) like a weird thing to do to a data frame, though; our APIs assume that each row is one of the "things" that you're adding (in this case, polylines).

Anyway, if that's actually what you want, you can achieve it by changing to a 2-column matrix and then an `sp::Line`:

```
addPolylines(data=dat[seq(from = 1, to = nrow(dat), by=input$slider), c("long", "lat")] %>%
  as.matrix() %>%
  sp::Line()
```

Actually even if you don't provide `sp::Line()` and just pass it as a matrix, it still works, but I think the intent is a little more clear this way.

**Comment by name-name** [comment]
ahh, the problem was that the lat/long are in columns instead of a list (in one row).
Thanks for the feedback!
