### ISSUE TITLE
Function "doColorRamp()" not found when using a version of the scales package > 1.0.0

### ISSUE THREAD

**Issue by nicocriscuolo** [rstudio/leaflet#684]
Hello, I currently have a Leaflet map in my shiny app that needs the **scales** package as dependency.

If I upgrade the scales package (version 1.0.0) to the latest version (1.1.1), my Leaflet object is not rendered when using the same exact functions to build the legend. The error reports that the function doColorRamp() is not found (but apparently this is not a function that I can call from the Leaflet package). Just if I downgrade to the 1.0.0 version things start working again.

Installing the Leaflet package from source, as suggested in [this thread](https://github.com/r-lib/scales/issues/254), did not help.

Thanks a lot for your help.

**Comment by jcheng5** [comment]
Sorry for the delay. Do you have a code sample that reproduces this?

**Comment by nicocriscuolo** [comment]
**Update**: with the version of the **scales** package 1.1.1 and the version of the **leaflet** package 2.0.4.1 this error doesn't appear anymore.
