### ISSUE TITLE
Feature Request: Leaflet.VectorGrid

### ISSUE THREAD

**Issue by s5joschi** [rstudio/leaflet#699]
Hi. First. Great work. Thanks for this library! 

Any chance rendering vector tiles could make it into the R package?

 [https://github.com/Leaflet/Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid). 

It's one of the most important features besides raster tiles to display large datasets. Otherwise, Leaflet in R/Shiny is always bound to work with very small polygon datasets or operate with a very low/unusable rendering speed.

**Comment by tim-salabim** [comment]
@s5joschi I support your request in general. Though maybe [leaflet.extras2](https://github.com/trafficonese/leaflet.extras2) is a better place to integrate leaflet addons?

In the meantime you can give [leafgl](https://github.com/r-spatial/leafgl) a try. It uses webgl to render large vector data. Not grids, but capable of handling much bigger data sets than native leaflet.

**Comment by s5joschi** [comment]
@tim-salabim . Thanks for your response. Sounds good to post it in the elaflet.extras2. will do and see what happens there.
