### ISSUE TITLE
addCircles could handle NA values for lng and lat arguments

### ISSUE THREAD

**Issue by hansthompson** [rstudio/leaflet#71]
I'd like to have the default behavior of addCircles to ignore NA values.  For example:
```
library(leaflet)  #a super awesome package
leaflet_sample <- data.frame(lati = c(61.191, NA, 61.171), long = c(-149.895, NA, -149.875))

leaflet() %>% addTiles() %>% 
  setView(-149.885, 61.181, zoom = 11) %>% addCircles(lng = leaflet_sample$long, lat = leaflet_sample$lati,
                                                      color = "#ff0000")
#OR 
leaflet() %>% addTiles() %>% 
  setView(-149.885, 61.181, zoom = 11) %>% addCircles(lng = leaflet_sample$long[!is.na(leaflet_sample$long)], 
                                                      lat = leaflet_sample$lati[!is.na(leaflet_sample$lati)], 
                                                      color = "#ff0000")
```
Thanks for any opinions if this is a worth feature request or not.

**Comment by yihui** [comment]
Interesting. I did not know NA's could cause problems in leaflet. Thanks for the minimal reproducible example! We will see what we can do.

**Comment by rbdixon** [comment]
+1 -- I just stumbled on this same issue when using addMarkers(). This seems to already be well documented but I do have a minimal reproducible example of the addMarker() behavior, if needed.

**Comment by bhaskarvk** [comment]
Closing as duplicate and tracking under #304
