### ISSUE TITLE
Synchronous XMLHttpRequest in leaflet

### ISSUE THREAD

**Issue by spongioblast** [rstudio/leaflet#713]
Is it possible to get rid of the synchronous Synchronous XMLHttpRequest in the future?

Eg: 
![image](https://user-images.githubusercontent.com/18749396/100145639-e792db00-2e98-11eb-82aa-c62133983522.png)

or
![image](https://user-images.githubusercontent.com/18749396/100145677-f7122400-2e98-11eb-8b4f-cd1b9e8bde77.png)

Thanks!

**Comment by jcheng5** [comment]
This doesn't have to happen today; as far as I know, it's only when JavaScript assets are deployed after initial page load.

So this doesn't trigger:

```r
library(shiny)
library(leaflet)

ui <- fluidPage(
  leafletOutput("map")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet()
  })
}

shinyApp(ui, server)
```

And this does:

```r
library(shiny)
library(leaflet)

ui <- fluidPage(
  # Nothing about this initial page load contains anything about leaflet
  uiOutput("ui")
)

server <- function(input, output, session) {
  output$ui <- renderUI({
    leafletOutput("map")
  })
  
  output$map <- renderLeaflet({
    leaflet()
  })
}

shinyApp(ui, server)
```

I don't know if it's possible to remove it in the latter case; if so, it'd need to happen in htmlwidgets and/or Shiny.
