### ISSUE TITLE
Support for new spatial data classes

### ISSUE THREAD

**Issue by rhijmans** [rstudio/leaflet#728]
It would be great if `addRasterImage` could support for `SpatRaster` objects from the terra package (a replacement for the `raster` package). It should perform better as `terra::project` is much faster than `raster::projectRaster`. It also should be easy to do, the interface of `terra` is very similar to that of `raster`.  It would also be great if the `leaflet` method could support vector data from `sf` and `SpatVector` from `terra`.

**Comment by jcheng5** [comment]
Hi @rhijmans! That would be really great indeed.

Can you clarify what you mean by "vector data from `sf`"? I thought we already had pretty good sf support, though I haven't been paying much attention.

**Comment by rhijmans** [comment]
And, by the way, I think you set me on the path towards terra (C++ with some R around it) with your contributions to make `raster` faster for leaflet.

**Comment by gilbertocamara** [comment]
I second the request from @rhijmans: supporting "terra" objects in leaflet would help all those that work with geospatial data.

**Comment by AMBarbosa** [comment]
Dear colleagues, any news on implementing "SpatRaster" input for `addRasterImage`, and "SpatVector" input for `addPolygons`, `addPolylines`, etc.? This is becoming more and more urgent, given the evolution in spatial data users. The "SpatVector" implementation could be as simple as coercing to the already-implemented 'sf' format at the beginning of the functions:
```
if (inherits(data, "SpatVector"))  data <- sf::st_as_sf(data)
```
I guess the analogous could _provisionally_ be done for "SpatRaster" too (`if (inherits(x, "SpatRaster"))  x <- raster::raster(x)`), though given the differences in performance, it is (speaking from experience) totally worth the trouble to do the opposite, i.e. make the minimal changes in code to accomodate "SpatRaster" instead, and eventually coerce "Raster" inputs to it (`if (inherits(x, "RasterLayer"))  x <- terra::rast(x)`). Thanks and kudos for the great package!

**Comment by rhijmans** [comment]
@jcheng5: I would happily create a PR if you are interested.

**Comment by jcheng5** [comment]
@rhijmans That would be fantastic, thank you

**Comment by AMBarbosa** [comment]
I've tested it with a few different 'leaflet' scripts, combining a variety of layers of different classes (including "Spatial*", "SpatVector", "RasterLayer", "SpatRaster"), and it seems to work seamlessly! Also, 'terra' layers plot visibly faster than their "Spatial*" versions (cf. Uganda in the above example). Thank you so much, Robert!

**Comment by AMBarbosa** [comment]
Forgot to mention I'm on Linux Mint 19.3 Cinnamon. I also deployed a Shiny app with 'leaflet' maps at https://ambiogeo.shinyapps.io/atlasmampor/, using @rhijmans's fork and a few 'SpatVector' layers, with no problems so far.

**Comment by rhijmans** [comment]
This has now been merged into the main branch. A next PR (pending) adds support for color-tables and RGB rasters. See the branch at https://github.com/rhijmans/leaflet with these examples 

```
library(terra)
library(leaflet)

# RGB
s <- rast(system.file("ex/logo.tif", package="terra"))  
crs(s) <- "+proj=longlat" 
leaflet() |> addTiles() |> addRasterImage(s)

# color table
r <- rast("/vsicurl/https://geodata.ucdavis.edu/test/pr_nlcd.tif")
r[550:750, ] <- NA
leaflet() |> addTiles() |> addRasterImage(r, opacity = 0.75)

# difference with a continuous raster
x <- r * 1
leaflet() |> addTiles() |> addRasterImage(x, opacity = 0.75)
```
