### ISSUE TITLE
[Security] Update jQuery

### ISSUE THREAD

**Issue by b4D8** [rstudio/leaflet#730]
Current package comes with jQuery 1.12.4 which was release in May 2016 and is known to have vulnerabilities...

I ran Lighthouse on my website and got the following warning:

```
Includes front-end JavaScript libraries with known security vulnerabilities 4 vulnerabilities detected
```

Library Version | Vulnerability Count | Highest Severity
-- | -- | --
jQuery@1.12.4 | 4 | Medium

Probably an even better option would be to remove this dependency (#VanillaJS).

**Comment by hedsnz** [comment]
It looks like leaflet contains both jQuery 1.12.4 and 3.6.0. The older version is in inst/htmlwidgets/lib/jquery/jquery.js. Is there any requirement to keep this vulnerable version? I don't think htmlwidgets actually relies on jQuery any more, though I might be wrong.
