### ISSUE TITLE
radius is not vectorized in addCircles()?

### ISSUE THREAD

**Issue by yihui** [rstudio/leaflet#74]
```r
library(leaflet)
leaflet() %>% addCircles(rnorm(100), rnorm(100), radius = runif(100, 1, 10))
```

![screenshot from 2015-05-04 21 09 53](https://cloud.githubusercontent.com/assets/163582/7466042/f2b98882-f2a1-11e4-964b-1c21bb9e7a03.png)

**Comment by jcheng5** [comment]
They're different, they're just all really small relative to the stroke (the radius is in meters, while lat/lng are in degrees). Try this:

```r
leaflet() %>% addCircles(rnorm(100), rnorm(100), radius = runif(100, 1, 20000))
```

**Comment by yihui** [comment]
Thanks! Seeing is not believing... :dizzy_face:
