### ISSUE TITLE
Broken URL in documentation

### ISSUE THREAD

**Issue by shirasal** [rstudio/leaflet#742]
The link to leaflet documentation ('reference document') in page ['Map Widget'](http://rstudio.github.io/leaflet/map_widget.html) is broken. I think the correct URL is: https://leafletjs.com/reference-1.7.1.html#map-option

**Comment by schloerke** [comment]
The leaflet R package is a little behind. The link should be https://leafletjs.com/reference-1.3.4.html#map-option
