### ISSUE TITLE
New feature: addLegend labels argument should support named vectors

### ISSUE THREAD

**Issue by davidhodge931** [rstudio/leaflet#781]
It'd be great if the labels argument could allow for a named vector, so that the order is not important of values provided to the legend

This would mirror the way in ggplot2, the scale_colour_manual argument can use a named vector

**Comment by jcheng5** [comment]
I'm not sure exactly how you mean... can you provide a minimal example of how you are doing this today, and how you would like to be able to express it? Thanks.

**Comment by davidhodge931** [comment]
Actually think this is a bit confused now, sorry. I'll close
