### ISSUE TITLE
Markers do not render: 403 Forbidden on cloudfront.net 

### ISSUE THREAD

**Issue by SimonCoulombe** [rstudio/leaflet#782]
Hi!
I am on a fresh install of Linux Mint and I can't display markers on a leaflet map.

Here is what I get when trying to run the [example code from Rstudio](https://rstudio.github.io/leaflet/)

Steps to reproduce
```

library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m

```
Expected behavior
I expect to get a map with a marker showing "the birthplace of R".

Current behavior
No marker appears. If I guess where it is and click, the text pops up.
In my firefox browser I get a transparent square where the marker should be.
Checking the consoles shows that I got a 403 Forbidden error when trying to download these two files:

*    https://d19vzq90twjlae.cloudfront.net/leaflet/v1.3.1/images/marker-icon-2x.png
*    https://d19vzq90twjlae.cloudfront.net/leaflet/v1.3.1/images/marker-shadow.png

Environment  

*    Leaflet version: 2.1.0  
*    Browser (with version): Mozilla Firefox for Linux Mint 98.0.1  
*    OS/Platform (with version): Linux Mint 20.3  
*    Rstudio 2022.02.0 build 443  
*    R 4.1.3  

```
> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       Linux Mint 20.3
 system   x86_64, linux-gnu
 ui       RStudio
 language en_CA
 collate  en_CA.UTF-8
 ctype    en_CA.UTF-8
 tz       America/Toronto
 date     2022-03-15
 rstudio  2022.02.0+443 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cli           3.2.0   2022-02-14 [1] CRAN (R 4.1.3)
 crosstalk     1.2.0   2021-11-04 [1] CRAN (R 4.1.3)
 digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.3)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.3)
 htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.3)
 htmlwidgets   1.5.4   2021-09-08 [1] CRAN (R 4.1.3)
 jsonlite      1.8.0   2022-02-22 [1] CRAN (R 4.1.3)
 leaflet     * 2.1.0   2022-02-16 [1] CRAN (R 4.1.3)
 magrittr      2.0.2   2022-01-26 [1] CRAN (R 4.1.3)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.3)
 rlang         1.0.2   2022-03-04 [1] CRAN (R 4.1.3)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.3)
 yaml          2.3.5   2022-02-21 [1] CRAN (R 4.1.3)

 [1] /home/simon/R/x86_64-pc-linux-gnu-library/4.1
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

Additional context

```
Here's a screenshot with everything discussed.

![Screenshot from 2022-03-15 23-38-16](https://user-images.githubusercontent.com/23444900/158620988-25141d7c-b748-4faa-9aaf-b6f283dbbd24.png)

**Comment by tpemartin** [comment]
I encountered the same problem the other day. I switch to use `addAwesomeMarkers` which still works.

**Comment by tim-salabim** [comment]
See also
https://twitter.com/marcbeldata/status/1503338111337697292

**Comment by tpemartin** [comment]
Wonder if it is the CORS policy causing the problem: 

Referrer Policy: strict-origin-when-cross-origin

![Untitled](https://user-images.githubusercontent.com/6549594/159117160-65e22f41-6754-448f-8679-254f050fd0f3.jpg)

**Comment by mw0000** [comment]
try alternative sources for tiles and markers:

`leaflet() %>% addProviderTiles(providers$OpenStreetMap.Mapnik) %>% addAwesomeMarkers(lat,lng,icon = awesomeIcons())`

**Comment by jcheng5** [comment]
Sorry about this, everyone. We’ll try to find an alternative ASAP

**Comment by jcheng5** [comment]
We'll try to get this onto CRAN ASAP.

**Comment by SimonCoulombe** [comment]
Thanks! I'm not sure what the listed alternatives mean for a user, but meanwhile I will just use a different marker. 
cheers

**Comment by jcheng5** [comment]
@SimonCoulombe Or just install leaflet from GitHub master, it should be fixed now. `remotes::install_github("rstudio/leaflet")`

**Comment by jcheng5** [comment]
The fix for this is on CRAN now. Thank you to everyone who reported it!
