### ISSUE TITLE
Leaflet providers outdated

### ISSUE THREAD

**Issue by rgzn** [rstudio/leaflet#797]
The leaflet providers in this package are not up-to-date with those on [the leaflet providers plug-in](https://leaflet-extras.github.io/leaflet-providers/preview/)

This: 
```r
> leaflet::providers["USGS"]
  $<NA>
  NULL
```

Does not match the results here:
https://leaflet-extras.github.io/leaflet-providers/preview/#filter=USGS

This seems like it was an issue before:
https://github.com/rstudio/leaflet/issues/649

Maybe providers should be dynamically acquired from the leaflet-providers site to avoid this?

**Comment by jeffkeller87** [comment]
The `leaflet.providers` package provides a means for getting newer base map providers without requiring updates to `leaflet`.

```r
library(leaflet)
library(leaflet.providers)
library(magrittr)
use_providers(get_providers())
leaflet() %>% addProviderTiles(provider = "USGS.USTopo")
```

**Comment by rgzn** [comment]
Thanks, I didn't know about this.
