### ISSUE TITLE
Incorrect license for OpenStreetMap?

### ISSUE THREAD

**Issue by kathleenlu09** [rstudio/leaflet#811]
Hello, I am with the Legal/Licensing Working Group of the OpenStreetMap Foundation.

We received a report from a user who was confused that 
> "CC-BY-SA" is automatically labeled when a map is created using the "leaflet" package in R.

OpenStreetMap's data license changed from CC-BY-SA to ODbL [many years ago](https://wiki.osmfoundation.org/wiki/Licence/About_The_Licence_Change.), and the tiles [no longer have a separate license](https://blog.openstreetmap.org/2020/06/25/new-licence-for-the-standard-style-tiles-from-openstreetmap-org/), and we have [simplified our attribution](https://wiki.osmfoundation.org/w/index.php?title=Licence/Attribution_Guidelines&mobileaction=toggle_view_desktop). 

Thus, I believe that the lines here https://github.com/rstudio/leaflet/blob/5d1317739fac114b9aecf33aa95dac24a02c3668/R/layers.R#L165-L166 should be
```
    "&copy; <a href=\"https://openstreetmap.org/copyright/\">OpenStreetMap</a>",
      "<a href=\"https://opendatacommons.org/licenses/odbl/\">ODbL</a>"
```

If you could update this, we would much appreciate it.

**Comment by jcheng5** [comment]
Ouch, I'm so sorry! We'll fix this right away. Thank you for the friendly report and for OpenStreetMap!
