### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [rstudio/leaflet#833]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

My guess is that dropping **rgdal** and **rgeos** and replacing them by **terra**, conditioning **raster** on `>= 3.6.3` will resolve this (untried). You use `rgeos::createPolygonsComment`, but should be able to work around that with either **sf** or **terra**.

**Comment by jcheng5** [comment]
Thanks @rsbivand. With regard to `rgeos::createPolygonsComment`, it looks to me like we use this for **sp** `Polygons` objects whenever they're missing comment data indicating, for each hole, what non-hole they belong to.

> `createPolygonsComment` attempts to create a valid comment for a `Polygons` object by assessing which polygons contain a given hole (using [gContains](http://127.0.0.1:14629/help/library/rgeos/help/gContains)). Ownership is assigned to the smallest polygon (by area) that contains the given hole.

Is there some higher-level functionality in **sf** or **terra** that we can use for this, or were you imagining a reimplementation using just `st_contains` and `st_area`?

**Comment by rsbivand** [comment]
I'll create a reprex in https://github.com/r-spatial/evolution https://github.com/r-spatial/evolution/issues/9 and explore. It should no longer be a big problem, if for example ESRI Shapefiles are read through the GDAL driver where GDAL was built linking to GEOS, the driver itself restores Simple Features specs even via `rgdal::readOGR()`. It was a problem before about 2010, and still would be for serialised `Polygons` objects pre-dating those changes, and for other manually created objects.

**Comment by jcheng5** [comment]
2010! Wow...

What if we detect Polygons with 1) missing comment, 2) holes, 3) more than one island, and throw a warning (or even error)? Technically breaking backward compatibility I suppose, but this seems like such an extreme edge case.

**Comment by rsbivand** [comment]
Right, an edge case, but if https://github.com/r-spatial/sf/issues/2063 can lead to coercion to a conformant `sfg`, or a list of `sfg`'s (`sfc`), then back to a Simple-Features conformant `Polygons` or `SpatialPolygons` object, it might make sense to do that. Other than **leaflet**, **occTest** uses `rgeos::createPolygonsComment()`, and **ggOceanMaps** uses `rgeos::createSPComment()`, calling `rgeos::createPolygonsComment()` internally.

**Comment by jcheng5** [comment]
OK, that’d be great. In the meantime I can get the rest of the PR ready. Thank you.

**Comment by cpsievert** [comment]
Seems this can be closed (the leaflet changes for this are now on main)?
