### ISSUE TITLE
L.CRS.EPSG3857.unproject function in R 

### ISSUE THREAD

**Issue by dustming** [rstudio/leaflet#840]
Hi Everyone 

   I got the lat and lon in epsg4326 using input$MAPID_bounds.  I need to transfer it to EPSG: 3587. I think the leaflet did these transformations internally. How do I make the same transformation as the leaflet did? 

Best 
Ming

**Comment by jcheng5** [comment]
Are you sure you mean unproject? Not project? If you mean project:

```r
# Be sure to check whether input$map1_bounds is NULL before proceeding!

bounds <- input$map1_bounds
longitude <- c(bounds$west, bounds$east)
latitude <- c(bounds$north, bounds$south)
lonlat <- cbind(longitude, latitude)

pts <- terra::vect(lonlat, type="points", crs="+proj=longlat +datum=WGS84")
projected <- terra::geom(terra::project(pts, "epsg:3857"))[,c("x", "y")]
```

The `projected` will be a matrix containing `x`/`y` columns and two rows.
