### ISSUE TITLE
Projection issues with raster plot on leaflet 

### ISSUE THREAD

**Issue by amegbor** [rstudio/leaflet#842]
I am plotting raster data on Leaflet and mapview however the location of the raster is off. Instead of Copenhagen, Denmark, the raster appears in the Gulf of Guinea (Longitude 0 and latitude 0) - please find the attached image below.

![Screenshot 2023-01-24 150416](https://user-images.githubusercontent.com/60387204/214446240-c8059055-5b3a-4cc2-b0be-848b18e07f78.jpg)

When I use a polygon with the same CRS as the raster I get the desired plot. This

![Screenshot 2023-01-24 150342](https://user-images.githubusercontent.com/60387204/214446301-aa037795-6c1a-4720-acd0-3888221427c0.jpg)

Any idea of what might be wrong? 

the results for the projections for the raster and polygon are shown below

 crs(r) 

    Coordinate Reference System:
    Deprecated Proj.4 representation: +proj=longlat +datum=WGS84 +no_defs 
    WKT2 2019 representation:
    GEOGCRS["unknown",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6326]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8901]],
        CS[ellipsoidal,2],
            AXIS["longitude",east,
                ORDER[1],
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            AXIS["latitude",north,
                ORDER[2],
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]]]

    proj4string(CPH)

"+proj=longlat +datum=WGS84 +no_defs"
[r](https://stackoverflow.com/questions/tagged/r)[leaflet](https://stackoverflow.com/questions/tagged/leaflet)[raster](https://stackoverflow.com/questions/tagged/raster)[mapview](https://stackoverflow.com/questions/tagged/mapview)

**Comment by jcheng5** [comment]
Hmmm, I haven't seen this. Do you have a reproducible example you can send?

**Comment by amegbor** [comment]
> Hmmm, I haven't seen this. Do you have a reproducible example you can send?

I realised the problem was coming from the unit of the projection. When I specified the "+proj=longlat +datum=WGS84 +no_defs" as the coordinate reference system for the raster I forgot the default unit meters. I am pulling this. Sorry for the error.
