### ISSUE TITLE
using a provider tile prevents caching chunk on knitr

### ISSUE THREAD

**Issue by cderv** [rstudio/leaflet#843]
Take this document 

````markdown
---
title: "test"
output: html_document
---

```{r}
library(leaflet)
```

```{r, cache = TRUE}
m <- leaflet() %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12)
m %>% addProviderTiles(providers$OpenTopoMap)
```

````

We'll get an error like this 
````
Error:
! path for html_dependency not found: C:/Users/chris/AppData/Local/Temp/RtmpaOTxJr
Backtrace:
    ▆
 1. └─rmarkdown::render("C:/Users/chris/Documents/test.Rmd", encoding = "UTF-8")
 2.   └─output_format$pre_processor(...)
 3.     └─rmarkdown (local) base(...)
 4.       └─rmarkdown:::html_extras_for_document(...)
 5.         └─rmarkdown (local) dependency_resolver(all_dependencies)
 6.           └─base::lapply(dependencies, validate_html_dependency)
 7.             └─rmarkdown (local) FUN(X[[i]], ...)
 8.               └─rmarkdown:::stop2("path for html_dependency not found: ", file)
 ````

I believe this is directly related to https://github.com/rstudio/leaflet/issues/732. Not using a temp file in the HTML dependency should solves this issue. 

This came initially in https://github.com/quarto-dev/quarto-cli/issues/4149

@schloerke I believe we already discussed on something related some time ago, but can't find a reference to it. Maybe you'll remember

**Comment by ericvmai** [comment]
How do you NOT use a temp file in the HTML dependency?

**Comment by schloerke** [comment]
Added new issue in https://github.com/rstudio/leaflet.providers/issues/34 in leaflet.providers to get the ball rolling. A small change will be needed here, but it needs to be fixed in `leaflet.providers` first.
