### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nipnipj** [rstudio/leaflet#844]
How to prevent polygon vertices to be connected in a wrong way/order? Please see the attached images.

In the "nice" image we see how the vertices form 2 polygons. It would be even better if they just formed a single polygon.
![nice](https://user-images.githubusercontent.com/36553373/219542964-fda06abd-d81f-4f11-bd2d-96d8cc0cf3ba.png)

Here, in the "ugly" image, we see how the vertices try to form a single polygon but in a not so attractive way.
![ugly](https://user-images.githubusercontent.com/36553373/219542985-5cabff05-5ab9-4fb2-8d98-0257b7c62151.png)

**Comment by jcheng5** [comment]
Are you forming these polygons by hand? The order of the vertices determines how the lines are drawn; make sure connected vertices appear consecutively. You may also have to make sure they are in counter-clockwise order (or clockwise? I don’t remember).

**Comment by nipnipj** [comment]
TY! I'll try you suggestion.
