### ISSUE TITLE
Missing `terra::` for `has.RGB()`

### ISSUE THREAD

**Issue by Rafnuss** [rstudio/leaflet#866]
https://github.com/rstudio/leaflet/blob/0f8e8315c63b8348c6cc054e1964af48309b576e/R/layers.R#L468

should be

```
if (terra::has.RGB(x)) {
```

Or I could be wrong and I still don't really understand the use of `::`

**Comment by audricvigier** [comment]
I'm currently having issues displaying a `SpatRaster` because of this, could `terra::` be added in front of all `has.RGB` please? That would save a lot of time to people wondering what's happening the first time they encounter an error stating that `has.RGB` does not exist.
