### ISSUE TITLE
Please bring the latest version from CRAN (2.1.2) to GitHub

### ISSUE THREAD

**Issue by rl-utility-man** [rstudio/leaflet#867]
Hello,

https://cran.r-project.org/web/packages/leaflet/index.html has version 2.1.2, but the latest version acknowledged as a release on GitHub appears to be version 2.0.3

https://rstudio.github.io/leaflet/ reports that "The "leaflet" R package is copyright © 2014-2016 RStudio, Inc."  Please update this as appropriate.

Thanks!

**Comment by daattali** [comment]
I believe that the latest version is indeed on github, if you install the package using `remotes::install_github()` it should be newer than CRAN. What you're referring to is the **releases**, it seems like they simply stopped making a release on GitHub every time they release on CRAN.

**Comment by rl-utility-man** [comment]
Many thanks Dean!  Yes, I would appreciate it if they either synched the releases on GitHub to those on CRAN or noted clearly on the project homepage that they are not doing so and gave clear advice about what to do to get the latest stable release.

**Comment by daattali** [comment]
I don't have any affiliation with this project, but I can tell you from my experience and as an educated guess that they are not likely to talk about the github releases in the README.  There's a convention in the community that stable releases go on CRAN and development version is on GitHub -- and the "releases" on GitHub are not as robust. For projects that are ONLY available on github, you can expect the Releases to be more strict, but with CRAN available, the releases on github are not too important.

**Comment by gadenbuie** [comment]
The tags were all there but we hadn't created releases yet, which was an oversight. I just created releases from the existing tags.

You can install a specific version from CRAN using the tags:

```r
remotes::install_github("rstudio/leaflet@2.1.2")
```

In the future, if you don't see the release in the [list of releases](https://github.com/rstudio/leaflet/releases), you can also check [the repository tags](https://github.com/rstudio/leaflet/tags) in the Releases tab to see if version tags were created.

I'm closing this issue as completed; we'll also update the copyright years soon. Thanks all!
