### ISSUE TITLE
addPolyline() with SpatVector fails if terra is not loaded because check_crs_terra() is missing depency terra::crs

### ISSUE THREAD

**Issue by mkoohafkan** [rstudio/leaflet#893]
When `{terra}` is not loaded (e.g., individual `{terra}` functions are imported into package namespace) functions that internally call `check_crs_terra()` will fail. I think this is because `check_crs_terra()` simply calls `crs()` instead of `terra::crs()`:
https://github.com/rstudio/leaflet/blob/d8c97944df7aa788dce0b4834eb250b13f34ba78/R/normalize-terra.R#L74-L94

I encounter this issue when calling `addPolylines()` with `SpatVector` objects.

**Comment by gadenbuie** [comment]
I think it's a little of all of the above, but mostly the fix is to call `terra::crs()` rather than `crs()`.
