### ISSUE TITLE
Update docs to use `{sf}` or `{terra}`

### ISSUE THREAD

**Issue by schloerke** [rstudio/leaflet#909]
> With the archival of legacy spatial packages, sf and terra are the new "best practices" packages. sp is still there, but uses sf under the hood  https://r-spatial.org/r/2023/04/10/evolution3.html

_Originally posted by @olivroy in https://github.com/rstudio/leaflet/pull/903#discussion_r1541978568_

**Comment by jack-davison** [comment]
Related (though perhaps a different issue?) - is there intention to export the example data (e.g., https://rstudio.github.io/leaflet/reference/breweries91.html) as `{sf}` dataframes/tibbles rather than `sp::SpatialPointsDataFrame`s?
