### ISSUE TITLE
Leaflet in ioslides_presentation

### ISSUE THREAD

**Issue by ldecicco-USGS** [rstudio/leaflet#92]
First off, super awesome package! It took almost no time to have great interactive maps hooked up.

If I make a presentation using rmarkdown + ioslides_presentation, and click through to a leaflet map (# 6 in this example), there is a problem with the tiles/zoom/circles:
https://rawgit.com/ldecicco-USGS/toxEval/master/samplePres.html

If I go directly to the slide (or hit refresh), it looks fine :
https://rawgit.com/ldecicco-USGS/toxEval/master/samplePres.html#6

This is true on the local html file, as well as the rawgit. Any suggestions on preventing this problem?

**Comment by yihui** [comment]
Can you try this?

```r
devtools::install_github(c('ramnathv/htmlwidgets', 'rstudio/leaflet'))
```

**Comment by ldecicco-USGS** [comment]
Works like a charm, thanks!

**Comment by ldecicco-USGS** [comment]
I've noticed this behavior returns if I use 2 maps in a presentation:

https://rawgit.com/ldecicco-USGS/toxEval/master/samplePres.html
see slide 4 via clicking from the first slide compared to going directly to:
https://rawgit.com/ldecicco-USGS/toxEval/master/samplePres.html#4

I noticed this, then updated via gitHub, so my current info is:

> devtools::session_info()
Session info ---------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, mingw32             
 ui       RStudio (0.98.1103)         
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             

Packages -------------------------------------------------------------------------------------
 package     * version   date       source                               
 bitops        1.0-6     2013-08-17 CRAN (R 3.1.1)                       
 devtools      1.8.0     2015-05-09 CRAN (R 3.2.0)                       
 digest        0.6.8     2014-12-31 CRAN (R 3.1.2)                       
 git2r         0.10.1    2015-05-07 CRAN (R 3.2.0)                       
 htmltools     0.2.6     2014-09-08 CRAN (R 3.1.2)                       
 htmlwidgets   0.4       2015-05-21 Github (ramnathv/htmlwidgets@86994f5)
 httr          0.6.1     2015-01-01 CRAN (R 3.1.2)                       
 knitr         1.10.5    2015-05-06 CRAN (R 3.2.0)                       
 leaflet     * 0.0.16    2015-05-21 Github (rstudio/leaflet@680a72b)     
 magrittr      1.5       2014-11-22 CRAN (R 3.1.2)                       
 memoise       0.2.1     2014-04-22 CRAN (R 3.1.1)                       
 RCurl         1.95-4.6  2015-04-24 CRAN (R 3.2.0)                       
 rstudio       0.98.1103 2015-04-08 local                                
 rstudioapi    0.3.1     2015-04-07 CRAN (R 3.2.0)                       
 rversions     1.0.0     2015-04-22 CRAN (R 3.2.0)                       
 stringi       0.4-1     2014-12-14 CRAN (R 3.1.2)                       
 stringr       1.0.0     2015-04-30 CRAN (R 3.2.0)                       
 XML           3.98-1.1  2013-06-20 CRAN (R 3.1.1)

**Comment by jcheng5** [comment]
Shoot, you're right. I'll take a look.

**Comment by jcheng5** [comment]
The fix is here: https://github.com/ramnathv/htmlwidgets/pull/114

You can try it out with:
```
devtools::install_github("ramnathv/htmlwidgets@joe/bugfix/bad-closure-scope")
```

Thanks so much for the heads up, it was a pretty bad bug...

**Comment by ldecicco-USGS** [comment]
Great, looks awesome! Thanks for the speedy reply!
