### ISSUE TITLE
unwanted grid added by showGroup()

### ISSUE THREAD

**Issue by aloboa** [rstudio/leaflet#936]
Given:

```
map1 <- leaflet() %>%
  setView(lat = -0.637, lng=-76.15 , zoom = 14) %>%
  addMouseCoordinates() %>% 
  addProviderTiles(providers$Esri.WorldImagery, 
                   group = c('Satview',"ortoMosaicos"), 
                   options=providerTileOptions(opacity=1)) %>% 
  addTiles(urlTemplate = urlGR_RGBpantano, group = "ortoMosaicos",
           options=tileOptions(maxZoom = 24)) %>%  addLayersControl(
           baseGroups =    c("Satview","ortoMosaicos"),
           overlayGroups = c(),
          options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE))
map1
```

I get:

![image](https://github.com/user-attachments/assets/7184e7c1-d56c-4b5f-975d-4751d016a653)

As I want the layer "ortoMosaicos" to be initially displayed, I do:

`map1 %>% showGroup(c("ortoMosaicos")) `

but get this undesired, odd grid overlayed:

![image](https://github.com/user-attachments/assets/5cbd3f13-d004-41a3-b15c-8b725e260c01)

I apologize for not providing  a fully reproducible example, the layer pointed by the url is not public (and it is not mine).

**Comment by gadenbuie** [comment]
> I apologize for not providing a fully reproducible example, the layer pointed by the url is not public (and it is not mine).

The problem most likely likes with this URL or your use of it. The "unwanted grid" is actually your browser showing you a grid of missing images (notice the broken image icon in the left of each grid). This indicates that the tile images aren't loading correctly. You may have misspecified the URL?

**Comment by tim-salabim** [comment]
Might just be that you zoomed out too far. Notice tile 2/2 shows (what I assume are) the mosaics. Probably best to set `minZoom` and `maxZoom` in the `tileOptions()` of the `addTiles()` call for the mosaics.

**Comment by aloboa** [comment]
Actually, as pointed out by a colleague, the problem was considering ortoMosaicos as a base layer. 
The following works without displaying the grid:

```
map1 <- leaflet() %>%
  setView(lat = -0.637, lng=-76.15 , zoom = 14) %>%
  addMouseCoordinates() %>% 
  addProviderTiles(providers$Esri.WorldImagery, 
                   group = c('Satview',"ortoMosaicos"), 
                   options=providerTileOptions(opacity=1)) %>% 
  addTiles(urlTemplate = urlGR_RGBpantano, group = "ortoMosaicos",
           options=tileOptions(maxZoom = 24)) %>%  addLayersControl(
           baseGroups =    c("Satview"),
           overlayGroups = c("ortoMosaicos"),
          options = layersControlOptions(collapsed = FALSE, autoZIndex = TRUE))
map1
```
![image](https://github.com/user-attachments/assets/9d950eb8-3ccc-43b9-b209-1f9c1ffc507b)
