### ISSUE TITLE
Different display of polyline in leaflet and in terra::plot()

### ISSUE THREAD

**Issue by aloboa** [rstudio/leaflet#937]
Given:
```

library(leaflet)
library(terra)
Trails <- vect(file.path("../GEODATABASE/Trails", "Trails.shp"))
leaflet() %>%
    setView(lat = -0.637, lng=-76.15 , zoom = 14) %>%
    addProviderTiles(providers$Esri.WorldImagery, 
                     group = c('Satview',"ortoMosaicos"), 
                     options=providerTileOptions(opacity=1)) %>%    
    addPolylines(data=Trails, group="Trails",
                 lng=geom(Trails)[,"x"], 
                 lat = geom(Trails)[,"y"],
                 weight=2,
                 fillColor="black",
                 color="black",
                 stroke=TRUE,
                 opacity=1)
```

I get:
![image](https://github.com/user-attachments/assets/c2ea56b2-4f53-4350-95f8-9fbfa10d70e4)

While in R:

plot(Trails)

![image](https://github.com/user-attachments/assets/0c5c8913-9d94-40e5-a6d6-c03788f66364)

Am I missing a critical option in addPolylines() or is there something to be done in the terra vector lines before ingesting to leaflet?

**Comment by tim-salabim** [comment]
This
```r
addPolylines(data=Trails, group="Trails",
               weight=2,
               fillColor="black",
               color="black",
               stroke=TRUE,
               opacity=1)
```
should do what you want. If you have data of a spatial type (terra, sf), use the `data` argument. If you only have coordinates, use `lng`, `lat`.

May I ask where you got the impression from that you can/should use both?

**Comment by aloboa** [comment]
> May I ask where you got the impression from that you can/should use both?

From not reading the documentation with due attention. I apologize.

**Comment by tim-salabim** [comment]
No need to apologise.  Was just wondering whether some llm like chatgpt came up with that.
