### ISSUE TITLE
shiny example references leafletProxy, but cannot find it...

### ISSUE THREAD

**Issue by hmaeda** [rstudio/leaflet#96]
Hi, I am very interested in using the interactive examples shown in the given examples [here](https://github.com/rstudio/leaflet/blob/master/inst/examples/shiny.R) 

But when running and trying to add a marker...I get the following error...

`Warning in run(timeoutMs) :
  Unhandled error in observer: could not find function "leafletProxy"
observeEvent(input$map1_click)`

Where would I be able to find leafletProxy?

**Comment by yihui** [comment]
It seems you have realized it: `devtools::install_github('rstudio/leaflet')`
