### ISSUE TITLE
Two updates of legend via inputmap_marker_click$id causes updates to stop

### ISSUE THREAD

**Issue by Stephen-McDaniel** [rstudio/leaflet#97]
The first update works, but stops thereafter.  Also seen in other, more complex code, but here's a simple example.

library(shiny)
library(leaflet)

ui <- fluidPage(leafletOutput("map1"))

server <- function(input, output, session) {

   values <- reactiveValues(click = "Click Markers")
   
   observeEvent(input$map1_marker_click$id,{
       values$click <- input$map1_marker_click$id
   })
   
   output$map1 <- renderLeaflet({
      leaflet() %>% 
         addCircleMarkers(lng = runif(10), lat = runif(10), layerId = paste0("marker", 1:10)) %>%
         addLegend(position = "bottomright",
            colors = "blue",
            title = "Two clicks and no update of legend", 
            labels = values$click
         )
    })
    
}

shinyApp(ui, server)

**Comment by jcheng5** [comment]
Wow, that's crazy. But I can confirm the repro.

Thanks, we'll get to the bottom of this...

**Comment by pssguy** [comment]
I can confirm same with two or more input variables. Only the very first update of either variable gets actioned

**Comment by pssguy** [comment]
Does this mean 
devtools::install_github("rstudio/leaflet")
will now provide bugfix?

**Comment by jcheng5** [comment]
Not until that pull request is merged. In the meantime you can try it with:

```r
devtools::install_github("rstudio/leaflet@joe/bugfix/unbind")

**Comment by jcheng5** [comment]
OK @pssguy, now it's merged :)

**Comment by pssguy** [comment]
@jcheng5 Looks good. Thanks

**Comment by Stephen-McDaniel** [comment]
Works for me in the simple and complex cases.  Thanks!

**Comment by jcheng5** [comment]
So glad to hear it--thanks for the great example @Stephen-McDaniel!
