### ISSUE TITLE
R using geocode with leafletProxy in Shiny to add markers and routes and change colours (SO question)

### ISSUE THREAD

**Issue by hmaeda** [rstudio/leaflet#99]
I was wondering if I could get a bit of help with the question I posted on SO [here](http://stackoverflow.com/questions/30336406/r-using-geocode-with-leafletproxy-in-shiny-to-add-markers-and-route)

To get some help with using leafletProxy to gain the benefits of interactivity...

**Comment by jcheng5** [comment]
Partial answer (I left you a comment to request clarification on the polylines):

```r
library(shiny)
library(shinydashboard)
library(leaflet)
library(ggmap)

header <- dashboardHeader(
  title = 'Simple dashbaord'
)
body <- dashboardBody(
  fluidRow(
    column(width=12,
      leafletOutput('outputmap',height = 550)
    )
  )
)
sidebar <- dashboardSidebar(
  sidebarSearchForm(textId = "origin.val",
    buttonId = "button_click_count",
    label = "Add marker"),
  sliderInput('num','Number of points:',min=1,max=3000,value=30)
)


ui <- dashboardPage(
  header,
  sidebar,
  body
)

server <- function(input,output){
  
  # Run Geocode only when button is clicked
  geocode_origin <- eventReactive(input$button_click_count,{
    geocode(input$origin.val)
  })
  
  # generate base leaflet map
  output$outputmap <- renderLeaflet({
    map <- leaflet() %>% addTiles()
    map
  })
  
  
  observeEvent(input$button_click_count,{
    v <- geocode_origin()
    leafletProxy('outputmap') %>% addCircleMarkers(lng=v$lon,lat=v$lat)
  })
  
  observeEvent(input$num, {
    v <- geocode_origin()
    num.points <- input$num
    lon.path <- c(v$lon,v$lon + cumsum(rnorm(num.points)))
    lat.path <- c(v$lat,v$lat + cumsum(rnorm(num.points)))
    leafletProxy('outputmap') %>% addPolylines(lng=lon.path,lat=lat.path)
  })
  
}

shinyApp(ui, server)
```

**Comment by hmaeda** [comment]
That looks good...Any idea how to change the colour of the line if clicking it?

**Comment by jcheng5** [comment]
Basically you'd make sure your `addPolylines` all keep consistent `layerId` arguments. That lets you mutate those layers later, simply by calling `addPolylines` again with the same `layerId`. See "Understanding Layer IDs" on [this page](http://rstudio.github.io/leaflet/shiny.html) (I'd welcome feedback on the new docs, BTW).

```r
observeEvent(input$outputmap_shape_click, {
  layerId <- input$outputmap_shape_click$id
  leafletProxy("outputmap") %>% addPolylines(..., layerId = layerId)
})

**Comment by hmaeda** [comment]
The new documentation looks good! thanks! One other thing...is there a way to remove multiple polygons/shapes simultaneously with `removeShape` as it doesnt seem to work with a vector of IDs....

**Comment by hmaeda** [comment]
Actually I found it...it works with a vector too
